"use client"
import { useCallback, useEffect, useState } from "react"
import { ArrowLeft, ArrowRight, Check, FileDown, RotateCcw } from "lucide-react"
import { reviewTask, downloadTaskFile } from "@/lib/workspace-api"
import { needsTaskReview, taskDate, taskMemberName, taskYearLabel, type TaskWorkspace, type ReviewEntry, type TaskRun } from "@/lib/task-presentation"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
export function TaskReviewWorkspace({workspace,entries,startId,run,busy,onBack,onDirty}:{workspace:TaskWorkspace;entries:ReviewEntry[];startId?:string;run:TaskRun;busy:boolean;onBack:()=>void;onDirty:(dirty:boolean)=>void}) {
  const [ids]=useState(()=>entries.map(entry=>entry.assignment.id)),[index,setIndex]=useState(()=>Math.max(0,entries.findIndex(entry=>entry.assignment.id===startId))),[handled,setHandled]=useState<string[]>([]),[feedback,setFeedback]=useState(""),[dirty,setDirty]=useState(false),[error,setError]=useState("")
  const id=ids[index],current=workspace.tasks.flatMap(task=>task.assignments.map(assignment=>({task,assignment}))).find(entry=>entry.assignment.id===id)??entries.find(entry=>entry.assignment.id===id)
  const move=useCallback((next:number)=>{if(busy)return;if(dirty&&!window.confirm("Leave this review? Unsaved feedback will be lost."))return;setIndex(next);setFeedback("");setDirty(false);onDirty(false);setError("")},[busy,dirty,onDirty])
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(!event.altKey||event.ctrlKey||event.metaKey||event.target instanceof HTMLElement&&event.target.matches("input,textarea,select,[contenteditable]"))return;if(event.key==="ArrowRight"&&index<ids.length-1){event.preventDefault();move(index+1)}else if(event.key==="ArrowLeft"&&index>0){event.preventDefault();move(index-1)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[index,ids.length,move])
  async function review(requestChanges:boolean){if(!current)return;setError("");if(requestChanges&&!feedback.trim()){setError("Add feedback explaining what needs to change.");return}const success=await run(()=>reviewTask({assignmentId:current.assignment.id,revision:current.assignment.revision,feedback,reopen:requestChanges,requestChanges}));if(success){setHandled(previous=>[...new Set([...previous,id])]);setDirty(false);onDirty(false);setFeedback("");const remaining=(candidate:string)=>candidate!==id&&!handled.includes(candidate)&&workspace.tasks.some(task=>task.assignments.some(assignment=>assignment.id===candidate&&needsTaskReview(assignment)));const later=ids.findIndex((candidate,i)=>i>index&&remaining(candidate));const next=later<0?ids.findIndex(remaining):later;setIndex(next<0?ids.length:next)}}
  const pending=current && needsTaskReview(current.assignment) && !handled.includes(id)
  return <section className="oc-review-workspace space-y-5" aria-label="Submission review" data-unsaved={dirty} data-saving={busy}>
    <div className="oc-review-top"><Button type="button" variant="ghost" onClick={()=>{if(!dirty||window.confirm("Leave this review? Unsaved feedback will be lost.")){onDirty(false);onBack()}}} disabled={busy}><ArrowLeft size={16}/>Review queue</Button><p role="status">{handled.length} of {ids.length} processed</p></div>
    {!current||index>=ids.length?<div className="oc-review-finished"><Check size={24}/><h3 className="oc-section-heading">This queue is complete.</h3><p className="text-sm text-muted-foreground">Your reviews are saved. Return to Needs Review to pick up new submissions.</p><Button type="button" onClick={onBack}>Back to Needs Review</Button>{ids.length>0 && <Button type="button" variant="ghost" onClick={()=>move(0)}>Revisit this session</Button>}</div>:<>
      <header className="oc-review-heading"><p className="oc-eyebrow">{current.task.title} · {index+1} of {ids.length}</p><div className="flex items-center gap-3"><span className="oc-task-avatar" aria-hidden="true">{taskMemberName(current.assignment.member).split(/\s+/).map(word=>word[0]).slice(0,2).join("")}</span><div className="min-w-0"><h3 className="oc-section-heading break-words">{taskMemberName(current.assignment.member)}</h3><p className="text-xs text-muted-foreground">{current.assignment.member.user.studentProfile?.gradYear?taskYearLabel(current.assignment.member.user.studentProfile.gradYear):"Year not provided"}{current.assignment.member.groups.length?` · ${current.assignment.member.groups.join(", ")}`:""}{current.assignment.member.cohort?` · ${current.assignment.member.cohort}`:""}{current.assignment.groupLabel?` · ${current.assignment.groupLabel}`:""}</p></div></div><p className="text-xs text-muted-foreground">Submitted {taskDate(current.assignment.submittedAt)}</p></header>
      <section className="oc-review-submission"><h4 className="oc-task-field-label">Submission</h4>{current.assignment.text && <p className="whitespace-pre-wrap break-words text-sm leading-7">{current.assignment.text}</p>}{current.assignment.link && <a className="break-all text-sm underline" target="_blank" rel="noreferrer" href={current.assignment.link}>{current.assignment.link} ↗</a>}{current.assignment.files.map(file=><Button type="button" variant="outline" className="max-w-full whitespace-normal break-all" key={file.id} onClick={async()=>{setError("");try{const {url}=await downloadTaskFile(file.id);window.location.assign(url)}catch(error){setError(error instanceof Error?error.message:"Could not download file.")}}}><FileDown size={16}/>{file.name} · {Math.ceil(file.size/1024)} KB</Button>)}{!current.assignment.text&&!current.assignment.link&&!current.assignment.files.length && <p className="text-sm text-muted-foreground">No response content is recorded.</p>}</section>
      <details className="oc-task-resources"><summary>Assignment instructions</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{current.task.description||"No additional instructions."}</p></details>
      {pending?<section className="space-y-3"><label className="oc-task-field-label">Feedback<Textarea rows={4} maxLength={5000} placeholder="Optional for approval; required for revisions." value={feedback} disabled={busy} onChange={event=>{setFeedback(event.target.value);setDirty(true);onDirty(true)}}/></label><div className="oc-review-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>void review(true)}><RotateCcw size={16}/>Request revision</Button><Button type="button" disabled={busy} onClick={()=>void review(false)}>{busy?"Saving…":"Approve & next"}<Check size={16}/></Button></div></section>:<div className="oc-recipient-preview"><p className="text-sm font-medium">{current.assignment.revisionRequestedAt?"Revision requested":current.assignment.reviewedAt||handled.includes(id)?"Review saved":"This submission is no longer awaiting review."}</p>{current.assignment.feedback && <p className="mt-2 whitespace-pre-wrap text-sm">{current.assignment.feedback}</p>}</div>}
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      <nav aria-label="Submission navigation" className="oc-review-navigation"><Button type="button" variant="outline" disabled={busy||index===0} onClick={()=>move(index-1)}><ArrowLeft size={16}/>Previous</Button><span className="hidden text-xs text-muted-foreground sm:block">Alt + ← / →</span><Button type="button" variant="outline" disabled={busy||index>=ids.length-1} onClick={()=>move(index+1)}>Next<ArrowRight size={16}/></Button></nav>
    </>}
  </section>
}
