"use client"
import { compareAcademicYears } from "@/lib/recruitment-profile"
import { useEffect, useRef, useState } from "react"
import { ArrowLeft, ArrowRight, Plus, Copy, Users, CalendarClock, RefreshCw } from "lucide-react"
import { taskAudienceSchema, taskInputSchema, taskState } from "@/lib/tasks"
import { taskCounts, taskManagerSummary, taskReviewQueue, taskDate, taskAudienceLabel, taskMemberName, memberTaskCounts, type TaskWorkspace, type ClubTask, type ReviewEntry, type TaskRun } from "@/lib/task-presentation"
import { bulkUpdateTasks, bulkApproveTaskSubmissions, addTaskRecipients, reviewTask, updateTaskMember } from "@/lib/workspace-api"
import { TaskMemberList, TaskRecipientPreview } from "./task-audience-builder"
import { TaskAssignmentBuilder } from "./task-assignment-builder"
import { TaskReviewWorkspace } from "./task-review-workspace"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet"
import { hasPermission } from "@/lib/permissions"
import { useAuth } from "@/contexts/auth-context"
const views=[{id:"active",label:"Active"},{id:"review",label:"Needs Review"},{id:"overdue",label:"Overdue"},{id:"projects",label:"Projects"},{id:"members",label:"Members"},{id:"completed",label:"Completed"}]
export function TaskManagerWorkspace({workspace,run,busy,error,onRefresh,onPersonal,onDirty}:{workspace:TaskWorkspace;run:TaskRun;busy:boolean;error:string;onRefresh:()=>void;onPersonal:()=>void;onDirty:(dirty:boolean)=>void}) {
  const {user}=useAuth(),membership=user?.memberships.find(member=>member.clubId===workspace.clubId)
  const [view,setView]=useState("active"),[dueWeekOnly,setDueWeekOnly]=useState(false),[query,setQuery]=useState(""),[detailId,setDetail]=useState<string|null>(null),[builder,setBuilder]=useState<{source?:ClubTask;editing?:boolean;kind?:"TASK"|"PROJECT";projectId?:string}|null>(null),[dirty,setDirty]=useState(false),[review,setReview]=useState<{entries:ReviewEntry[];startId?:string}|null>(null),[selected,setSelected]=useState<string[]>([]),[reviewSelected,setReviewSelected]=useState<string[]>([]),[bulk,setBulk]=useState<"DUE"|"CLOSE"|"APPROVE"|null>(null),[bulkDue,setBulkDue]=useState(""),[memberId,setMember]=useState<string|null>(null),[taskFilter,setTaskFilter]=useState(""),[projectFilter,setProjectFilter]=useState(""),[yearFilter,setYearFilter]=useState(""),[groupFilter,setGroupFilter]=useState("")
  const trigger=useRef<HTMLElement|null>(null),now=Date.now(),summary=taskManagerSummary(workspace.tasks,now),projects=workspace.tasks.filter(task=>task.kind==="PROJECT"),detail=workspace.tasks.find(task=>task.id===detailId)
  function markDirty(value:boolean){setDirty(value);onDirty(value)}
  function close(){if(busy)return;if(dirty&&!window.confirm("Close this workspace? Unsaved changes will be lost."))return;setBuilder(null);setReview(null);setDetail(null);setBulk(null);markDirty(false)}
  function openBuilder(value:NonNullable<typeof builder>,event?:React.MouseEvent<HTMLElement>){trigger.current=event?.currentTarget??document.activeElement as HTMLElement;setBuilder(value);setDetail(null);markDirty(false)}
  function openReview(entries:ReviewEntry[],startId?:string){if(!entries.length)return;trigger.current=document.activeElement as HTMLElement;setReview({entries,startId});setDetail(null);markDirty(false)}
  function changeView(next:string){setView(next);setDueWeekOnly(false);setSelected([]);setReviewSelected([]);setMember(null)}
  const matching=(task:ClubTask)=>`${task.title} ${task.description} ${task.projectId?projects.find(project=>project.id===task.projectId)?.title??"":""}`.toLowerCase().includes(query.toLowerCase())
  const tasks=workspace.tasks.filter(task=>task.kind==="TASK"&&matching(task)&&(!dueWeekOnly||task.status!=="DRAFT"&&task.assignments.length>0&&!!task.dueAt&&+new Date(task.dueAt)>=now&&+new Date(task.dueAt)<now+7*86400000)).filter(task=>view==="completed"?task.status==="DONE"||taskCounts(task).reviewed>0:view==="overdue"?taskCounts(task,now).overdue>0:task.status!=="DONE"&&(task.status==="DRAFT"||taskCounts(task).reviewed<task.assignments.length||!task.assignments.length))
  const reviewQueue=taskReviewQueue(workspace.tasks).filter(({task,assignment})=>(!taskFilter||task.id===taskFilter)&&(!projectFilter||task.projectId===projectFilter)&&(!yearFilter||assignment.member.user.studentProfile?.academicYear===yearFilter)&&(!groupFilter||assignment.groupLabel===groupFilter||assignment.member.groups.includes(groupFilter)||assignment.member.cohort===groupFilter)&&`${taskMemberName(assignment.member)} ${assignment.member.user.email} ${task.title}`.toLowerCase().includes(query.toLowerCase()))
  const years=[...new Set(workspace.members.flatMap(member=>member.user.studentProfile?.academicYear?[member.user.studentProfile.academicYear]:[]))].sort(compareAcademicYears),groups=[...new Set([...workspace.members.flatMap(member=>[...member.groups,...member.cohort?[member.cohort]:[]]),...workspace.tasks.flatMap(task=>task.assignments.flatMap(assignment=>assignment.groupLabel?[assignment.groupLabel]:[]))])].sort()
  const bulkTasks=workspace.tasks.filter(task=>selected.includes(task.id)),bulkEntries=reviewQueue.filter(entry=>reviewSelected.includes(entry.assignment.id))
  const managerMembers=[...workspace.members,...workspace.tasks.flatMap(task=>task.assignments.filter(assignment=>!workspace.members.some(member=>member.id===assignment.member.id)).map(assignment=>assignment.member))].filter((member,index,array)=>array.findIndex(other=>other.id===member.id)===index)
  useEffect(()=>{setSelected(ids=>ids.filter(id=>workspace.tasks.some(task=>task.id===id)));setReviewSelected(ids=>ids.filter(id=>taskReviewQueue(workspace.tasks).some(entry=>entry.assignment.id===id)))},[workspace])
  async function confirmBulk(){const success=await run(()=>bulk==="APPROVE"?bulkApproveTaskSubmissions({clubId:workspace.clubId,assignments:bulkEntries.map(({assignment})=>({id:assignment.id,revision:assignment.revision}))}):bulkUpdateTasks({clubId:workspace.clubId,tasks:bulkTasks.map(task=>({id:task.id,revision:task.revision})),action:bulk as "DUE"|"CLOSE",dueAt:bulkDue?new Date(bulkDue).toISOString():null}));if(success){setBulk(null);setSelected([]);setReviewSelected([])}}
  function taskRow(task:ClubTask){const counts=taskCounts(task,now);return <li className="oc-manager-task-row" key={task.id}>
    <input type="checkbox" aria-label={`Select ${task.title}`} disabled={task.status==="DRAFT"} checked={selected.includes(task.id)} onChange={event=>setSelected(event.target.checked?[...selected,task.id]:selected.filter(id=>id!==task.id))}/>
    <div className="oc-manager-task-copy"><button type="button" className="oc-task-title-button" onClick={event=>{trigger.current=event.currentTarget;task.status==="DRAFT"?openBuilder({source:task,editing:true},event):setDetail(task.id)}}>{task.title}</button><p>{task.status==="DRAFT"?"Draft · not assigned":`${taskAudienceLabel(task)} · ${counts.assigned} assigned`}{task.projectId?` · ${projects.find(project=>project.id===task.projectId)?.title??"Related project"}`:""}</p>{task.status!=="DRAFT" && <><div className="oc-task-inline-meta"><span>{counts.submitted} submitted</span>{task.status!=="DONE"&&counts.pending-counts.overdue>0 && <span>{counts.pending-counts.overdue} pending</span>}{counts.overdue>0 && <span className="text-destructive">{counts.overdue} overdue</span>}{counts.revisions>0 && <span>{counts.revisions} revisions requested</span>}<span>{counts.reviewed}/{counts.assigned} reviewed</span></div><progress className="oc-task-progress" aria-label={`Reviewed submissions for ${task.title}`} value={counts.reviewed} max={Math.max(1,counts.assigned)}/></>}</div>
    <div className="oc-manager-task-next"><span><CalendarClock size={14}/> {taskDate(task.dueAt)}</span><Button type="button" size="sm" variant={view!=="overdue"&&view!=="completed"&&counts.needsReview?"default":"outline"} onClick={()=>view==="overdue"||view==="completed"?setDetail(task.id):task.status==="DRAFT"?openBuilder({source:task,editing:true}):counts.needsReview?openReview(taskReviewQueue([task])):setDetail(task.id)}>{view==="overdue"?`View ${counts.overdue} overdue ${counts.overdue===1?"member":"members"}`:view==="completed"?counts.reviewed?`View ${counts.reviewed} reviewed submissions`:"View closed work":task.status==="DRAFT"?"Finish assigning":counts.needsReview?`Review ${counts.needsReview} submissions`:"View progress"}<ArrowRight size={15}/></Button></div>
  </li>}
  return <div className="oc-task-manager space-y-5" data-unsaved={dirty} data-saving={busy}>
    <div className="oc-task-manager-toolbar"><div role="group" aria-label="Task workspace" className="flex gap-1 rounded-md border bg-card p-1"><Button type="button" variant="ghost" onClick={onPersonal} disabled={busy}>My Tasks</Button><Button type="button" variant="secondary" aria-pressed>Manage</Button></div><div className="flex gap-2"><Button type="button" variant="ghost" onClick={onRefresh} disabled={busy} aria-label="Refresh tasks"><RefreshCw size={16}/></Button><Button type="button" variant="outline" onClick={event=>openBuilder({kind:"PROJECT"},event)}>New project</Button><Button type="button" onClick={event=>openBuilder({},event)}><Plus size={16}/>New task</Button></div></div>
    <div className="oc-manager-task-metrics" aria-label="Club task totals">{[{key:"needsReview",label:"Needs review",view:"review"},{key:"overdue",label:"Overdue",view:"overdue"},{key:"dueThisWeek",label:"Due this week",view:"active"},{key:"completed",label:"Completed",view:"completed"}].filter(metric=>summary[metric.key as keyof typeof summary]>0).map(metric=><button type="button" key={metric.key} onClick={()=>{changeView(metric.view);if(metric.key==="dueThisWeek")setDueWeekOnly(true)}}><strong>{summary[metric.key as keyof typeof summary]}</strong><span>{metric.label}</span></button>)}</div>
    <nav className="oc-task-view-tabs" aria-label="Manage tasks">{views.map(item=><button type="button" key={item.id} aria-current={view===item.id?"page":undefined} onClick={()=>changeView(item.id)}>{item.label}{item.id==="review"&&summary.needsReview>0&&<span>{summary.needsReview}</span>}</button>)}</nav>
    {error && <p role="alert" className="oc-task-error">{error}</p>}
    <Input aria-label={view==="review"?"Search submissions by member or task":view==="members"?"Search members":"Search tasks and projects"} type="search" placeholder={view==="review"?"Search a member or assignment":view==="members"?"Find a member":"Find a task or project"} value={query} onChange={event=>setQuery(event.target.value)}/>
    {dueWeekOnly && <div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>Due in the next seven days</span><Button type="button" variant="ghost" size="sm" onClick={()=>setDueWeekOnly(false)}>Show all active tasks</Button></div>}
    {view==="review"?<>
      <div className="oc-review-filters"><label>Task<select className="oc-task-select" value={taskFilter} onChange={event=>setTaskFilter(event.target.value)}><option value="">All tasks</option>{workspace.tasks.filter(task=>task.kind==="TASK").map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select></label><label>Project<select className="oc-task-select" value={projectFilter} onChange={event=>setProjectFilter(event.target.value)}><option value="">All projects</option>{projects.map(project=><option key={project.id} value={project.id}>{project.title}</option>)}</select></label><label>Class year<select className="oc-task-select" value={yearFilter} onChange={event=>setYearFilter(event.target.value)}><option value="">All years</option>{years.map(year=><option key={year} value={year}>{year}</option>)}</select></label><label>Group / cohort<select className="oc-task-select" value={groupFilter} onChange={event=>setGroupFilter(event.target.value)}><option value="">All groups & cohorts</option>{groups.map(group=><option key={group} value={group}>{group}</option>)}</select></label></div>
      {reviewQueue.length>0 && <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm" role="status">{reviewQueue.length} submissions awaiting review</p><Button type="button" onClick={()=>openReview(reviewQueue)}>Review queue<ArrowRight size={16}/></Button></div>}
      {reviewSelected.length>0 && <div className="oc-task-bulk-bar"><span>{bulkEntries.length} selected</span><Button type="button" variant="outline" disabled={!bulkEntries.length||busy||bulkEntries.length>50} onClick={()=>setBulk("APPROVE")}>Approve selected</Button><Button type="button" variant="ghost" onClick={()=>setReviewSelected([])}>Clear</Button></div>}
      <div className="space-y-4">{workspace.tasks.filter(task=>reviewQueue.some(entry=>entry.task.id===task.id)).map(task=>{const entries=reviewQueue.filter(entry=>entry.task.id===task.id);return <section className="oc-review-queue-card" key={task.id}><header><div><h3>{task.title}</h3><p>{entries.length} waiting · {taskCounts(task).reviewed}/{task.assignments.length} reviewed</p></div><Button type="button" variant="outline" onClick={()=>openReview(entries)}>Review<ArrowRight size={15}/></Button></header><ul>{entries.map(entry=><li key={entry.assignment.id}><input type="checkbox" aria-label={`Select submission by ${taskMemberName(entry.assignment.member)} for ${task.title}`} checked={reviewSelected.includes(entry.assignment.id)} onChange={event=>setReviewSelected(event.target.checked?[...reviewSelected,entry.assignment.id]:reviewSelected.filter(id=>id!==entry.assignment.id))}/><span className="oc-task-avatar" aria-hidden="true">{taskMemberName(entry.assignment.member).split(/\s+/).map(word=>word[0]).slice(0,2).join("")}</span><div><strong>{taskMemberName(entry.assignment.member)}</strong><p>Submitted {taskDate(entry.assignment.submittedAt)}</p></div><Button type="button" size="sm" variant="ghost" onClick={()=>openReview(entries,entry.assignment.id)}>Open submission</Button></li>)}</ul></section>})}</div>{!reviewQueue.length && <TaskEmpty title="No submissions to review." description="New submissions will appear here. Change your filters to review another group."/>}
    </>:view==="projects"?<div className="space-y-4">{projects.filter(matching).map(project=>{const children=workspace.tasks.filter(task=>task.projectId===project.id);return <details className="oc-task-project" key={project.id} open><summary><strong>{project.title}</strong><span>{children.length} tasks · Due {taskDate(project.dueAt)}</span></summary><div className="flex flex-wrap gap-2 py-3"><Button type="button" size="sm" onClick={event=>openBuilder({projectId:project.id},event)}><Plus size={15}/>Add task</Button><Button type="button" size="sm" variant="ghost" onClick={()=>setDetail(project.id)}>Project progress</Button></div><ul className="oc-manager-task-list">{children.map(taskRow)}</ul>{!children.length && <p className="py-3 text-sm text-muted-foreground">Add the first task to this project.</p>}</details>})}{!projects.filter(matching).length && <TaskEmpty title="Organize related work in a project." description="Create a collection, then add assignments as members work through it."/>}</div>:view==="members"?<>
      <ul className="oc-task-members">{managerMembers.filter(member=>taskMemberName(member).toLowerCase().includes(query.toLowerCase())).filter(member=>!memberId||member.id===memberId).map(member=>{const progress=memberTaskCounts(workspace.tasks,member.id,now);return <li key={member.id}><button type="button" onClick={()=>setMember(memberId?null:member.id)}><span className="oc-task-avatar" aria-hidden="true">{taskMemberName(member).split(/\s+/).map(word=>word[0]).slice(0,2).join("")}</span><div><strong>{taskMemberName(member)}</strong><p>{member.user.studentProfile?.academicYear?member.user.studentProfile.academicYear:"Year not provided"} · {member.groups.join(", ") || "No group"}</p><div className="oc-task-inline-meta"><span>{progress.assigned} assigned</span><span>{progress.completed} completed</span>{progress.awaiting>0&&<span>{progress.awaiting} awaiting review</span>}{progress.overdue>0&&<span className="text-destructive">{progress.overdue} overdue</span>}</div></div><ArrowRight size={16}/></button>{memberId===member.id && <ul className="oc-member-work">{progress.entries.map(({task,assignment})=><li key={assignment.id}><Button type="button" variant="ghost" onClick={()=>setDetail(task.id)}>{task.title}</Button><span>{taskState(task,assignment)} · Due {taskDate(task.dueAt)}</span></li>)}</ul>}</li>})}</ul>{memberId && <Button type="button" variant="ghost" onClick={()=>setMember(null)}><ArrowLeft size={15}/>All members</Button>}
      {hasPermission(membership,"members.manage") && <details className="oc-task-resources"><summary>Manage groups & cohorts</summary><p className="mt-3 text-xs text-muted-foreground">Roster labels affect new assignments. Existing recipients stay fixed.</p>{workspace.members.map(member=><form className="oc-task-member-labels" key={member.id} onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);await run(()=>updateTaskMember({clubId:workspace.clubId,memberId:member.id,groups:String(data.get("groups")).split(",").map(group=>group.trim()).filter(Boolean),cohort:String(data.get("cohort")).trim()||null}))}}><strong>{taskMemberName(member)}</strong><label>Groups<Input name="groups" defaultValue={member.groups.join(", ")}/></label><label>Cohort<Input name="cohort" maxLength={80} defaultValue={member.cohort??""}/></label><Button size="sm" variant="outline" disabled={busy}>Save labels<span className="sr-only"> for {taskMemberName(member)}</span></Button></form>)}</details>}
    </>:<>
      {selected.length>0 && <div className="oc-task-bulk-bar"><span>{selected.length} tasks selected</span><Button type="button" variant="outline" disabled={busy||selected.length>100} onClick={()=>setBulk("DUE")}>Change due date</Button><Button type="button" variant="outline" disabled={busy||selected.length>100} onClick={()=>setBulk("CLOSE")}>Close tasks</Button><Button type="button" variant="ghost" onClick={()=>setSelected([])}>Clear</Button></div>}
      <ul className="oc-manager-task-list">{tasks.map(taskRow)}</ul>{!tasks.length && <TaskEmpty title={view==="overdue"?"No overdue work in this view.":view==="completed"?"No completed work in this view.":"Create your next assignment."} description={view==="active"?"Choose who receives it, preview the list, and assign in one place.":"Change the view or search to find other assignments."}/>}
    </>}
    <Sheet open={!!builder||!!review||!!detail||!!bulk} onOpenChange={open=>{if(!open)close()}}><SheetContent className="oc-workspace-drawer oc-task-manager-drawer w-full overflow-y-auto sm:max-w-3xl" onCloseAutoFocus={event=>{event.preventDefault();if(trigger.current?.isConnected)trigger.current.focus();else document.getElementById("workspace-content")?.focus()}}><SheetTitle>{builder?builder.editing?"Edit assignment":builder.source?"Duplicate task":builder.kind==="PROJECT"?"New project":"New task":review?"Review submissions":bulk?"Confirm bulk action":detail?.title||"Task"}</SheetTitle><SheetDescription>{builder?"Create, choose recipients, and preview before assigning.":review?"Read, give feedback, and move to the next submission.":bulk?"Check the affected records before saving.":"Assignment details and member progress."}</SheetDescription>{error && <p role="alert" className="oc-task-error">{error}</p>}
      {builder && <TaskAssignmentBuilder key={`${builder.source?.id??"new"}:${builder.editing??false}:${builder.kind??"TASK"}:${builder.projectId??""}`} workspace={workspace} {...builder} run={run} busy={busy} onSaved={()=>{setBuilder(null);markDirty(false)}} onDirty={()=>markDirty(true)}/>}
      {review && <TaskReviewWorkspace workspace={workspace} {...review} run={run} busy={busy} onDirty={markDirty} onBack={()=>{setReview(null);changeView("review")}}/>}
      {bulk && <section className="space-y-5"><p className="text-sm leading-6">{bulk==="APPROVE"?`Approve ${bulkEntries.length} selected submissions? This will mark them reviewed and lock member editing.`:bulk==="CLOSE"?`Close ${bulkTasks.length} selected tasks, affecting ${bulkTasks.reduce((sum,task)=>sum+task.assignments.length,0)} assignments? Members will no longer be able to submit to these tasks.`:`Change the due date for ${bulkTasks.length} tasks, affecting ${bulkTasks.reduce((sum,task)=>sum+task.assignments.length,0)} assignments?`}</p>{bulk==="APPROVE" && <p className="text-xs text-muted-foreground">Use bulk approval only after checking the selected submissions. Revision requests are excluded.</p>}<ul className="oc-recipient-scroll list-disc pl-5 text-sm">{bulk==="APPROVE"?bulkEntries.map(({task,assignment})=><li key={assignment.id}>{taskMemberName(assignment.member)} · {task.title}</li>):bulkTasks.map(task=><li key={task.id}>{task.title}</li>)}</ul>{bulk==="DUE" && <label className="oc-task-field-label">New due date & time<Input type="datetime-local" value={bulkDue} onChange={event=>setBulkDue(event.target.value)}/><small>Leave empty to remove the due date.</small></label>}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={()=>setBulk(null)} disabled={busy}>Cancel</Button><Button type="button" onClick={()=>void confirmBulk()} disabled={busy||(bulk==="APPROVE"?!bulkEntries.length:!bulkTasks.length)}>{busy?"Saving…":bulk==="APPROVE"?`Approve ${bulkEntries.length} submissions`:bulk==="CLOSE"?"Close selected tasks":"Update due dates"}</Button></div></section>}
      {detail && !builder && !review && <TaskManagerDetail key={`${detail.id}:${view}`} initialFilter={view==="overdue"?"overdue":view==="completed"?"completed":"all"} task={detail} workspace={workspace} run={run} busy={busy} onEdit={()=>openBuilder({source:detail,editing:true})} onDuplicate={()=>openBuilder({source:detail})} onReview={entries=>openReview(entries)} onDirty={markDirty}/>}
    </SheetContent></Sheet>
  </div>
}
function TaskEmpty({title,description}:{title:string;description:string}) {return <div className="oc-task-manager-empty"><h3 className="oc-section-heading">{title}</h3><p>{description}</p></div>}
function TaskManagerDetail({task,workspace,run,busy,onEdit,onDuplicate,onReview,onDirty,initialFilter="all"}:{task:ClubTask;workspace:TaskWorkspace;run:TaskRun;busy:boolean;onEdit:()=>void;onDuplicate:()=>void;onReview:(entries:ReviewEntry[])=>void;onDirty:(dirty:boolean)=>void;initialFilter?:string}) {
  const [filter,setFilter]=useState(initialFilter),[query,setQuery]=useState(""),[adding,setAdding]=useState(false),[members,setMembers]=useState<string[]>([])
  const counts=taskCounts(task),available=workspace.members.filter(member=>!task.assignments.some(assignment=>assignment.memberId===member.id)),resources=taskInputSchema.shape.resources.safeParse(task.resources).data??[]
  const visible=task.assignments.filter(assignment=>taskMemberName(assignment.member).toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="completed"&&(!!assignment.reviewedAt||task.status==="DONE")||filter==="review"&&!!assignment.submittedAt&&!assignment.reviewedAt&&!assignment.revisionRequestedAt||filter==="pending"&&!assignment.reviewedAt&&(!assignment.submittedAt||assignment.revisionRequestedAt)||filter==="overdue"&&task.dueAt&&+new Date(task.dueAt)<Date.now()&&!assignment.reviewedAt&&(!assignment.submittedAt||assignment.revisionRequestedAt)))
  return <section className="space-y-5"><div className="oc-task-inline-meta"><span>{taskAudienceLabel(task)} · {counts.assigned} assigned</span><span>Due {taskDate(task.dueAt)}</span><span>{task.status==="DONE"?"Closed":task.status.replaceAll("_"," ").toLowerCase()}</span></div><p className="whitespace-pre-wrap text-sm leading-7">{task.description||"No additional instructions."}</p>{resources.length>0 && <ul className="space-y-2 text-sm">{resources.map((resource,index)=><li key={index}><a href={resource.url} target="_blank" rel="noreferrer" className="break-all underline">{resource.label} ↗</a></li>)}</ul>}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={onEdit}>Edit details</Button><Button type="button" variant="outline" onClick={onDuplicate}><Copy size={15}/>Duplicate {task.kind==="PROJECT"?"project":"task"}</Button>{task.status!=="DONE"&&task.status!=="DRAFT"&&available.length>0&&<Button type="button" variant="outline" onClick={()=>setAdding(!adding)}><Users size={15}/>Add recipients</Button>}{counts.needsReview>0&&<Button type="button" onClick={()=>onReview(taskReviewQueue([task]))}>Review {counts.needsReview} submissions<ArrowRight size={15}/></Button>}</div>
    {adding && <section className="oc-builder-section"><h3>Add recipients</h3><TaskMemberList members={available} selected={members} onChange={ids=>{setMembers(ids);onDirty(true)}}/><TaskRecipientPreview recipients={available.filter(member=>members.includes(member.id)).map(member=>({member,groupLabel:null}))}/><Button type="button" disabled={busy||!members.length} onClick={async()=>{if(!window.confirm(`Assign this task to ${members.length} additional members? Existing work will be preserved.`))return;if(await run(()=>addTaskRecipients({clubId:workspace.clubId,taskId:task.id,revision:task.revision,audience:taskAudienceSchema.parse({members}),expectedRecipients:members}))){setAdding(false);setMembers([]);onDirty(false)}}}>Assign to {members.length} more members</Button></section>}
    <div className="flex flex-wrap gap-3"><label className="oc-task-field-label">Member<Input type="search" placeholder="Search recipients" value={query} onChange={event=>setQuery(event.target.value)}/></label><label className="oc-task-field-label">Progress<select className="oc-task-select" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All recipients</option><option value="review">Needs review</option><option value="pending">Pending / revisions</option><option value="overdue">Overdue</option><option value="completed">Reviewed / closed</option></select></label></div><ul className="oc-task-progress-members">{visible.map(assignment=><li key={assignment.id}><div><strong>{taskMemberName(assignment.member)}</strong><p>{taskState(task,assignment)}{assignment.groupLabel?` · ${assignment.groupLabel}`:""} · {assignment.viewedAt?"Viewed":"Not viewed"}</p>{assignment.feedback&&<p className="whitespace-pre-wrap">{assignment.feedback}</p>}</div>{task.kind==="PROJECT"?<Button type="button" size="sm" variant="outline" disabled={busy} onClick={()=>void run(()=>reviewTask({assignmentId:assignment.id,revision:assignment.revision,feedback:assignment.feedback,reopen:!!assignment.reviewedAt}))}>{assignment.reviewedAt?"Reopen progress":"Mark complete"}</Button>:<div className="flex flex-wrap gap-2">{assignment.reviewedAt&&<Button type="button" variant="outline" size="sm" disabled={busy} onClick={()=>void run(()=>reviewTask({assignmentId:assignment.id,revision:assignment.revision,feedback:assignment.feedback,reopen:true}))}>Reopen submission</Button>}{assignment.submittedAt&&<Button type="button" variant="ghost" size="sm" onClick={()=>onReview(task.assignments.filter(a=>a.submittedAt).map(a=>({task,assignment:a})).sort((a,b)=>a.assignment.id===assignment.id?-1:b.assignment.id===assignment.id?1:0))}>Open submission</Button>}</div>}</li>)}</ul>{!visible.length && <p className="text-sm text-muted-foreground">No recipients match this filter.</p>}
  </section>
}
