"use client"
import { useState } from "react"
import { Search, Shuffle, Users, UserRound, GraduationCap, Shield, Layers, SlidersHorizontal } from "lucide-react"
import { taskAudienceSchema, resolveTaskRecipients, type TaskAudience } from "@/lib/tasks"
import { taskAudienceMode, taskMemberName, taskYearLabel, taskRoleLabels, type TaskWorkspace, type TaskMember } from "@/lib/task-presentation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
const choices=[{id:"everyone",label:"Everyone",icon:Users},{id:"members",label:"Choose members",icon:UserRound},{id:"years",label:"Class year",icon:GraduationCap},{id:"groups",label:"Groups & cohorts",icon:Layers},{id:"roles",label:"Role",icon:Shield},{id:"random",label:"Random",icon:Shuffle},{id:"advanced",label:"Advanced",icon:SlidersHorizontal}]
export function TaskMemberList({members,selected,onChange,label="Choose members"}:{members:TaskMember[];selected:string[];onChange:(ids:string[])=>void;label?:string}) {
  const [query,setQuery]=useState("")
  const visible=members.filter(member=>`${taskMemberName(member)} ${member.user.email} ${member.user.studentProfile?.gradYear ?? ""} ${member.groups.join(" ")}`.toLowerCase().includes(query.toLowerCase()))
  return <section className="oc-recipient-selector" aria-label={label}>
    <label className="oc-task-search"><Search size={16} aria-hidden="true"/><Input aria-label={`Search ${label.toLowerCase()}`} type="search" placeholder="Search members, years, or groups" value={query} onChange={event=>setQuery(event.target.value)}/></label>
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs"><span role="status">{selected.length} members selected</span><div><Button type="button" size="sm" variant="ghost" onClick={()=>onChange([...new Set([...selected,...visible.map(member=>member.id)])])}>Select all{query ? " results" : ""}</Button><Button type="button" size="sm" variant="ghost" onClick={()=>onChange([])}>Clear</Button></div></div>
    <div className="oc-recipient-scroll">{visible.map(member=><label className="oc-recipient-person" key={member.id}><input type="checkbox" checked={selected.includes(member.id)} onChange={event=>onChange(event.target.checked?[...selected,member.id]:selected.filter(id=>id!==member.id))}/><span className="oc-task-avatar" aria-hidden="true">{taskMemberName(member).split(/\s+/).map(word=>word[0]).slice(0,2).join("")}</span><span><strong>{taskMemberName(member)}</strong><small>{member.user.studentProfile?.gradYear ? taskYearLabel(member.user.studentProfile.gradYear) : "Year not provided"} · {taskRoleLabels[member.role]}{member.groups.length ? ` · ${member.groups.join(", ")}` : ""}</small></span></label>)}{!visible.length && <p className="py-3 text-sm text-muted-foreground">No matching members.</p>}</div>
  </section>
}
export function TaskRecipientPreview({recipients}:{recipients:{member:TaskMember;groupLabel:string|null}[]}) {
  const [all,setAll]=useState(false)
  return <section className="oc-recipient-preview" aria-label="Recipient preview"><div className="flex flex-wrap items-center justify-between gap-2"><strong role="status">{recipients.length} recipients</strong>{recipients.length>4 && <Button type="button" variant="ghost" size="sm" onClick={()=>setAll(!all)}>{all?"Show fewer":`View all ${recipients.length}`}</Button>}</div><ul className={all?"oc-recipient-scroll":""}>{recipients.slice(0,all?undefined:4).map(({member,groupLabel})=><li className="oc-recipient-person" key={member.id}><span className="oc-task-avatar" aria-hidden="true">{taskMemberName(member).split(/\s+/).map(word=>word[0]).slice(0,2).join("")}</span><span><strong>{taskMemberName(member)}</strong><small>{member.user.studentProfile?.gradYear ?? "Year not provided"}{groupLabel ? ` · ${groupLabel}` : ""}</small></span></li>)}</ul>{!recipients.length && <p className="mt-2 text-sm text-muted-foreground">Choose who should receive this assignment.</p>}</section>
}
export function TaskAudienceBuilder({workspace,value,onChange,mode:initialMode,onModeChange,omitMembers=[]}:{workspace:TaskWorkspace;value:TaskAudience;onChange:(audience:TaskAudience)=>void;mode?:string;onModeChange?:(mode:string)=>void;omitMembers?:string[]}) {
  const [mode,setMode]=useState(initialMode ?? taskAudienceMode(value)),[pool,setPool]=useState(value.everyone?"everyone":value.years.length?"years":value.groups.length||value.cohorts.length?"groups":value.roles.length?"roles":value.members.length?"members":"everyone"),[randomKind,setRandomKind]=useState(value.random?.groups?"groups":"sample"),[count,setCount]=useState(value.random?.count ?? 10),[groupCount,setGroupCount]=useState(value.random?.groups ?? 3)
  const members=workspace.members.filter(member=>!omitMembers.includes(member.id)),groups=[...new Set(members.flatMap(member=>member.groups))].sort(),cohorts=[...new Set(members.flatMap(member=>member.cohort?[member.cohort]:[]))].sort(),years=[...new Set(members.flatMap(member=>member.user.studentProfile?.gradYear?[member.user.studentProfile.gradYear]:[]))].sort((a,b)=>b-a)
  function patch(update:Partial<TaskAudience>){onChange({...value,...update,random:mode==="random" ? null : update.random ?? value.random})}
  function choose(id:string){setMode(id);onModeChange?.(id);setPool("everyone");onChange(taskAudienceSchema.parse({everyone:id==="everyone" || id==="random"}))}
  function checks(field:"groups"|"cohorts"|"years"|"roles"|"excludeGroups",options:{value:string|number;label:string;count:number}[],legend:string){return <fieldset><legend className="oc-task-field-label">{legend}</legend><div className="oc-audience-checks">{options.map(option=><label key={option.value}><input type="checkbox" checked={(value[field] as (string|number)[]).includes(option.value)} onChange={event=>patch({[field]:event.target.checked?[...value[field],option.value]:value[field].filter(item=>item!==option.value)})}/><span>{option.label}</span><small>{option.count}</small></label>)}{!options.length && <p className="text-sm text-muted-foreground">No {legend.toLowerCase()} are set on the current roster.</p>}</div></fieldset>}
  const yearControls=()=>checks("years",years.map(year=>({value:year,label:taskYearLabel(year),count:members.filter(member=>member.user.studentProfile?.gradYear===year).length})),"Class year")
  const groupControls=()=> <div className="oc-audience-dimensions">{checks("groups",groups.map(group=>({value:group,label:group,count:members.filter(member=>member.groups.includes(group)).length})),"Groups")}{checks("cohorts",cohorts.map(cohort=>({value:cohort,label:cohort,count:members.filter(member=>member.cohort===cohort).length})),"Cohorts")}</div>
  const roleControls=()=>checks("roles",Object.entries(taskRoleLabels).map(([role,label])=>({value:role,label,count:members.filter(member=>member.role===role).length})),"Roles")
  const excluded=workspace.tasks.filter(task=>value.excludeTasks.includes(task.id)).flatMap(task=>task.assignments.flatMap(assignment=>assignment.memberId?[assignment.memberId]:[]))
  let recipients:{member:TaskMember;groupLabel:string|null}[]=[],previewError=""
  try{recipients=resolveTaskRecipients(members,value,excluded)}catch(error){previewError=error instanceof Error?error.message:"Check your selection."}
  return <div className="oc-audience-builder">
    <div className="oc-audience-options" role="group" aria-label="Who should receive this?">{choices.map(choice=><button type="button" aria-pressed={mode===choice.id} key={choice.id} onClick={()=>choose(choice.id)}><choice.icon size={17} aria-hidden="true"/>{choice.label}</button>)}</div>
    {mode==="everyone" && <p className="text-sm text-muted-foreground">Everyone on the current club roster. Each person receives their own assignment.</p>}
    {mode==="members" && <TaskMemberList members={members} selected={value.members} onChange={ids=>patch({members:ids})}/>}
    {mode==="years" && yearControls()}{mode==="groups" && groupControls()}{mode==="roles" && roleControls()}
    {mode==="random" && <div className="space-y-4"><label className="oc-task-field-label">Audience<select className="oc-task-select" value={pool} onChange={event=>{setPool(event.target.value);onChange(taskAudienceSchema.parse({everyone:event.target.value==="everyone"}))}}><option value="everyone">Everyone</option><option value="years">By class year</option><option value="groups">By group / cohort</option><option value="roles">By role</option><option value="members">Choose members</option></select></label>{pool==="years" && yearControls()}{pool==="groups" && groupControls()}{pool==="roles" && roleControls()}{pool==="members" && <TaskMemberList members={members} selected={value.members} onChange={ids=>patch({members:ids})}/>}
      <div className="grid gap-3 sm:grid-cols-2"><label className="oc-task-field-label">Random assignment<select className="oc-task-select" value={randomKind} onChange={event=>{setRandomKind(event.target.value);patch({random:null})}}><option value="sample">Choose a number of members</option><option value="groups">Divide everyone into groups</option></select></label><label className="oc-task-field-label">{randomKind==="sample"?"Number of members":"Number of groups"}<Input type="number" min={randomKind==="sample"?1:2} max={randomKind==="sample"?1000:100} value={randomKind==="sample"?count:groupCount} onChange={event=>{randomKind==="sample"?setCount(Number(event.target.value)):setGroupCount(Number(event.target.value));patch({random:null})}}/></label></div>
      <label className="oc-task-field-label">Exclude members already assigned to<select className="oc-task-select" value={value.excludeTasks[0]??""} onChange={event=>patch({excludeTasks:event.target.value?[event.target.value]:[]})}><option value="">No task exclusion</option>{workspace.tasks.filter(task=>task.kind==="TASK"&&task.status!=="DRAFT").map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select></label>
      <Button type="button" variant="outline" onClick={()=>onChange({...value,random:{seed:crypto.randomUUID(),count:randomKind==="sample"?count:null,groups:randomKind==="groups"?groupCount:null}})}><Shuffle size={16}/>{value.random?"Regenerate":"Preview selection"}</Button>{value.random?.groups && !previewError && <p className="text-xs text-muted-foreground">{value.random.groups} groups · {Math.floor(recipients.length/value.random.groups)===Math.ceil(recipients.length/value.random.groups)?Math.floor(recipients.length/value.random.groups):`${Math.floor(recipients.length/value.random.groups)}–${Math.ceil(recipients.length/value.random.groups)}`} members per group</p>}{!value.random && <p className="text-xs text-muted-foreground">Preview a random selection before assigning. The selected people and groups will be saved.</p>}
    </div>}
    {mode==="advanced" && <div className="space-y-4"><label className="oc-task-field-label">Combine selected criteria<select className="oc-task-select" value={value.match} onChange={event=>patch({match:event.target.value as TaskAudience["match"]})}><option value="ALL">Match every selected category (AND)</option><option value="ANY">Match any selected category (OR)</option></select></label><p className="text-xs text-muted-foreground">Within a category, any checked option matches. Exclusions always take precedence.</p>{yearControls()}{groupControls()}{roleControls()}<TaskMemberList members={members} selected={value.members} onChange={ids=>patch({members:ids})} label="Include members"/>{checks("excludeGroups",groups.map(group=>({value:group,label:group,count:members.filter(member=>member.groups.includes(group)).length})),"Exclude groups")}<TaskMemberList members={members} selected={value.excludeMembers} onChange={ids=>patch({excludeMembers:ids})} label="Exclude members"/></div>}
    {previewError && <p role="alert" className="text-sm text-destructive">{previewError}</p>}
    <div data-random-ready={mode!=="random"||!!value.random}>{mode==="random"&&!value.random?<p className="oc-recipient-preview text-sm">{recipients.length} eligible members · preview a selection to continue.</p>:<TaskRecipientPreview recipients={recipients}/>}</div>
  </div>
}
