"use client"
import { useState } from "react"
import { ArrowLeft, ArrowRight, Plus, Trash2 } from "lucide-react"
import { taskAudienceSchema, taskInputSchema, type TaskAudience, type TaskInput } from "@/lib/tasks"
import { taskAudienceMode, taskLocalDate, taskDate, type TaskWorkspace, type ClubTask, type TaskRun, type TaskMember } from "@/lib/task-presentation"
import { saveTask, previewTaskAudience } from "@/lib/workspace-api"
import { TaskAudienceBuilder, TaskRecipientPreview } from "./task-audience-builder"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
export function TaskAssignmentBuilder({workspace,source,editing=false,kind:initialKind="TASK",projectId,run,busy,onSaved,onDirty}:{workspace:TaskWorkspace;source?:ClubTask;editing?:boolean;kind?:"TASK"|"PROJECT";projectId?:string;run:TaskRun;busy:boolean;onSaved:()=>void;onDirty:()=>void}) {
  const fixed=!!source && editing && source.status!=="DRAFT"
  const [title,setTitle]=useState(source?.title??""),[description,setDescription]=useState(source?.description??""),[kind,setKind]=useState(source?.kind??initialKind),[project,setProject]=useState(source?.projectId??projectId??""),[due,setDue]=useState(editing?taskLocalDate(source?.dueAt??null):""),[status,setStatus]=useState(source?.status==="DRAFT"?"OPEN":editing?source?.status??"OPEN":"OPEN"),[requirements,setRequirements]=useState(source?.requirements??["TEXT"]),[resources,setResources]=useState(taskInputSchema.shape.resources.safeParse(source?.resources).data??[])
  const [audience,setAudience]=useState<TaskAudience>(editing && source?taskAudienceSchema.parse(source.audience):taskAudienceSchema.parse({everyone:true})),[audienceMode,setAudienceMode]=useState(editing&&source?taskAudienceMode(taskAudienceSchema.parse(source.audience)):"everyone")
  const [stage,setStage]=useState("edit"),[recipients,setRecipients]=useState<{member:TaskMember;groupLabel:string|null}[]>([]),[checking,setChecking]=useState(false),[error,setError]=useState("")
  const projects=workspace.tasks.filter(task=>task.kind==="PROJECT" && task.status!=="DRAFT")
  function payload(saveStatus=status):TaskInput { return {clubId:workspace.clubId,id:editing?source?.id:undefined,revision:editing?source?.revision??0:0,title,description,kind:kind as "TASK"|"PROJECT",projectId:kind==="TASK"?project||null:null,dueAt:due?new Date(due).toISOString():null,status:saveStatus as "OPEN",requirements:kind==="TASK"?requirements as ("TEXT"|"LINK"|"FILE")[]:[],resources,audience,expectedRecipients:fixed?undefined:recipients.map(recipient=>recipient.member.id)} }
  async function review(){if(busy||checking)return;setError("");try{taskInputSchema.parse(payload());if(!fixed && audienceMode==="random"&&!audience.random)throw new Error("Preview a random selection first.");setChecking(true);const selected=fixed?source!.assignments.map(assignment=>({member:assignment.member,groupLabel:assignment.groupLabel})):await previewTaskAudience({clubId:workspace.clubId,audience});if(!selected.length && !fixed)throw new Error("Choose at least one recipient.");setRecipients(selected);setStage("review")}catch(error){setError(error instanceof Error?error.message:"Could not preview recipients.")}finally{setChecking(false)}}
  async function save(saveStatus=status){if(busy||checking)return;setError("");try{const input=taskInputSchema.parse(payload(saveStatus));if(await run(()=>saveTask(input)))onSaved()}catch(error){setError(error instanceof Error?error.message:"Check the assignment details.")}}
  return <form className="oc-assignment-builder space-y-5" data-saving={busy||checking} onChangeCapture={onDirty} onSubmit={event=>{event.preventDefault();stage==="review"?void save():void review()}}>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    {stage==="review"?<>
      <Button type="button" variant="ghost" onClick={()=>setStage("edit")}><ArrowLeft size={16}/>Edit details</Button>
      <section className="oc-builder-section"><p className="oc-eyebrow">Review & {fixed?"save":"assign"}</p><h3 className="oc-section-heading">{title}</h3><p className="whitespace-pre-wrap text-sm leading-6">{description || "No additional instructions."}</p><div className="oc-task-inline-meta"><span>{kind==="PROJECT"?"Project":"Task"}{project?` · ${projects.find(item=>item.id===project)?.title??"Related project"}`:""}</span><span>Due {due?taskDate(new Date(due)):"date not set"}</span><span>{requirements.map(value=>({TEXT:"Written response",LINK:"Link",FILE:"File"})[value as "TEXT"]).join(" + ") || (kind==="PROJECT"?"Progress tracked through related tasks":"Any submission format")}</span></div></section>
      <TaskRecipientPreview recipients={recipients}/>
      <p className="text-xs text-muted-foreground">{fixed?"Editing details preserves all current assignments and submitted work.":"These recipients will be saved when you assign. New roster changes will require you to review the list again."}</p>
      <Button disabled={busy||checking} className="w-full sm:w-auto">{busy?"Saving…":fixed?"Save changes":`Assign to ${recipients.length} members`}<ArrowRight size={16}/></Button>
    </>:<>
      <section className="oc-builder-section"><h3><span>1</span>Task</h3><label className="oc-task-field-label">Title<Input autoFocus required maxLength={200} placeholder={kind==="PROJECT"?"e.g. New member education":"e.g. Company research memo"} value={title} onChange={event=>setTitle(event.target.value)}/></label><label className="oc-task-field-label">Instructions<Textarea rows={3} maxLength={10000} placeholder="What should members do?" value={description} onChange={event=>setDescription(event.target.value)}/></label>
        <div className="grid gap-3 sm:grid-cols-2"><label className="oc-task-field-label">Organize as<select className="oc-task-select" value={kind} disabled={editing} onChange={event=>setKind(event.target.value)}><option value="TASK">Task</option><option value="PROJECT">Project / collection</option></select></label>{kind==="TASK" && <label className="oc-task-field-label">Project<select className="oc-task-select" value={project} onChange={event=>setProject(event.target.value)}><option value="">Standalone task</option>{projects.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}</div>
      </section>
      <section className="oc-builder-section"><h3><span>2</span>Who is this for?</h3>{fixed?<><p className="text-sm text-muted-foreground">{source!.assignments.length} assigned members. Add recipients from the task’s progress view.</p><TaskRecipientPreview recipients={source!.assignments.map(assignment=>({member:assignment.member,groupLabel:assignment.groupLabel}))}/></>:<TaskAudienceBuilder workspace={workspace} value={audience} mode={audienceMode} onModeChange={setAudienceMode} onChange={next=>{setAudience(next);onDirty()}}/>}</section>
      {kind==="TASK" && <section className="oc-builder-section"><h3><span>3</span>Submission</h3><p className="text-xs text-muted-foreground">Select the formats members must provide. Leave unchecked to accept any format.</p><div className="oc-audience-checks">{[{id:"TEXT",label:"Written response"},{id:"LINK",label:"Link"},{id:"FILE",label:"File"}].map(format=><label key={format.id}><input type="checkbox" checked={requirements.includes(format.id)} onChange={event=>setRequirements(event.target.checked?[...requirements,format.id]:requirements.filter(value=>value!==format.id))}/>{format.label}</label>)}</div></section>}
      <section className="oc-builder-section"><h3><span>{kind==="TASK"?4:3}</span>Timing</h3><label className="oc-task-field-label">Due date & time (your local time)<Input type="datetime-local" value={due} onChange={event=>setDue(event.target.value)}/></label>{fixed && <label className="oc-task-field-label">Availability<select className="oc-task-select" value={status} onChange={event=>setStatus(event.target.value)}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Closed</option></select></label>}</section>
      <details className="oc-task-resources"><summary>Resources{resources.length?` · ${resources.length}`:" (optional)"}</summary><div className="mt-3 space-y-3">{resources.map((resource,index)=><div className="flex flex-wrap items-center gap-2" key={index}><Input aria-label={`Resource ${index+1} label`} placeholder="Resource name" value={resource.label} maxLength={150} onChange={event=>setResources(resources.map((item,i)=>i===index?{...item,label:event.target.value}:item))}/><Input aria-label={`Resource ${index+1} URL`} type="url" placeholder="https://…" value={resource.url} onChange={event=>setResources(resources.map((item,i)=>i===index?{...item,url:event.target.value}:item))}/><Button type="button" variant="ghost" aria-label={`Remove resource ${index+1}`} onClick={()=>setResources(resources.filter((_,i)=>i!==index))}><Trash2 size={16}/></Button></div>)}<Button type="button" variant="ghost" disabled={resources.length>=20} onClick={()=>{setResources([...resources,{label:"",url:""}]);onDirty()}}><Plus size={15}/>Add resource</Button></div></details>
      <div className="oc-builder-actions">{!fixed && <Button type="button" variant="outline" disabled={busy||checking||!title.trim()||audienceMode==="random"&&!audience.random} onClick={()=>void save("DRAFT")}>Save draft</Button>}<Button disabled={busy||checking||!title.trim()||!fixed&&audienceMode==="random"&&!audience.random}>{checking?"Checking recipients…":fixed?"Review changes":"Review & assign"}<ArrowRight size={16}/></Button></div>
    </>}
  </form>
}
