import { roomPanelApprovalSchema, roomPanelChangeSchema } from "@/lib/interview-setup";
import { demoStore, demoMember } from "./store";
import { interviewCapabilities } from "@/lib/interview-access";
import { anonymousApplicantLabel } from "@/lib/anonymous-review";
function owner(clubId:string){const s=demoStore.get(),m=demoMember();if(s.perspective.role!=="leader"||m.clubId!==clubId||!interviewCapabilities(m).manageGrants)throw Error("Owner interview-access management required.");return{s,m};}
export function syncDemoBookingPanel(applicationId:string,roundId:string){
  demoStore.mutate(s=>{const app=s.applications.find(a=>a.id===applicationId)!;const b=s.roomBookings.find(b=>b.applicationId===applicationId&&b.roundId===roundId),room=s.interviewRooms.find(r=>r.id===b?.roomId);const allowed=room?.isOpen&&room.panelApprovedBy&&app.roundId===roundId&&app.status==="INTERVIEWING"&&!s.clubs.find(c=>c.id===app.clubId)!.rounds.find(r=>r.id===roundId)?.anonymousReview?room.approvedPanelMemberIds||[]:[];const eligible=s.memberships.filter(m=>allowed.includes(m.id)&&room!.panelMemberIds.includes(m.id)&&m.userId!==app.studentId&&interviewCapabilities(m).participate);for(const a of s.interviewFoundation.assignments.filter(a=>a.applicationId===applicationId&&a.roundId===roundId&&a.bookingManaged)){if(!eligible.some(m=>m.id===a.memberId))a.revokedAt=new Date().toISOString();}for(const m of eligible){const a=s.interviewFoundation.assignments.find(a=>a.applicationId===applicationId&&a.roundId===roundId&&a.memberId===m.id);if(a&&!a.bookingManaged)continue;if(a){a.revokedAt=null;a.bookingId=b!.id;}else s.interviewFoundation.assignments.push({applicationId,roundId,memberId:m.id,revokedAt:null,bookingManaged:true,bookingId:b!.id});}});
}
export function getInterviewAccessSetup(clubId:string){const{s}=owner(clubId);const members=s.memberships.filter(m=>m.clubId===clubId&&m.status==="ACTIVE").map(m=>{const p=s.students.find(p=>p.id===m.userId)!.profile;return{id:m.id,name:`${p.firstName} ${p.lastName}`,offices:m.interviewOffices,participate:interviewCapabilities(m).participate};});const applications=s.applications.filter(a=>a.clubId===clubId&&a.status!=="DRAFTING"&&a.studentId!==demoMember().userId).map(a=>{const r=s.clubs[0].rounds.find(r=>r.id===a.roundId)!,p=s.students.find(p=>p.id===a.studentId)!.profile;return{id:a.id,roundId:a.roundId,roundName:r.name,anonymous:r.anonymousReview,name:r.anonymousReview?anonymousApplicantLabel(a.id):`${p.firstName} ${p.lastName}`};});return{members,applications,rooms:s.interviewRooms.filter(r=>r.clubId===clubId).map(r=>({id:r.id,name:r.name,roundId:r.roundId,isOpen:r.isOpen,panelMemberIds:r.panelMemberIds,approvedPanelMemberIds:r.approvedPanelMemberIds||[],revision:r.panelApprovalRevision||0,bookings:s.roomBookings.filter(b=>b.roomId===r.id).map(b=>({id:b.id,applicationId:b.applicationId,unresolved:b.roundId!==r.roundId||!applications.some(a=>a.id===b.applicationId&&a.roundId===r.roundId&&!a.anonymous&&s.applications.find(app=>app.id===a.id)?.status==="INTERVIEWING")}))})),grants:s.interviewFoundation.assignments.filter(a=>s.applications.some(app=>app.id===a.applicationId&&app.clubId===clubId)).map(a=>({id:`${a.applicationId}-${a.memberId}`,applicationId:a.applicationId,roundId:a.roundId,memberId:a.memberId,revokedAt:a.revokedAt?new Date(a.revokedAt):null,bookingManaged:!!a.bookingManaged}))};}
export function approveInterviewRoomPanel(raw:unknown){const input=roomPanelApprovalSchema.parse(raw);const{s,m}=owner(input.clubId),r=s.interviewRooms.find(r=>r.id===input.roomId&&r.clubId===input.clubId);if(!r||!input.confirm||!r.isOpen||(r.panelApprovalRevision||0)!==input.revision||JSON.stringify([...r.panelMemberIds].sort())!==JSON.stringify([...input.panelMemberIds].sort())||s.clubs[0].rounds.find(round=>round.id===r.roundId)?.anonymousReview)throw Error("Room panel changed or unavailable.");if(r.panelMemberIds.some(id=>!s.memberships.some(m=>m.id===id&&interviewCapabilities(m).participate)))throw Error("Active reviewers required.");demoStore.mutate(s=>{const r=s.interviewRooms.find(r=>r.id===input.roomId)!;r.approvedPanelMemberIds=[...r.panelMemberIds];r.panelApprovedBy=m.userId;r.panelApprovalRevision=(r.panelApprovalRevision||0)+1;s.interviewFoundation.audit.push({action:"interview.room.panel.approve",actorId:m.userId,targetId:r.id});});let unresolved=0;for(const b of s.roomBookings.filter(b=>b.roomId===r.id)){const a=s.applications.find(a=>a.id===b.applicationId);if(b.roundId!==r.roundId||a?.roundId!==r.roundId||a.status!=="INTERVIEWING"){unresolved++;continue;}syncDemoBookingPanel(b.applicationId,b.roundId);}return{unresolved};}
export function changeInterviewRoomPanel(raw:unknown){const input=roomPanelChangeSchema.parse(raw);const{s,m}=owner(input.clubId),r=s.interviewRooms.find(r=>r.id===input.roomId&&r.clubId===input.clubId);if(!r||(r.panelApprovalRevision||0)!==input.revision||input.panelMemberIds.some(id=>!s.memberships.some(m=>m.id===id&&m.clubId===input.clubId&&m.status==="ACTIVE")))throw Error("Room panel changed.");demoStore.mutate(s=>{const r=s.interviewRooms.find(r=>r.id===input.roomId)!;r.panelMemberIds=[...new Set(input.panelMemberIds)];r.approvedPanelMemberIds=[];r.panelApprovedBy=null;r.panelApprovalRevision=(r.panelApprovalRevision||0)+1;s.interviewFoundation.audit.push({action:"interview.room.panel.change",actorId:m.userId,targetId:r.id});});for(const b of s.roomBookings.filter(b=>b.roomId===r.id))syncDemoBookingPanel(b.applicationId,b.roundId);}
