const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/lib/')?load(n.slice(2)+'.ts',mocks):require(n),m,m.exports);return m.exports;}
const id='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002',asset=`club-assets/${id}/${other}.webp`;
function setup(){let allowed=true,fail=false,query,stored=null,audits=0,reauth=0;const tx={$queryRaw:async()=>[],club:{findUniqueOrThrow:async()=>stored,create:async({data})=>(stored={id,...data}),update:async({data})=>(stored={...stored,...data})},school:{findUnique:async({where})=>({id:where.id,key:where.id==='school-uva'?'uva':'foreign',active:true})},auditLog:{create:async()=>audits++}};const db={$transaction:fn=>fn(tx),club:{findMany:async q=>{query=q;if(fail)throw Error('secret db');return[]},findUniqueOrThrow:async()=>stored},school:{findMany:async()=>[]}};const mocks={'@/utils/prisma':{prisma:db},'@/utils/platform-admin':{requirePlatformAdmin:async()=>{if(!allowed)throw Error('Denied');return{id:'admin'}}},'@/utils/admin-transaction':{authorizeAdminTransaction:async()=>{reauth++;if(!allowed)throw Error('Denied')}},'@/utils/club-asset-storage':{assertClubImageAssignment:async()=>{}},'@/utils/admin-page':{adminPageLoad:async(_p,fn)=>{try{return{value:await fn()}}catch{return{supportCode:'ADMIN-TEST'}}},logAdminFailure:()=> 'ADMIN-TEST'},'next/navigation':{redirect:()=>{throw Error('Redirect')}},'next/cache':{revalidateTag(){},revalidatePath(){}}};return{api:load('actions/admin-clubs.ts',mocks),setAllowed:v=>allowed=v,setFail:v=>fail=v,query:()=>query,stored:()=>stored,audits:()=>audits,reauth:()=>reauth,tx};}
const {profileDraft}=load('lib/club-marketing.ts');const input=()=>({slug:'new-club',schoolId:'school-uva',isDiscoverable:false,applicationOpen:false,applicationDeadline:null,profile:profileDraft({name:'New Club'}),reason:'Create authorized local test club.'});
test('Admin index guards identity, uses narrow projection and retains search with recruitment filter',async()=>{const h=setup();h.setAllowed(false);await assert.rejects(h.api.getAdminClubs(),/Denied/);h.setAllowed(true);await h.api.getAdminClubs({query:'finance',status:'RECRUITING'});const q=h.query();assert.equal(q.where.OR[0].name.contains,'finance');assert.ok(q.where.AND[0].OR);assert.equal(q.select.members,undefined);assert.equal(q.select.marketing,undefined);assert.equal(q.take,31)});
test('operational Admin loader failure returns support recovery without leaking exception',async()=>{const h=setup();h.setFail(true);const r=await h.api.loadAdminClubs();assert.deepEqual(r,{supportCode:'ADMIN-TEST'});assert.doesNotMatch(JSON.stringify(r),/secret/)});
test('create uses canonical Club, reauthorizes, audits and does not assign leadership',async()=>{const h=setup(),r=await h.api.saveAdminClub(input());assert.equal(r.id,id);assert.equal(h.reauth(),1);assert.equal(h.audits(),1);assert.equal(h.stored().schoolId,'school-uva');assert.equal(h.stored().campusKey,'uva');assert.equal(h.stored().members,undefined)});
test('edits require current version; platform metadata and school consistency fail closed',async()=>{const h=setup();await h.api.saveAdminClub(input());const current=(await h.api.getAdminClub(id)).value;assert.match((await h.api.saveAdminClub({...input(),id,version:'stale'})).error,/changed/);assert.match((await h.api.saveAdminClub({...input(),id,version:current.version,schoolId:'foreign'})).error,/School/);const r=await h.api.saveAdminClub({...input(),id,version:current.version,isDiscoverable:true});assert.equal(r.id,id);assert.equal(h.stored().isDiscoverable,true)});
test('new images cannot be assigned before canonical Club creation',async()=>{const h=setup();assert.match((await h.api.saveAdminClub({...input(),profile:{...input().profile,logoUrl:asset}})).error,/Create the club/);assert.equal(h.stored(),null)});
test('image assignment rejects foreign-club objects and missing objects; preserves historical fields',async()=>{const {assertClubImageAssignment}=load('utils/club-asset-storage.ts',{'server-only':{},'@/utils/prisma':{},'@supabase/supabase-js':{}});const tx={$queryRaw:async()=>[{name:'exists'}]};await assertClubImageAssignment(tx,id,{logoUrl:asset});await assert.rejects(assertClubImageAssignment(tx,other,{logoUrl:asset}),/ownership/);await assert.rejects(assertClubImageAssignment({$queryRaw:async()=>[]},id,{logoUrl:asset}),/unavailable/);await assertClubImageAssignment(tx,id,{logoUrl:'https://historical.example/image.png'},{logoUrl:'https://historical.example/image.png'});await assert.rejects(assertClubImageAssignment(tx,id,{logoUrl:'data:image/png;base64,YQ=='}),/Upload new/);await assertClubImageAssignment(tx,id,{logoUrl:null},{logoUrl:asset})});
test('structured sections retain order and visibility and reject unsafe links',()=>{const {clubProfileSchema}=load('lib/club-marketing.ts'),p=input().profile;p.marketing.sections=[{kind:'programs',title:'Visible',body:'Body',visible:true,cards:[]},{kind:'people',title:'Hidden',body:'',visible:false,cards:[]}];assert.deepEqual(clubProfileSchema.parse(p).marketing.sections.map(s=>s.title),['Visible','Hidden']);p.marketing.sections[0].cards=[{title:'Card',description:'',image:'',url:'javascript:alert(1)'}];assert.equal(clubProfileSchema.safeParse(p).success,false)});
test('launch fixtures use reusable data, omit unknown statistics/people/dates and preserve four identities',()=>{const profiles=require('../scripts/fixtures/spring-launch-club-profiles.json');assert.equal(new Set(profiles.map(p=>p.key)).size,4);for(const p of profiles){assert.ok(p.sections.length);assert.equal(p.acceptanceRate,undefined);assert.equal(p.memberCount,undefined);assert.equal(p.applicationDeadline,undefined);assert.ok(p.sections.every(s=>s.kind!=='people'));assert.doesNotMatch(fs.readFileSync('components/clubs/marketing-profile.tsx','utf8'),/slug\s*===/)}});
test('raster decoder rejects signatures without valid pixels and normalizes valid images',async()=>{const {prepareClubImage}=load('lib/club-image.ts');await assert.rejects(prepareClubImage(new Uint8Array([137,80,78,71,13,10,26,10]),'image/png'),/valid/);await assert.rejects(prepareClubImage(Buffer.from('<svg/>'),'image/png'));const sharp=require('sharp');const png=await sharp({create:{width:10,height:10,channels:3,background:'#fff'}}).png().toBuffer();const result=await prepareClubImage(png,'image/png');assert.equal(result.contentType,'image/webp');assert.equal((await sharp(result.bytes).metadata()).format,'webp')});
test('public profile uses canonical published Corkboard events and excludes suspended clubs while retaining unlisted direct links',async()=>{let query;const c={...input().profile,id,pipelineRounds:[],questions:[],events:[]};const api=load('actions/club-directory.ts',{'next/cache':{unstable_cache:fn=>fn},'@/utils/prisma':{prisma:{club:{findFirst:async q=>{query=q;return c}}}},'@/actions/campus-events':{getPublicCorkboard:async f=>{assert.equal(f.clubId,id);return{events:[{id:other,title:'Approved event',date:'2099-01-01T00:00:00Z',location:'Hall',description:'Approved'}]}}}});const result=await api.getPublicClub(id);assert.equal(query.where.isDiscoverable,undefined);assert.equal(query.where.suspendedAt,null);assert.equal(query.select.events,false);assert.deepEqual(result.club.publicEvents.map(e=>e.title),['Approved event'])});

test("duplicate canonical slug produces safe validation response without leaking database details",async()=>{const h=setup();const {Prisma}=require("@prisma/client");h.tx.club.create=async()=>{throw new Prisma.PrismaClientKnownRequestError("secret SQL text",{code:"P2002",clientVersion:"test"})};assert.deepEqual(await h.api.saveAdminClub(input()),{error:"That slug is already in use. Choose another slug."});assert.equal(h.audits(),0);});
