const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const {randomUUID}=require('node:crypto');
const nodes=n=>!n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];
const clubId=randomUUID(),q1=randomUUID(),q2=randomUUID(),r1=randomUUID();
function harness(file,api){const states=[],effects=[];let cursor=0;const mocks={react:{useState:initial=>{const i=cursor++;if(!(i in states))states[i]=typeof initial==='function'?initial():initial;return[states[i],v=>states[i]=typeof v==='function'?v(states[i]):v]},useRef:initial=>{const i=cursor++;if(!(i in states))states[i]={current:initial};return states[i]},useEffect:(fn,deps)=>{const i=cursor++;if(!states[i]||deps.some((v,j)=>v!==states[i][j])){states[i]=deps;effects.push(fn)}}},'@/actions/club-settings':api,'@/lib/workspace-read':api,'@/contexts/auth-context':{useAuth:()=>({activeClubId:clubId,user:{memberships:[{clubId,isOwner:true}]}})},'@/contexts/demo-context':{useDemoMode:()=>({ready:true,isDemoEnabled:false})},'next/link':{default:'Link'}};
 function load(file){const mod={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(n=>n in mocks?mocks[n]:n.endsWith('.css')?{}:n.startsWith('@/lib/')?load(n.slice(2)+'.ts'):n.startsWith('@/components/')?new Proxy({},{get:(_,key)=>key}):require(n),mod,mod.exports);return mod.exports;}
 const C=Object.values(load(file))[0];return{render(){cursor=0;return C({clubId})},async flush(){for(const fn of effects.splice(0))fn();for(let i=0;i<20;i++)await Promise.resolve()}};
}
const button=(tree,label)=>nodes(tree).find(n=>n.type==='Button'&&(JSON.stringify(n.props.children).includes(label)||n.props['aria-label']===label));
const environment=()=>{const before=global.window;global.window={confirm:()=>true,addEventListener(){},removeEventListener(){}};return()=>global.window=before};
test('real application editor loads shared configuration, reorders/marks questions and previews the exact saved shape',async()=>{
 const restore=environment();try{let payload;const questions=[q1,q2].map((id,i)=>({id,prompt:`Question ${i+1}`,type:'ESSAY',required:true,wordLimit:100,options:[]}));const h=harness('components/views/club-manager/application-builder-view.tsx',{getApplicationSettings:async()=>({name:'Club',questions,applicationOpen:true,applicationDeadline:null,applicationVersion:7}),saveApplicationSettings:async data=>{payload=data;return{version:8}}});h.render();await h.flush();let tree=h.render();button(tree,'Move question 2 up').props.onClick();tree=h.render();const checks=nodes(tree).filter(n=>n.type==='input'&&n.props.type==='checkbox');checks[1].props.onChange({target:{checked:false}});tree=h.render();button(tree,'Preview as student').props.onClick();tree=h.render();const preview=nodes(tree).find(n=>n.type==='Dialog');assert.equal(preview.props.open,true);const fields=nodes(preview).filter(n=>n.type==='QuestionField');assert.deepEqual(fields.map(f=>f.props.question.id),[q2,q1]);assert.equal(fields[0].props.question.required,false);button(tree,'Save application').props.onClick();await h.flush();assert.equal(payload.version,7);assert.deepEqual(payload.questions.map(q=>q.id),[q2,q1]);assert.equal(payload.questions[0].required,false);assert.equal(button(h.render(),'Save application').props.disabled,true);}finally{restore()}
});
test('new recruiting rounds and duration/instructions changes reach the versioned pipeline action',async()=>{
 const restore=environment();try{let payload;const h=harness('components/views/club-manager/interview-pipeline-builder-view.tsx',{getPipelineSettings:async()=>({pipelineVersion:3,pipelineRounds:[{id:r1,name:'Applied',type:'APPLICATION_REVIEW',configuration:{},anonymousReview:false,archivedAt:null}]}),savePipelineSettings:async data=>{payload=data;return{version:4}}});h.render();await h.flush();button(h.render(),'Add round').props.onClick();let tree=h.render();const selects=nodes(tree).filter(n=>n.type==='select');selects[1].props.onChange({target:{value:'INTERVIEW'}});tree=h.render();nodes(tree).find(n=>n.type==='Input'&&n.props.type==='number').props.onChange({target:{value:'45'}});const notes=nodes(h.render()).filter(n=>n.type==='Textarea');notes[1].props.onChange({target:{value:'Use the evaluation kit.'}});button(h.render(),'Save pipeline').props.onClick();await h.flush();assert.equal(payload.version,3);assert.equal(payload.rounds.length,2);assert.equal(payload.rounds[1].type,'INTERVIEW');assert.equal(payload.rounds[1].configuration.duration,45);assert.equal(payload.rounds[1].configuration.instructions,'Use the evaluation kit.');}finally{restore()}
});
