const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/lib/')?load(n.slice(2)+'.ts',mocks):require(n),m,m.exports);return m.exports;}
const clubId='00000000-0000-4000-8000-000000000001';
function setup(){let suspended=false,authorized=true;const logs=[],writes=[],member={id:'member',userId:'leader',clubId,status:'ACTIVE',isOwner:true,permissions:['club.settings','recruitment.manage']};
 const prisma={$queryRaw:async(strings,id)=>strings.join('').includes('"suspendedAt"')&&suspended&&id===clubId?[{id}]:[],user:{findUnique:async()=>({id:'leader',email:'leader@virginia.edu',disabledAt:null})},clubMember:{findUnique:async()=>member},club:{findUniqueOrThrow:async()=>({}),update:async({data})=>{writes.push(data);if('suspendedAt'in data)suspended=!!data.suspendedAt;return{id:clubId,...data}}},auditLog:{create:async({data})=>logs.push(data)}};prisma.$transaction=async fn=>fn(prisma);
 const mocks={'@/utils/club-asset-storage':{assertClubImageAssignment:async()=>{}},'./prisma':{prisma},'@/utils/prisma':{prisma},'@/utils/platform-view-as':{platformViewSession:async()=>null},'next/headers':{cookies:async()=>({has:()=>false,get:()=>undefined})},'./supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:'leader',email:'leader@virginia.edu',email_confirmed_at:'2026-01-01'}}})}})},'next/navigation':{redirect(){throw Error('Unauthenticated')}},'next/cache':{revalidatePath(){},revalidateTag(){}},'@/utils/platform-admin':{requirePlatformAdmin:async()=>{if(!authorized)throw Error('Fresh Admin authentication required.');return{id:'admin'}}},'@/actions/platform-admin':{},'@/actions/platform-organization-onboarding':{},'@/actions/club-onboarding':{},'@/utils/club-onboarding':{},'@/utils/email':{},'@/utils/invitation-delivery':{},'@/utils/invitation-background':{}};
 const auth=load('utils/auth.ts',mocks);mocks['@/utils/auth']=auth;
 return {prisma,member,logs,writes,auth,admin:load('actions/admin-workspace.ts',mocks),workspace:load('actions/club-workspace.ts',mocks),setSuspended:v=>suspended=v,setAuthorized:v=>authorized=v};}
test('active operations succeed; suspension denies actual server mutations and restoration retains membership/capabilities',async()=>{const h=setup(),input={clubId,name:'Test club',tagline:'Test',description:'Description'};await h.workspace.updateClubSettings(input);const before=structuredClone(h.member);await h.admin.setAdminClubSuspended(clubId,true,'Suspend the club for this focused regression.');await assert.rejects(h.workspace.updateClubSettings(input),/club is suspended/);await assert.rejects(h.auth.requireClubPermission(clubId,['recruitment.manage']),/club is suspended/);assert.deepEqual(h.member,before);await h.admin.setAdminClubSuspended(clubId,false,'Restore the club after the focused regression.');await h.workspace.updateClubSettings(input);assert.deepEqual(h.member,before);assert.deepEqual(h.logs.filter(l=>l.action==='platform.club.suspension').map(l=>({actor:l.actorId,suspended:l.details.suspended,result:l.details.result})),[{actor:'admin',suspended:true,result:'success'},{actor:'admin',suspended:false,result:'success'}]);});
test('historical read exception preserves capability checks, members and unrelated club authorization',async()=>{const h=setup();h.setSuspended(true);await h.auth.requireClubPermission(clubId,['recruitment.manage'],{allowSuspendedRead:true});await h.auth.requireClubPermission('other-club',['recruitment.manage']);h.member.isOwner=false;h.member.permissions=[];await assert.rejects(h.auth.requireClubPermission(clubId,['applications.review'],{allowSuspendedRead:true}),/permission/);assert.equal(h.member.status,'ACTIVE');});
test('both suspend and restore require elevated Admin authority before any writes',async()=>{const h=setup();h.setAuthorized(false);for(const value of[true,false])await assert.rejects(h.admin.setAdminClubSuspended(clubId,value,'Attempt without independent Admin elevation.'),/Fresh Admin/);assert.equal(h.writes.length,0);assert.equal(h.logs.length,0);});
test('canonical publication visibility hides suspended clubs and still requires current approved revision on restoration',()=>{const {eventIsPublished,publicMeetingVisibility}=load('lib/campus-events.ts');const e={isPublic:true,audience:'RECRUITMENT',revision:3,club:{suspendedAt:null},publication:{status:'PUBLISHED',approvedRevision:3}};assert.equal(eventIsPublished(e),true);e.club.suspendedAt=new Date();assert.equal(eventIsPublished(e),false);e.club.suspendedAt=null;e.revision=4;assert.equal(eventIsPublished(e),false);e.publication.approvedRevision=4;assert.equal(eventIsPublished(e),true);assert.deepEqual(publicMeetingVisibility.club,{is:{suspendedAt:null}});});
test('transaction suspension gate runs after obtaining the club lock and before mutation',async()=>{const {lockOperationalClub}=load('lib/club-suspension.ts'),queries=[];await assert.rejects(lockOperationalClub({$queryRaw:async strings=>{const sql=strings.join('');queries.push(sql);return sql.includes('"suspendedAt"')?[{id:clubId}]:[]}},clubId),/club is suspended/);assert.match(queries[0],/FOR UPDATE/);assert.match(queries[1],/FOR SHARE/);});
test('workspace is membership scoped and notice settings explicitly make no delivery claim',()=>{const page=fs.readFileSync('app/club/[clubId]/workspace/page.tsx','utf8');assert.match(page,/membership\?\.club\.suspendedAt/);assert.match(page,/This club is suspended/);assert.match(fs.readFileSync('components/admin/admin-settings.tsx','utf8'),/not currently displayed outside Admin or broadcast, emailed, or sent/);});
test('new submissions and drafts recheck suspension inside their transaction before changing stored answers',async()=>{const h=setup();h.setSuspended(true);const api=load('actions/applications.ts',{'@/utils/prisma':{prisma:h.prisma},'@/utils/auth':{requireAuth:async()=>({user:{id:'student'}})},'next/cache':{revalidatePath(){}}});for(const action of['submitApplication','saveApplicationDraft'])await assert.rejects(api[action]({clubId,answers:[]}),/club is suspended/);assert.equal(h.writes.length,0);});
test('legacy interview booking rechecks suspension after student ownership authorization',async()=>{const h=setup();h.setSuspended(true);h.prisma.application={findUnique:async()=>({id:clubId,studentId:'student',clubId,status:'INTERVIEWING'})};const api=load('actions/scheduling.ts',{'@/utils/prisma':{prisma:h.prisma},'@/utils/auth':{requireAuth:async()=>({user:{id:'student'}})},'next/cache':{revalidatePath(){}}});await assert.rejects(api.bookInterviewSlot({slotId:clubId,applicationId:clubId}),/club is suspended/);assert.equal(h.writes.length,0);});
test('applicant observations and interview display settings reject a suspension race inside the transaction',async()=>{const h=setup();h.setSuspended(true);const api=load('actions/applicant-intelligence.ts',{'@/utils/prisma':{prisma:h.prisma},'@/utils/auth':{requireClubPermission:async()=>({user:{id:'leader'},membership:h.member})}});for(const action of['saveApplicantObservation','deleteApplicantObservation'])await assert.rejects(api[action]({clubId,applicationId:clubId,...(action==='saveApplicantObservation'?{kind:'PRO',body:'A review'}:{id:clubId})}),/club is suspended/);await assert.rejects(api.saveApplicantDisplayConfiguration({clubId,roundId:clubId,version:0,config:load('lib/applicant-display.ts').defaultDisplayConfig}),/club is suspended/);});
