const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(file,mocks={}){const mod={exports:{}};new Function('require','module','exports','window','document',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/lib/')?load(n.replace('@/','')+'.ts',mocks):n.startsWith('@/')||n.endsWith('.css')?new Proxy({},{get:(_,k)=>String(k)}):require(n),mod,mod.exports,mocks.window,mocks.document);return mod.exports}
const nodes=n=>!n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];
const label=n=>typeof n==='string'||typeof n==='number'?String(n):Array.isArray(n)?n.map(label).join(''):n?.props?label(n.props.children):'';
const flush=()=>new Promise(r=>setImmediate(r));
const club={id:'club',name:'Research Club',source:'database',category:'Academic',color:'#142d4e',pitch:'Explore research',tags:[],logoText:'RC'};
function providerHarness(){
 const slots=[],effects=[],listeners={};let cursor=0,user={id:'student'},records=[{club,savedAt:'2026-10-03T12:00:00.000Z'}],resolve,reject,reads=0;
 const react={createContext:()=>({Provider:'Provider'}),useContext(){},useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]},useRef(initial){const i=cursor++;return slots[i]??=({current:initial})},useCallback(fn,deps){const i=cursor++,prev=slots[i];if(!prev||deps.some((v,j)=>v!==prev.deps[j]))slots[i]={fn,deps};return slots[i].fn},useEffect(fn,deps){const i=cursor++,prev=slots[i];if(!prev||deps.some((v,j)=>v!==prev[j])){slots[i]=deps;effects.push(fn)}}};
 const api={getCorkboard:async()=>{reads++;return{items:structuredClone(records)}},setCorkboardClub:({saved})=>new Promise((res,rej)=>{resolve=()=>{records=saved?[{club,savedAt:'2026-10-03T12:00:00.000Z'}]:[];res({saved,savedAt:saved?'2026-10-03T12:00:00.000Z':null})};reject=()=>rej(Error('Database unavailable'))})};
 const {CorkboardProvider}=load('contexts/corkboard-context.tsx',{react,'@/contexts/auth-context':{useAuth:()=>({user,loading:false})},'@/contexts/demo-context':{useDemoMode:()=>({isDemoEnabled:false,state:null})},'@/lib/workspace-api':api,window:{addEventListener:(k,fn)=>listeners[k]=fn,removeEventListener(){}},document:{visibilityState:'visible'}});
 return{render(){cursor=0;const value=CorkboardProvider({children:null}).props.value;while(effects.length)effects.shift()();return value},finish:()=>resolve(),fail:()=>reject(),focus:()=>listeners.focus(),logout:()=>user=null,reads:()=>reads};
}
test('optimistic Corkboard removal is immediate, blocks stale focus reads, and persists after reload',async()=>{const h=providerHarness();assert.equal(h.render().loading,true);await flush();let data=h.render();assert.equal(data.items.length,1);const pending=data.saveClub(club,false);data=h.render();assert.equal(data.items.length,0);assert.equal(data.pending.has(club.id),true);const reads=h.reads();await h.focus();assert.equal(h.reads(),reads);h.finish();await pending;await flush();data=h.render();assert.equal(data.items.length,0);assert.equal(data.pending.size,0);await data.refresh();assert.equal(h.render().items.length,0)});
test('failed removal restores only the affected item; account changes immediately conceal prior private saves',async()=>{const h=providerHarness();h.render();await flush();const pending=h.render().saveClub(club,false);assert.equal(h.render().items.length,0);h.fail();await assert.rejects(pending,/restored/);assert.equal(h.render().items.length,1);assert.match(h.render().error,/restored/);h.logout();const loggedOut=h.render();assert.equal(loggedOut.items.length,0);assert.equal(loggedOut.authenticated,false)});
test('saving is immediate, produces one shared saved state, and repeated clicks while pending cannot duplicate requests',async()=>{const h=providerHarness();h.render();await flush();let pending=h.render().saveClub(club,false);h.finish();await pending;await flush();const data=h.render();pending=data.saveClub(club,true);assert.equal(h.render().items.length,1);await h.render().saveClub(club,true);h.finish();await pending;await flush();assert.equal(h.render().items.length,1)});
test('Corkboard has loading, sign-in, empty, populated and retry states, reusing the existing card/profile',()=>{let state={items:[],loading:true,authenticated:true,error:'',refresh:async()=>{}};const mocks={'@/contexts/corkboard-context':{useCorkboard:()=>state},react:{useState:()=>[null,()=>{}]}};const {CorkboardView}=load('components/views/corkboard-view.tsx',mocks),actions=[];const render=()=>CorkboardView({onNavigate:v=>actions.push(v)});assert.ok(nodes(render()).some(n=>n.props?.['aria-label']==='Loading Corkboard'));state.loading=false;assert.match(label(render()),/A place for your next possibility/);nodes(render()).find(n=>n.type==='Button'&&label(n).includes('Find clubs')).props.onClick();assert.deepEqual(actions,['explore']);state.authenticated=false;assert.match(label(render()),/Sign in to save/);state.authenticated=true;state.items=[{club,savedAt:'2026-10-03'}];assert.ok(nodes(render()).some(n=>n.type==='DiscoveryCard'&&n.props.club.id===club.id));state.items=[];state.error='Unavailable';assert.match(label(render()),/Retry Corkboard/)});
test('desktop and mobile share contextual modes with Corkboard in Explore',()=>{
 const {personalItems,personalModes}=load('lib/product-navigation.ts');
 assert.deepEqual(personalModes.map(item=>item.label),['Explore','Apply','My Clubs']);
 assert.deepEqual(personalItems('explore').map(item=>item.label),['Discover','Categories','Corkboard']);
 assert.deepEqual(personalItems('apply').map(item=>item.label),['Applications','Status','Calendar']);
 assert.deepEqual(personalItems('clubs').map(item=>item.label),['Clubs','Meetings','Tasks']);
 const selections=[],{MobileNavigation}=load('components/shell/mobile-navigation.tsx',{'next/link':{default:'Link'}});
 const tree=MobileNavigation({items:personalItems('explore'),active:'corkboard',manager:false,onSelect:id=>selections.push(id),onLink(){},onMore(){}});
 const buttons=nodes(tree).filter(node=>node.type==='button');assert.deepEqual(buttons.map(label),['Home','Discover','Categories','Corkboard','More']);
 buttons.find(node=>label(node)==='Corkboard').props.onClick();assert.deepEqual(selections,['corkboard']);assert.equal(buttons.find(node=>label(node)==='Corkboard').props['aria-current'],'page');
});
test('student tutorials keep their eight-step indices/version contract while replacing the existing Corkboard placeholder',()=>{const {tutorialSteps,tutorialInput}=load('lib/tutorials.ts');assert.equal(tutorialSteps.student.length,8);assert.equal(tutorialSteps.student[1].view,'explore');assert.equal(tutorialSteps.student[6].view,'corkboard');assert.equal(tutorialSteps.student[6].anchor,'nav-corkboard');assert.equal(tutorialInput.parse({experience:'student',action:'progress',step:6}).step,6);assert.doesNotMatch(JSON.stringify(tutorialSteps.student),/when available|view":"discover"|Categories/)});
