const {test}=require('node:test'),assert=require('node:assert/strict');
const {harness}=require('./helpers/interview-sql-harness.cjs');
test('real migrated SQL plus live room/booking/grant/session actions enforce owner setup, rescheduling, cancellation and revocation',async t=>{
 const h=await harness();t.after(()=>h.db.close());const{id:unused,...ids}=h.ids,rooms=h.load('actions/interview-rooms.ts'),setup=h.load('actions/interview-access-setup.ts'),sessions=h.load('actions/interview-kits.ts'),grants=h.load('actions/organization-members.ts');
 const input={clubId:ids.club,roundId:ids.round,name:'Room one',location:'Room one',kind:'IN_PERSON',timezone:'UTC',dates:['2099-09-07'],start:'10:00',end:'11:00',duration:20,buffer:0,capacity:2,panelMemberIds:[ids.panelMember]};
 h.as(ids.scheduler);const one=await rooms.createInterviewRoom(input);h.as(ids.student);let slot=(await h.db.query('SELECT id FROM "InterviewSlot" WHERE "roomId"=$1 ORDER BY "startTime"',[one.id])).rows[0];const booking=await rooms.reserveInterview({applicationId:ids.app,slotId:slot.id});
 h.as(ids.panel);await assert.rejects(sessions.openInterviewSession(h.scope),/panel/);h.as(ids.scheduler);await assert.rejects(setup.approveInterviewRoomPanel({clubId:ids.club,roomId:one.id,revision:0,panelMemberIds:[ids.panelMember],confirm:true}),/owner/);
 h.as(ids.owner);await setup.approveInterviewRoomPanel({clubId:ids.club,roomId:one.id,revision:0,panelMemberIds:[ids.panelMember],confirm:true});h.as(ids.panel);assert.equal((await sessions.openInterviewSession(h.scope)).questions[0].id,ids.question);
 h.as(ids.scheduler);await setup.changeInterviewRoomPanel({clubId:ids.club,roomId:one.id,revision:1,panelMemberIds:[ids.schedulerMember]});await assert.rejects(sessions.openInterviewSession(h.scope));h.as(ids.panel);await assert.rejects(sessions.openInterviewSession(h.scope),/panel/);
 h.as(ids.owner);await assert.rejects(setup.approveInterviewRoomPanel({clubId:ids.club,roomId:one.id,revision:1,panelMemberIds:[ids.panelMember],confirm:true}),/changed/);await assert.rejects(setup.approveInterviewRoomPanel({clubId:ids.club,roomId:one.id,revision:2,panelMemberIds:[ids.schedulerMember],confirm:true}),/reviewer/);
 const two=await rooms.createInterviewRoom({...input,name:'Room two',location:'Room two',dates:['2099-09-08'],panelMemberIds:[ids.peerMember]});await setup.approveInterviewRoomPanel({clubId:ids.club,roomId:two.id,revision:0,panelMemberIds:[ids.peerMember],confirm:true});slot=(await h.db.query('SELECT id FROM "InterviewSlot" WHERE "roomId"=$1 ORDER BY "startTime"',[two.id])).rows[0];
 h.as(ids.student);const replacement=await rooms.reserveInterview({applicationId:ids.app,slotId:slot.id});assert.notEqual(replacement.id,booking.id);h.as(ids.peer);await sessions.openInterviewSession(h.scope);h.as(ids.panel);await assert.rejects(sessions.openInterviewSession(h.scope));
 h.as(ids.student);await rooms.cancelRoomBooking(replacement.id);h.as(ids.peer);await assert.rejects(sessions.openInterviewSession(h.scope),/panel/);h.as(ids.student);await rooms.reserveInterview({applicationId:ids.app,slotId:slot.id});h.as(ids.peer);await sessions.openInterviewSession(h.scope);
 h.as(ids.owner);await grants.setInterviewPanelAssignment({...h.scope,memberId:ids.peerMember,assigned:false});h.as(ids.student);await rooms.reserveInterview({applicationId:ids.app,slotId:slot.id});h.as(ids.peer);await assert.rejects(sessions.openInterviewSession(h.scope),/panel/);
 h.as(ids.owner);await grants.setInterviewPanelAssignment({...h.scope,memberId:ids.peerMember,assigned:true});await h.db.query('UPDATE "User" SET "disabledAt"=NOW() WHERE id=$1',[ids.peer]);h.as(ids.peer);await assert.rejects(sessions.openInterviewSession(h.scope),/unavailable/);assert.equal((await h.db.query('SELECT "panelApprovedBy" FROM "InterviewRoom" WHERE id=$1',[two.id])).rows[0].panelApprovedBy,null);
 const audits=(await h.db.query('SELECT action FROM "AuditLog"')).rows.map(r=>r.action);assert.ok(audits.includes('interview.room.panel.approve'));assert.ok(audits.includes('interview.panel.booking.grant'));assert.ok(audits.includes('interview.booking.cancel'));
});
test('legacy booking review stays unresolved and panel edits cannot introduce scheduling conflicts',async t=>{
 const h=await harness();t.after(()=>h.db.close());const i=h.ids,rooms=h.load('actions/interview-rooms.ts'),setup=h.load('actions/interview-access-setup.ts');
 const input={clubId:i.club,roundId:i.round,name:'Legacy room',location:'Legacy room',kind:'IN_PERSON',timezone:'UTC',dates:['2099-09-07'],start:'10:00',end:'11:00',duration:20,buffer:0,capacity:2,panelMemberIds:[i.panelMember]};
 const room=await rooms.createInterviewRoom(input),other=await rooms.createInterviewRoom({...input,name:'Other room',location:'Other room',panelMemberIds:[i.peerMember]});
 await assert.rejects(setup.changeInterviewRoomPanel({clubId:i.club,roomId:other.id,revision:0,panelMemberIds:[i.panelMember]}),/overlapping/);
 const slot=(await h.db.query('SELECT id FROM "InterviewSlot" WHERE "roomId"=$1 ORDER BY "startTime"',[room.id])).rows[0];
 await h.db.query('INSERT INTO "InterviewBooking"(id,"applicationId","slotId","roundId") VALUES ($1,$2,$3,NULL)',[crypto.randomUUID(),i.app,slot.id]);
 const moved=crypto.randomUUID();await h.db.query('INSERT INTO "PipelineRound"(id,"clubId",name,"order") VALUES ($1,$2,\'Later round\',2)',[moved,i.club]);await h.db.query('UPDATE "Application" SET "roundId"=$1 WHERE id=$2',[moved,i.app]);
 const result=await setup.approveInterviewRoomPanel({clubId:i.club,roomId:room.id,revision:0,panelMemberIds:[i.panelMember],confirm:true});assert.equal(result.unresolved,1);assert.equal((await h.db.query('SELECT id FROM "InterviewPanelAssignment"')).rows.length,0);
 await rooms.setInterviewRoomOpen({roomId:room.id,open:false});const closed=(await h.db.query('SELECT "approvedPanelMemberIds","panelApprovedBy" FROM "InterviewRoom" WHERE id=$1',[room.id])).rows[0];assert.deepEqual(closed.approvedPanelMemberIds,[]);assert.equal(closed.panelApprovedBy,null);
});
