const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const flush=()=>new Promise(r=>setImmediate(r));
const nodes=n=>!n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];
const text=n=>typeof n==='string'||typeof n==='number'?String(n):Array.isArray(n)?n.map(text).join(''):n?.props?text(n.props.children):'';
test('leadership UI renders only closing DTO, supports empty/retry, and clears opened reviews on revoked access',async()=>{
 const slots=[],effects=[],cleanups=[],polls=new Map();let index=0,sequence=0,deny=false,empty=true;
 const row={id:'record',applicationId:'app',roundId:'past-round',interviewerId:'reviewer',roundName:'Past round',applicantName:'Synthetic Applicant'};
 const react={useState(v){const i=index++;if(!(i in slots))slots[i]=v;return[slots[i],value=>slots[i]=typeof value==='function'?value(slots[i]):value]},useEffect(fn,deps){const i=index++;if(!slots[i]||deps.some((v,j)=>v!==slots[i][j])){slots[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=fn()})}}};
 const api={getSubmittedInterviewReviews:async()=>{if(deny)throw Error('Revoked');return empty?[]:[row]},getSubmittedInterviewReview:async scope=>{assert.equal(scope.roundId,'past-round');if(deny)throw Error('Revoked');return{id:'record',submittedAt:'2026-10-01T12:00:00Z',applicantQuestions:'What comes next?',additionalNotes:'Final review',score:8.25,readOnly:true}}};
 const mod={exports:{}},code=ts.transpileModule(fs.readFileSync('components/interview-submitted-reviews.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
 new Function('require','module','exports','setInterval','clearInterval','window','document',code)(n=>n==='react'?react:n==='@/lib/workspace-api'?api:n==='@/components/ui/button'?{Button:'Button'}:require(n),mod,mod.exports,fn=>{polls.set(++sequence,fn);return sequence},id=>polls.delete(id),{addEventListener(){},removeEventListener(){}},{hidden:false});
 const render=()=>{index=0;const t=mod.exports.InterviewSubmittedReviews({clubId:'club'});while(effects.length)effects.shift()();return t},click=(t,label)=>nodes(t).find(n=>n.type==='Button'&&text(n)===label).props.onClick();
 render();await flush();let t=render();assert.match(text(t),/No submitted reviews available/);empty=false;click(t,'Refresh reviews');render();await flush();t=render();click(t,'Synthetic Applicant · Past round · Open review');render();await flush();t=render();assert.match(text(t),/8.25 \/ 10/);assert.match(text(t),/What comes next/);assert.equal(nodes(t).some(n=>['input','textarea','Slider'].includes(n.type)),false);assert.doesNotMatch(text(t),/unlock|resubmit|Save and finish/);
 deny=true;[...polls.values()].forEach(fn=>fn());await flush();t=render();assert.doesNotMatch(text(t),/Synthetic Applicant|Final review|What comes next/);assert.match(text(t),/access/);deny=false;click(t,'Refresh reviews');render();await flush();assert.match(text(render()),/Synthetic Applicant/);
});
