const {test}=require('node:test'),assert=require('node:assert/strict');const {harness,id}=require('./helpers/interview-harness.cjs');
test('scholar validation preserves null and enforces exclusive Not Applicable, duplicates and Other',()=>{const h=harness(),{scholarStatusSchema:s}=h.load('lib/scholar-status.ts');assert.equal(s.parse(null),null);assert.deepEqual(s.parse({selections:['JEFFERSON','ECHOLS'],other:'stale'}),{selections:['JEFFERSON','ECHOLS'],other:''});for(const selections of [[],['OTHER'],['NOT_APPLICABLE','ECHOLS'],['RODMAN','RODMAN']])assert.equal(s.safeParse({selections}).success,false);assert.equal(s.parse({selections:['OTHER','WALENTAS'],other:' Named scholarship '}).other,'Named scholarship');});
test('only owner can attest offices or grant panel; titles and admin capabilities never imply offices',async()=>{const h=harness(),api=h.load('actions/organization-members.ts');h.as(11);h.members[1].permissions.push('members.manage','leaders.manage','interviews.manage');h.members[1].title='Vice President';await assert.rejects(api.setMemberInterviewOffices({clubId:id(1),memberId:id(21),offices:['VICE_PRESIDENT']}),/owner/);h.as(10);await api.setMemberInterviewOffices({clubId:id(1),memberId:id(21),offices:['VICE_PRESIDENT']});assert.deepEqual(h.members[1].interviewOffices,['VICE_PRESIDENT']);assert.equal(h.state.audits.at(-1).action,'interview.offices.change');await assert.rejects(api.setMemberInterviewOffices({clubId:id(1),memberId:id(88),offices:['BOARD']}),/member/);await api.setInterviewPanelAssignment({...h.scope,memberId:id(21),assigned:false});assert.ok(h.assignments[1].revokedAt);h.as(11);await assert.rejects(h.load('actions/interview-kits.ts').openInterviewSession(h.scope),/panel/);});
test('pinned resume bytes and hash remain stable across replacement uploads; unrelated round denied',async()=>{const h=harness(),api=h.load('actions/interview-resumes.ts');process.env.SUPABASE_SECRET_KEY='test-only';process.env.NEXT_PUBLIC_SUPABASE_URL='https://fixture.invalid';const one=await api.pinInterviewResume(h.scope);h.tx.studentProfile.findUnique=async()=>({resumeUrl:`${id(99)}/replacement.pdf`});const two=await api.pinInterviewResume(h.scope);assert.equal(one.id,two.id);assert.equal(one.contentHash,two.contentHash);assert.equal(h.state.documents.length,1);await assert.rejects(api.pinInterviewResume({...h.scope,roundId:id(8)}),/unavailable/);});
test('panel annotations allow independent concurrent comments, enforce author/moderator revisions and conceal deleted history',async()=>{
 const h=harness(),api=h.load('actions/interview-resumes.ts');h.state.documents.push({id:id(300),applicationId:id(2),roundId:id(3)});const base={...h.scope,documentId:id(300)},content={kind:'GENERAL_NOTE',anchor:null,comment:'Panel comment'};
 h.as(11);await Promise.all([api.saveInterviewResumeAnnotation({...base,id:id(401),content}),api.saveInterviewResumeAnnotation({...base,id:id(402),content:{...content,comment:'Independent'}})]);assert.equal(h.state.annotations.length,2);await api.saveInterviewResumeAnnotation({...base,id:id(401),content});assert.equal(h.state.annotations.length,2);
 const races=await Promise.allSettled([api.saveInterviewResumeAnnotation({...base,id:id(401),revision:0,content:{...content,comment:'Edit A'}}),api.saveInterviewResumeAnnotation({...base,id:id(401),revision:0,content:{...content,comment:'Edit B'}})]);assert.equal(races.filter(r=>r.status==='fulfilled').length,1);
 h.as(12);await assert.rejects(api.saveInterviewResumeAnnotation({...base,id:id(401),revision:1,content}),/unavailable/);await assert.rejects(api.getInterviewAnnotationHistory({...base,id:id(401)}),/unavailable/);
 h.members[2].interviewOffices=['BOARD'];h.assignments[2].revokedAt=new Date();await assert.rejects(api.getInterviewResumeAnnotations(base),/panel/);
 h.as(10);await api.deleteInterviewResumeAnnotation({...base,id:id(401),revision:1});assert.equal((await api.getInterviewResumeAnnotations(base)).annotations.length,1);assert.equal((await api.getInterviewAnnotationHistory({...base,id:id(401)})).length,2);assert.doesNotMatch(JSON.stringify(h.state.audits),/Panel comment|Edit A/);
 h.as(11);h.assignments[1].revokedAt=new Date();await assert.rejects(api.getInterviewAnnotationHistory({...base,id:id(401)}),/panel/);await assert.rejects(api.getInterviewResumeAnnotations(base),/panel/);
});
test('annotation validation requires version-scoped document, page, quote and valid offsets',async()=>{const h=harness(),api=h.load('actions/interview-resumes.ts');h.state.documents.push({id:id(300),applicationId:id(2),roundId:id(3),content:new Uint8Array(require('node:fs').readFileSync('public/demo/sample-resume.pdf'))});const base={...h.scope,documentId:id(300),id:id(401)};await assert.rejects(api.saveInterviewResumeAnnotation({...base,content:{kind:'TEXT_HIGHLIGHT',anchor:null,comment:'Hi'}}));await api.saveInterviewResumeAnnotation({...base,content:{kind:'TEXT_HIGHLIGHT',anchor:{page:1,start:0,end:8,quote:'OutClass'},comment:'Anchored'}});assert.equal(h.state.annotations[0].anchor.page,1);await assert.rejects(api.getInterviewResumeAnnotations({...base,documentId:id(301)}),/unavailable/);});
