const { test } = require('node:test')
const assert = require('node:assert/strict')
const { harness } = require('./helpers/demo-harness.cjs')

test('next applicant keeps name/ID order, skips completed/unassigned/other rounds and wraps unfinished earlier rows', () => {
  const { nextInterviewApplicant, interviewQueue } = harness().load('lib/interview-queue.ts')
  const candidate = (id, name, extra = {}) => ({ id, name, roundId: 'r', assignedRoundIds: ['r'], completedRoundIds: [], ...extra })
  const rows = [candidate('c','Casey'), candidate('a2','Alex'), candidate('b','Blair',{completedRoundIds:['r']}), candidate('a1','Alex'), candidate('x','Cameron',{assignedRoundIds:[]}), candidate('y','Cameron',{roundId:'other'}), candidate('z','Cameron',{assignedRoundIds:['other']})]
  assert.deepEqual(interviewQueue(rows,'r').map(a=>a.id), ['a1','a2','b','c'])
  assert.equal(nextInterviewApplicant(rows,'r','a2').id, 'c')
  assert.equal(nextInterviewApplicant(rows,'r','c').id, 'a1')
  assert.equal(nextInterviewApplicant(rows,'r','revoked-current').id, 'a1')
  assert.equal(nextInterviewApplicant(rows.map(a=>({...a,completedRoundIds:['r']})),'r','c'), null)
  assert.equal(nextInterviewApplicant([], 'r', 'c'), null)
})

test('fresh Demo queue honors current assignments, independent completion, anonymity, revocation and membership denial with zero server calls', async () => {
  const h=harness(),store=h.load('lib/demo/store.ts'),api=h.load('lib/workspace-api.ts'),{nextInterviewApplicant}=h.load('lib/interview-queue.ts')
  store.demoStore.start();store.demoStore.mutate(s=>{s.perspective.role='leader'})
  const s=store.demoStore.get(), club=s.clubs[0], round=club.rounds.find(r=>r.name==='Interview'), member=store.demoMember()
  const current=(await api.getInterviewWorkspace(club.id)).applications.find(a=>a.roundId===round.id&&!a.completedRoundIds.includes(round.id))
  const scope={clubId:club.id,roundId:round.id,applicationId:current.id}
  const session=await api.openInterviewSession(scope)
  const saved=await api.saveInterviewSession({...scope,revision:session.revision,draft:{...session.draft,postInterview:true,score:8.5},complete:true})
  const fresh=await api.getInterviewWorkspace(club.id)
  assert.ok(fresh.applications.find(a=>a.id===current.id).completedRoundIds.includes(round.id))
  const next=nextInterviewApplicant(fresh.applications,round.id,current.id);assert.ok(next)
  const opened=await api.openInterviewSession({...scope,applicationId:next.id})
  assert.equal(opened.draft.score,null);assert.equal(opened.draft.postInterview,undefined);assert.deepEqual(opened.draft.questionNotes,[])
  assert.equal((await api.openInterviewSession(scope)).id,saved.session.id)
  store.demoStore.mutate(s=>{s.interviewFoundation.assignments.find(a=>a.applicationId===next.id&&a.memberId===member.id&&a.roundId===round.id).revokedAt=new Date().toISOString()})
  assert.equal((await api.getInterviewWorkspace(club.id)).applications.some(a=>a.id===next.id&&a.assignedRoundIds.includes(round.id)),false)
  await assert.rejects(api.openInterviewSession({...scope,applicationId:next.id}), /panel/)
  store.demoStore.mutate(s=>{s.clubs[0].rounds.find(r=>r.id===round.id).anonymousReview=true})
  assert.equal((await api.getInterviewWorkspace(club.id)).rounds.some(r=>r.id===round.id),false)
  store.demoStore.mutate(s=>{s.memberships.find(m=>m.id===member.id).status='LEFT'})
  await assert.rejects(api.getInterviewWorkspace(club.id), /access/)
  assert.equal(h.calls(),0);store.demoStore.stop()
})
