const {test}=require('node:test'),assert=require('node:assert/strict');
const {harness}=require('./helpers/demo-harness.cjs');
test('owner setup uses isolated adapters, persists office/panel approvals and grants entry without live writes',async()=>{
const h=harness(),{demoStore,demoMember}=h.load('lib/demo/store.ts'),api=h.load('lib/workspace-api.ts');demoStore.start();const s=demoStore.get(),club=s.clubs[0],member=demoMember(),round=club.rounds.find(r=>!r.anonymousReview),app=s.applications.find(a=>a.clubId===club.id&&a.studentId!==member.userId);
demoStore.mutate(s=>{s.perspective={role:'leader',clubId:club.id};s.interviewFoundation.assignments=[];const a=s.applications.find(a=>a.id===app.id);a.roundId=round.id;a.status='INTERVIEWING';});
const room=await api.createInterviewRoom({clubId:club.id,roundId:round.id,name:'Demo setup',location:'Test',kind:'IN_PERSON',timezone:'UTC',dates:['2099-09-07'],start:'10:00',end:'11:00',duration:20,buffer:0,capacity:2,panelMemberIds:[member.id]});
const slot=demoStore.get().interviewRooms.find(r=>r.id===room.id).slots[0];demoStore.mutate(s=>s.roomBookings.push({id:crypto.randomUUID(),applicationId:app.id,roundId:round.id,roomId:room.id,slotId:slot.id,startTime:slot.startTime,endTime:slot.endTime,candidate:'Fixture',location:'Test',kind:'IN_PERSON'}));
const scope={clubId:club.id,roundId:round.id,applicationId:app.id};await assert.rejects(api.openInterviewSession(scope));await api.setMemberInterviewOffices({clubId:club.id,memberId:member.id,offices:['VICE_PRESIDENT']});assert.deepEqual((await api.getInterviewAccessSetup(club.id)).members.find(m=>m.id===member.id).offices,['VICE_PRESIDENT']);
await api.approveInterviewRoomPanel({clubId:club.id,roomId:room.id,revision:0,panelMemberIds:[member.id],confirm:true});assert.deepEqual((await api.getInterviewAccessSetup(club.id)).rooms.find(r=>r.id===room.id).approvedPanelMemberIds,[member.id]);await api.openInterviewSession(scope);
await api.setInterviewRoomOpen({roomId:room.id,open:false});await assert.rejects(api.openInterviewSession(scope));await api.setInterviewRoomOpen({roomId:room.id,open:true});await assert.rejects(api.openInterviewSession(scope));await api.approveInterviewRoomPanel({clubId:club.id,roomId:room.id,revision:2,panelMemberIds:[member.id],confirm:true});await api.openInterviewSession(scope);
await api.changeInterviewRoomPanel({clubId:club.id,roomId:room.id,revision:3,panelMemberIds:[]});assert.deepEqual((await api.getInterviewAccessSetup(club.id)).rooms.find(r=>r.id===room.id).panelMemberIds,[]);await assert.rejects(api.openInterviewSession(scope));assert.equal(h.calls(),0);demoStore.stop();
});
