const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const nodes=n=>!n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];
function harness(api){const state=[];let cursor=0;const mod={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('components/invitation-email-controls.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText)(name=>name==='react'?{useState:initial=>{const i=cursor++;if(!(i in state))state[i]=initial;return[state[i],v=>state[i]=v];},useRef:initial=>{const i=cursor++;if(!(i in state))state[i]={current:initial};return state[i];}}:name==='@/actions/invitation-emails'?api:name==='@/components/ui/button'?{Button:'Button'}:require(name),mod,mod.exports);return{render(props={clubId:'club',importId:'import'}){cursor=0;return mod.exports.InvitationEmailControls(props);},async flush(){for(let i=0;i<20;i++)await Promise.resolve();}};}
test('review step never sends on render; explicit double click queues once and drains bounded batches',async()=>{
 let queued=0,processed=0,resolve;const h=harness({sendRosterInvitations:()=>{queued++;return new Promise(done=>resolve=done);},deliverOrganizationInvitations:async()=>({sent:++processed===1?5:2,failed:0,cancelled:0,uncertain:0,remaining:processed===1?2:0})});
 const tree=h.render();assert.equal(queued,0);const button=nodes(tree).find(n=>n.type==='Button');assert.equal(button.props.children,'Send invitations');button.props.onClick();button.props.onClick();assert.equal(queued,1);assert.equal(nodes(h.render()).find(n=>n.type==='Button').props.disabled,true);
 resolve({queued:7,reused:0,skipped:0});await h.flush();assert.equal(processed,2);assert.ok(JSON.stringify(h.render()).includes('7 emails sent'));
});
test('configuration/network errors preserve retry and standalone control drains without re-enqueue',async()=>{
 let calls=0;const h=harness({sendRosterInvitations:async()=>{throw Error('SMTP not configured');},deliverOrganizationInvitations:async()=>{calls++;return{sent:0,failed:1,cancelled:0,uncertain:1,remaining:0};}});nodes(h.render()).find(n=>n.type==='Button').props.onClick();await h.flush();assert.ok(JSON.stringify(h.render()).includes('SMTP not configured'));assert.equal(calls,0);assert.equal(nodes(h.render()).find(n=>n.type==='Button').props.disabled,false);
 const control=h.render({clubId:'club'});assert.equal(nodes(control).find(n=>n.type==='Button').props.children,'Send queued invitations');nodes(control).find(n=>n.type==='Button').props.onClick();await h.flush();assert.equal(calls,1);assert.ok(JSON.stringify(h.render({clubId:'club'})).includes('need delivery review'));
});
