const {test}=require('node:test'), assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript')
function load(file,mocks={}){const mod={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/lib/')?load(n.replace('@/','')+'.ts'):require(n),mod,mod.exports);return mod.exports}
const clubId='00000000-0000-4000-8000-000000000001',meetingId='00000000-0000-4000-8000-000000000002'
function setup(){let userId='leader',studentMember=false,revoked=false,rows=[],tokens=[],tail=Promise.resolve();const meeting={id:meetingId,clubId,title:'Interest meeting',date:new Date(),endDate:null,audience:'RECRUITMENT',isPublic:true,revision:0};let lastQuery
 const tx={$queryRaw:async()=>[],meeting:{findFirst:async({where})=>where.id===meetingId&&(!where.clubId||where.clubId===clubId)?meeting:null,findUnique:async()=>meeting,findMany:async args=>{lastQuery=args;return[]},updateMany:async({where,data})=>{if(where.revision!==meeting.revision)return{count:0};Object.assign(meeting,{...data,revision:meeting.revision+1});return{count:1}},create:async({data})=>Object.assign(meeting,data),count:async()=>3},clubMember:{findUnique:async({where})=>{const id=where.userId_clubId.userId;return id==='leader'&&!revoked?{isOwner:true}:studentMember?{permissions:[]}:null}},user:{findUnique:async()=>({disabledAt:null})},meetingCheckInToken:{findFirst:async({where})=>tokens.find(t=>t.meetingId===where.meetingId&&t.tokenHash===where.tokenHash&&t.expiresAt>where.expiresAt.gt)||null,create:async({data})=>{tokens.push(data);return data},deleteMany:async({where})=>{tokens=tokens.filter(t=>t.meetingId!==where.meetingId||(where.expiresAt&&t.expiresAt>where.expiresAt.lte))}},eventAttendance:{findUnique:async({where})=>rows.find(r=>r.eventId===where.eventId_studentId.eventId&&r.studentId===where.eventId_studentId.studentId)||null,create:async({data})=>{const row={...data,id:'attendance-'+rows.length,checkedInAt:new Date()};rows.push(row);return row},findMany:async()=>[],count:async()=>2},auditLog:{create:async()=>({})}}
 const prisma={...tx,$transaction:fn=>{const run=tail.then(()=>fn(tx));tail=run.catch(()=>{});return run}}
 const api=load('actions/meetings.ts',{'@/utils/prisma':{prisma},'@/utils/auth':{requireAuth:async()=>({user:{id:userId}}),requireClubPermission:async(id,permissions)=>{assert.equal(id,clubId);if(userId!=='leader'||revoked)throw Error('Denied');return{user:{id:userId},membership:{isOwner:true}}}},'next/cache':{revalidatePath:()=>{}}})
 return{api,meeting,rows:()=>rows,tokens:()=>tokens,student:()=>{userId='student'},member:()=>{studentMember=true},revoke:()=>{revoked=true},expire:()=>tokens.forEach(t=>t.expiresAt=new Date(0)),lastQuery:()=>lastQuery}
}
test('meetings are scoped by audience and membership in the server query',async()=>{const h=setup();h.student();await h.api.listMeetings();assert.deepEqual(h.lastQuery().where.OR,[{audience:'RECRUITMENT',isPublic:true},{club:{members:{some:{userId:'student'}}}}]);assert.equal(h.lastQuery().select.checkInTokens,undefined)})
test('short-lived QR tokens are hashed and check-in is idempotent even with concurrent scans',async()=>{const h=setup(),issued=await h.api.issueMeetingCheckIn(clubId,meetingId);assert.match(issued.token,/^[a-f0-9]{64}$/);assert.notEqual(h.tokens()[0].tokenHash,issued.token);assert.ok(new Date(issued.expiresAt).getTime()-Date.now()<=90000);h.student();const results=await Promise.all([h.api.checkInMeeting(meetingId,issued.token),h.api.checkInMeeting(meetingId,issued.token)]);assert.equal(h.rows().length,1);assert.deepEqual(results.map(r=>r.status),['checked-in','already-checked-in']);assert.equal(results[0].checkedInAt,results[1].checkedInAt)})
test('member meetings reject outsiders, preserve permission after the meeting, and accept members',async()=>{const h=setup();h.meeting.audience='MEMBERS';h.meeting.isPublic=false;const issued=await h.api.issueMeetingCheckIn(clubId,meetingId);h.student();await assert.rejects(h.api.checkInMeeting(meetingId,issued.token),/members only/);h.member();assert.equal((await h.api.checkInMeeting(meetingId,issued.token)).status,'checked-in')})
test('expired, invalid, closed, wrong-meeting, and revoked-issuer codes cannot record attendance',async()=>{const h=setup(),issued=await h.api.issueMeetingCheckIn(clubId,meetingId);await assert.rejects(h.api.checkInMeeting(meetingId,'static'),/Invalid/);await assert.rejects(h.api.checkInMeeting(clubId,issued.token),/expired/);await h.api.closeMeetingCheckIn(clubId,meetingId);h.student();await assert.rejects(h.api.checkInMeeting(meetingId,issued.token),/expired/);assert.equal(h.rows().length,0);const expired=setup(),code=await expired.api.issueMeetingCheckIn(clubId,meetingId);expired.expire();await assert.rejects(expired.api.checkInMeeting(meetingId,code.token),/expired/);const revoked=setup(),other=await revoked.api.issueMeetingCheckIn(clubId,meetingId);revoked.revoke();revoked.student();await assert.rejects(revoked.api.checkInMeeting(meetingId,other.token),/no longer available/)})
test('meeting edits require permission and revision, invalidate QR tokens, and keep audience consistent',async()=>{const h=setup();await h.api.issueMeetingCheckIn(clubId,meetingId);const input={id:meetingId,clubId,title:'Members',date:new Date(),location:'Hall',audience:'MEMBERS',revision:0,agenda:'Agenda',recap:'Recap',resources:[]};await h.api.saveMeeting(input);assert.equal(h.meeting.isPublic,false);assert.equal(h.tokens().length,0);await assert.rejects(h.api.saveMeeting(input),/changed/);h.student();await assert.rejects(h.api.saveMeeting({...input,revision:1}),/Denied/)})
test('old meetings cannot issue new check-in codes and unsafe resource links are rejected',async()=>{const h=setup();h.meeting.date=new Date(0);await assert.rejects(h.api.issueMeetingCheckIn(clubId,meetingId),/Attendance opens/);const {meetingInputSchema}=load('lib/meetings.ts');assert.equal(meetingInputSchema.safeParse({clubId,title:'A',date:new Date(),location:'Hall',audience:'MEMBERS',resources:[{id:meetingId,label:'File',kind:'FILE',url:'javascript:alert(1)'}]}).success,false)})
test('attendance history redacts anonymous applicants and summary only counts held recruitment meetings',async()=>{
 const tx={meeting:{findFirst:async()=>({id:meetingId,clubId}),count:async({where})=>{assert.equal(where.audience,'RECRUITMENT');assert.equal(where.isPublic,true);assert.ok(where.date.lte instanceof Date);return 3}},eventAttendance:{findMany:async()=>[{id:'row',checkedInAt:new Date(),student:{id:'secret',email:'secret@example.com',studentProfile:{firstName:'Secret',lastName:'Name'},applications:[{id:'anonymous-app'}]}}],count:async({where})=>{assert.equal(where.studentId,'student');assert.equal(where.event.audience,'RECRUITMENT');return 2}},application:{findFirst:async()=>({studentId:'student',round:{anonymousReview:true}})}}
 const api=load('actions/meetings.ts',{'@/utils/prisma':{prisma:tx},'@/utils/auth':{requireClubPermission:async()=>({membership:{permissions:['applications.review','meetings.attendance']}})},'next/cache':{revalidatePath:()=>{}}})
 const history=await api.meetingAttendance(clubId,meetingId);assert.equal(history[0].name,'Anonymous applicant');assert.equal(history[0].email,null);assert.ok(!JSON.stringify(history).includes('secret'))
 assert.deepEqual(await api.recruitmentAttendanceSummary(clubId,'application'),{held:3,attended:2})
})
