const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const nodes=n=>!n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];
const text=n=>typeof n==='string'||typeof n==='number'?String(n):Array.isArray(n)?n.map(text).join(''):n?.props?text(n.props.children):'';
const flush=()=>new Promise(r=>setImmediate(r));
function harness(){
 const slots=[],effects=[],commands=[],ballots=[];let cursor=0,poll,deny=false;
 const session={id:'session',roundId:'round',clubId:'club',state:'OPEN',currentPass:1,revision:1,targetSize:1,participants:[{memberId:'member'}],candidates:[{applicationId:'candidate',position:0}],passes:[{number:1,state:'OPEN',candidates:[{applicationId:'candidate',position:0,ballots:[]}]}],createdAt:new Date(),publishedAt:null};
 const view=()=>({sessions:[session],session,summary:{total:1,processed:session.passes[0].candidates[0].ballots.length,passed:session.passes[0].candidates[0].ballots.length,held:0,notPassed:0,remaining:1-session.passes[0].candidates[0].ballots.length,target:1,targetReached:!!session.passes[0].candidates[0].ballots.length,outcomes:[{applicationId:'candidate',outcome:session.passes[0].candidates[0].ballots.length?'PASS':'UNRESOLVED',passNumber:1,automatic:false}]},memberId:'member',canVote:true,canManage:true,canStart:true,canFinish:true,canReopen:true,canPublish:true,eligible:[],rounds:[{id:'round',name:'Round 1'}],graduationYears:[{id:'candidate',student:{studentProfile:{gradYear:2028}}}]});
 const react={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]},useRef(initial){const i=cursor++;return slots[i]??=({current:initial})},useCallback(fn,deps){const i=cursor++,prev=slots[i];if(!prev||deps.some((v,j)=>v!==prev.deps[j]))slots[i]={fn,deps};return slots[i].fn},useEffect(fn,deps){const i=cursor++,prev=slots[i];if(!prev||deps.some((v,j)=>v!==prev[j])){slots[i]=deps;effects.push(fn)}}};
 const api={getVotingWorkspace:async()=>{if(deny)throw Error('Access revoked');return structuredClone(view())},createVotingSession:async()=>{throw Error('unused')},submitVotingBallot:async d=>{ballots.push(d);session.passes[0].candidates[0].ballots.push({...d,memberId:'member'});session.revision++},commandVotingSession:async d=>{commands.push(d);if(d.action==='COMPLETE_PASS'){session.state='PAUSED';session.passes[0].state='COMPLETED'}if(d.action==='FINISH')session.state='COMPLETED';if(d.action==='PUBLISH')session.publishedAt=new Date();session.revision++}};
 const mod={exports:{}};const code=ts.transpileModule(fs.readFileSync('components/live-voting/board-decision-mode.tsx','utf8')+'\nexports.TestBoard=VotingBoard;',{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 new Function('require','module','exports','setInterval','clearInterval',code)(name=>name==='react'?react:name==='@/lib/workspace-api'?api:name==='@/contexts/demo-context'?{useDemoMode:()=>({isDemoEnabled:false})}:name==='@/components/ui/button'?{Button:'Button'}:name==='@/components/applicant-intelligence'?{ApplicantDisplayPanel:'ApplicantDisplayPanel'}:name.startsWith('@/')||name.endsWith('.css')?{}:require(name),mod,mod.exports,fn=>{poll=fn;return 1},()=>{});
 const changes=[];
 return {render(){cursor=0;const result=mod.exports.TestBoard({clubId:'club',applicants:[],onDecision:(...args)=>changes.push(args)});while(effects.length)effects.shift()();return result},poll:()=>poll(),revoke:()=>deny=true,commands,ballots,changes,session};
}
const button=(tree,label)=>nodes(tree).find(n=>n.type==='Button'&&text(n)===label);
test('board uses shared presentation, saves a ballot without publishing, and continues past advisory target',async()=>{const h=harness();h.render();await flush();let tree=h.render();tree=h.render();assert.ok(nodes(tree).some(n=>n.type==='ApplicantDisplayPanel'&&n.props.mode==='voting'));await button(tree,'Pass').props.onClick();await flush();tree=h.render();assert.equal(h.ballots.length,1);assert.equal(h.commands.length,0);assert.equal(h.changes.length,0);assert.match(text(tree),/Target reached/);assert.equal(button(tree,'Pass').props.disabled,true);assert.equal(h.session.state,'OPEN')});
test('leadership explicitly completes/finishes then confirms selected candidates before publication',async()=>{const h=harness();h.render();await flush();let tree=h.render();tree=h.render();button(tree,'Pass').props.onClick();await flush();tree=h.render();button(tree,'Complete pass').props.onClick();await flush();tree=h.render();assert.match(text(tree),/Would you like another pass/);button(tree,'Finish session').props.onClick();await flush();tree=h.render();const candidateLabel=nodes(tree).find(n=>n.type==='label'&&text(n).includes('candidate · Pass'));assert.ok(candidateLabel);nodes(candidateLabel).find(n=>n.type==='input').props.onChange({target:{checked:true}});tree=h.render();assert.equal(button(tree,'Publish 1 decisions').props.disabled,true);const confirmation=nodes(tree).find(n=>n.type==='label'&&text(n).includes('I reviewed'));nodes(confirmation).find(n=>n.type==='input').props.onChange({target:{checked:true}});tree=h.render();assert.equal(button(tree,'Publish 1 decisions').props.disabled,false);button(tree,'Publish 1 decisions').props.onClick();await flush();assert.equal(h.commands.at(-1).action,'PUBLISH');assert.deepEqual(h.commands.at(-1).applicationIds,['candidate']);assert.deepEqual(h.changes,[['candidate','ACCEPTED']])});
test('server polling refreshes ballots from another device and clears applicant panel after access revocation',async()=>{const h=harness();h.render();await flush();let tree=h.render();h.session.passes[0].candidates[0].ballots.push({memberId:'member',decision:'HOLD'});await h.poll();await flush();tree=h.render();assert.match(text(tree),/Your ballot in this pass: Hold \/ Fringe/);h.revoke();await h.poll();await flush();tree=h.render();assert.match(text(tree),/Access revoked/);assert.equal(nodes(tree).some(n=>n.type==='ApplicantDisplayPanel'),false)});
