const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const {load,uuid}=require('./helpers/voting-harness.cjs');
const nodes=n=>!n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)],text=n=>typeof n==='string'?n:Array.isArray(n)?n.map(text).join(''):n?.props?text(n.props.children):'';
const flush=()=>new Promise(r=>setImmediate(r));
function harness({authenticated=true,demoEnabled=false,demoScoped=false,status='JOINABLE'}={}){
 const slots=[],effects=[],calls=[];let cursor=0,poll;
 const session={id:uuid(1),clubId:uuid(2),currentPass:1,state:'OPEN',revision:1,activeApplicationId:uuid(3),participants:[{memberId:uuid(5)}],passes:[{number:1,state:'OPEN',candidates:[{applicationId:uuid(3),ballots:[]},{applicationId:uuid(4),ballots:[]}]}]};
 const react={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]},useRef(initial){return slots[cursor++]??=({current:initial})},useCallback(fn,deps){const i=cursor++,prev=slots[i];if(!prev||deps.some((v,j)=>v!==prev.deps[j]))slots[i]={fn,deps};return slots[i].fn},useEffect(fn,deps){const i=cursor++,prev=slots[i];if(!prev||deps.some((v,j)=>v!==prev[j])){slots[i]=deps;effects.push(fn)}}};
 const api={getVotingJoinInfo:async()=>{calls.push('info');return ['JOINABLE','ALREADY_JOINED'].includes(status)?{status,clubId:session.clubId,clubName:'Club',sessionId:session.id}:{status}},joinVotingSession:async id=>{calls.push(['join',id]);return{clubId:session.clubId,sessionId:id}},getJoinedVotingWorkspace:async()=>{calls.push('workspace');return structuredClone({session,memberId:uuid(5),canVote:true,summary:{target:3,passed:0,held:0,notPassed:0,remaining:2}})},submitVotingBallot:async input=>{calls.push(['ballot',input]);session.passes[0].candidates.find(c=>c.applicationId===input.applicationId).ballots.push({memberId:uuid(5),decision:input.decision})}};
 const mod={exports:{}};new Function('require','module','exports','setInterval','clearInterval',ts.transpileModule(fs.readFileSync('components/live-voting/session-join.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText)(n=>n==='react'?react:n==='next/link'?{default:'Link',__esModule:true}:n==='@/contexts/auth-context'?{useAuth:()=>({user:authenticated?{id:'user'}:null,loading:false})}:n==='@/contexts/demo-context'?{useDemoMode:()=>({ready:true,isDemoEnabled:demoEnabled,state:{memberships:[]}})}:n==='@/lib/workspace-api'?api:n==='@/lib/voting-presentation'?load('lib/voting-presentation.ts'):n==='@/components/ui/button'?{Button:'Button'}:n==='@/components/applicant-intelligence'?{ApplicantDisplayPanel:'ApplicantDisplayPanel'}:n.endsWith('.css')?{}:require(n),mod,mod.exports,fn=>{poll=fn;return 1},()=>{});
 return{calls,session,poll:()=>poll(),render(){cursor=0;const tree=mod.exports.VotingSessionJoin({sessionId:session.id,demoScoped});while(effects.length)effects.shift()();return tree}};
}
const button=(tree,label)=>nodes(tree).find(n=>n.type==='Button'&&text(n)===label);
test('unauthenticated join retains a safe return route and makes no voting calls',()=>{const h=harness({authenticated:false}),tree=h.render();assert.match(text(tree),/Sign in to verify/);assert.ok(nodes(tree).some(n=>n.type==='a'&&n.props.href.includes('/login?next=%2Fvoting%2F')));assert.equal(h.calls.length,0)});
for(const status of ['NOT_FOUND','NOT_JOINABLE','FINISHED','UNAUTHORIZED','ROSTER_LOCKED'])test(`join UI explicitly handles ${status}`,async()=>{const h=harness({status});h.render();await flush();const tree=h.render();assert.ok(nodes(tree).some(n=>n.props?.role==='status'));assert.equal(button(tree,'Join session'),undefined);assert.equal(nodes(tree).some(n=>n.type==='ApplicantDisplayPanel'),false)});
test('successful/idempotent join enters the same durable candidate, saves ballots, and polls leader navigation',async()=>{const h=harness({status:'ALREADY_JOINED'});h.render();await flush();let tree=h.render();assert.match(text(tree),/already joined/);await button(tree,'Enter voting').props.onClick();tree=h.render();await flush();tree=h.render();assert.ok(nodes(tree).some(n=>n.type==='ApplicantDisplayPanel'&&n.props.sessionId===h.session.id&&n.props.applicationId===uuid(3)));await button(tree,'Pass').props.onClick();tree=h.render();assert.ok(h.calls.some(c=>Array.isArray(c)&&c[0]==='ballot'));assert.equal(button(tree,'Pass').props.disabled,true);h.session.activeApplicationId=uuid(4);await h.poll();tree=h.render();assert.ok(nodes(tree).some(n=>n.type==='ApplicantDisplayPanel'&&n.props.applicationId===uuid(4)));assert.equal(button(tree,'Pass').props.disabled,false)});
test('Demo and production join paths cannot cross the boundary or silently fall back',()=>{for(const config of [{demoScoped:true,demoEnabled:false},{demoScoped:false,demoEnabled:true}]){const h=harness(config),tree=h.render();assert.match(text(tree),/Demo/);assert.equal(h.calls.length,0)}});
