"use client"
import { useCallback, useEffect, useRef, useState } from "react"
import { ApplicantDisplayPanel } from "@/components/applicant-intelligence"
import { getVotingWorkspace, createVotingSession, submitVotingBallot, commandVotingSession, seedVotingDemo } from "@/lib/workspace-api"
import type { getClubPipeline } from "@/lib/workspace-api"
import type { AppStatus } from "@prisma/client"
import { useDemoMode } from "@/contexts/demo-context"
import { QrCodeCard } from "@/components/qr/qr-code-card"
import { liveVotingFields, defaultVotingDisplay, readVotingDisplay, votingJoinPath, votingDisplayWarning, votingSessionStage } from "@/lib/voting-presentation"
import { fieldLabels, type ApplicantField } from "@/lib/applicant-display"
import type { Decision } from "@/lib/voting-engine"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog"
import "./voting-mode.css"
type Pipeline = Awaited<ReturnType<typeof getClubPipeline>>
type Workspace = Awaited<ReturnType<typeof getVotingWorkspace>>
const labels = { PASS: "Pass", HOLD: "Hold / Fringe", NOT_PASS: "Do Not Pass", UNRESOLVED: "Unresolved" }
export function BoardDecisionMode(props: { applicants: Pipeline["applications"]; rounds: Pipeline["rounds"]; clubId: string; clubName: string; canDecide: boolean; onDecision: (id: string,status: AppStatus)=>void }) {
  const [open,setOpen]=useState(false)
  return <><Button variant="outline" size="sm" onClick={()=>setOpen(true)}>Recruitment voting</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent aria-describedby={undefined} className="oc-voting-stage inset-0 flex h-dvh w-screen max-w-none translate-x-0 translate-y-0 flex-col overflow-y-auto rounded-none bg-background p-6 sm:max-w-none"><DialogTitle>{props.clubName} · Recruitment voting</DialogTitle>{open&&<VotingBoard {...props} />}</DialogContent></Dialog></>
}
export function VotingBoard({ clubId, applicants, onDecision }: Parameters<typeof BoardDecisionMode>[0]) {
  const demo = useDemoMode()
  const requestRevision = useRef({value:0})
  const initializedSession = useRef<string | undefined>(undefined)
  const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false)
  const [sessionId,setSessionId]=useState<string>(),[round,setRound]=useState(""),[target,setTarget]=useState(40),[rule,setRule]=useState("NONE"),[threshold,setThreshold]=useState(100),[members,setMembers]=useState<string[]>([])
  const [previewCandidate,setPreviewCandidate]=useState("")
  const [previewFits,setPreviewFits]=useState<boolean|null>(null),[presentFits,setPresentFits]=useState<boolean|null>(null)
  const [present,setPresent]=useState(false),[displayFields,setDisplayFields]=useState<ApplicantField[]>(defaultVotingDisplay.fields),[creationCandidates,setCreationCandidates]=useState<string[]>([])
  const [index,setIndex]=useState(0),[ballotFilter,setBallotFilter]=useState("ALL"),[filter,setFilter]=useState("ALL"),[year,setYear]=useState("ALL"),[viewPass,setViewPass]=useState(0),[selected,setSelected]=useState<string[]>([]),[publishReview,setPublishReview]=useState(false),[override,setOverride]=useState<Decision>("HOLD"),[reason,setReason]=useState("")
  const refresh=useCallback(async()=>{const request=++requestRevision.current.value;try{const v=await getVotingWorkspace(clubId,sessionId);if(request!==requestRevision.current.value)return;setData(v);setError("")}catch(e){if(request!==requestRevision.current.value)return;setData(null);setError(e instanceof Error?e.message:"Session unavailable.")}},[clubId,sessionId])
  useEffect(()=>{const revision=requestRevision.current;let live=true;const poll=async()=>{if(live)await refresh()};void poll();const timer=setInterval(()=>void poll(),5000);return()=>{live=false;revision.value++;clearInterval(timer)}},[refresh])
  async function run(work:()=>Promise<unknown>){if(busy)return;setBusy(true);try{await work();await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not save.")}finally{setBusy(false)}}
  const s=data?.session,summary=data?.summary,current=s?.passes.find(p=>p.number===s.currentPass),shown=s?.passes.find(p=>p.number===(viewPass||s.currentPass))
  const liveNavigation=!!s&&current?.state==="OPEN"&&["OPEN","PAUSED"].includes(s.state)&&(!viewPass||viewPass===s.currentPass)
  useEffect(()=>{if(s&&initializedSession.current!==s.id){initializedSession.current=s.id;setTarget(s.targetSize);setDisplayFields(readVotingDisplay(s.displayConfig).fields);setViewPass(0);setIndex(0);setSelected([]);setPublishReview(false)}},[s])
  const queue=(shown?.candidates??s?.candidates??[]).filter(c=>filter==="ALL"||summary?.outcomes.find(o=>o.applicationId===c.applicationId)?.outcome===filter).filter(c=>year==="ALL"||String(data?.graduationYears.find(a=>a.id===c.applicationId)?.student.studentProfile?.gradYear)===year)
  const filteredQueue=queue.filter(c=>ballotFilter==="ALL"||(shown?.candidates.find(v=>v.applicationId===c.applicationId)?.ballots.some(b=>b.memberId===data?.memberId)??false)===(ballotFilter==="VOTED"))
  const app=!liveNavigation ? filteredQueue[Math.min(index,Math.max(0,filteredQueue.length-1))] : (current?.candidates.find(c=>c.applicationId===s?.activeApplicationId)??filteredQueue[0]),outcome=summary?.outcomes.find(o=>o.applicationId===app?.applicationId),entry=shown?.candidates.find(c=>c.applicationId===app?.applicationId),mine=entry?.ballots.find(b=>b.memberId===data?.memberId)
  const years=[...new Set(data?.graduationYears.map(a=>a.student.studentProfile?.gradYear).filter(Boolean))].sort()
  const command=(action:string,extra:Record<string,unknown>={})=>commandVotingSession({clubId,sessionId:s!.id,revision:s!.revision,action,...extra})
  const displayConfig={version:1 as const,fields:displayFields}
  const setupWarning=votingDisplayWarning(displayConfig)
  const savedDisplayWarning=s?votingDisplayWarning(readVotingDisplay(s.displayConfig)):null
  const displayDirty=!!s && JSON.stringify(displayConfig)!==JSON.stringify(readVotingDisplay(s.displayConfig))
  const previewPool=applicants.filter(a=>a.roundId===round&&a.status!=="DRAFTING"&&(!creationCandidates.length||creationCandidates.includes(a.id)))
  const previewApplicant=previewPool.find(a=>a.id===previewCandidate)??previewPool[0]
  const navigate=(direction:number)=>{if(!liveNavigation){setIndex(i=>Math.max(0,Math.min(filteredQueue.length-1,i+direction)));return}const position=filteredQueue.findIndex(c=>c.applicationId===app?.applicationId);const next=filteredQueue[position+direction];if(next)void run(()=>command("SET_CANDIDATE",{applicationId:next.applicationId}))}
  const voteControls=s&&app?<div className="flex flex-wrap items-center justify-center gap-3">{(["PASS","HOLD","NOT_PASS"] as const).map(d=><Button key={d} variant={d==="PASS"?"default":"outline"} disabled={busy||(present&&!presentFits)||!data?.canVote||!!mine||s.state!=="OPEN"||current?.state!=="OPEN"||!entry} onClick={()=>void run(()=>submitVotingBallot({clubId,sessionId:s.id,passNumber:s.currentPass,applicationId:app.applicationId,decision:d}))}>{labels[d]}</Button>)}</div>:null
  if(present && s && summary && data) return <section className="oc-voting-projector" aria-label="Live voting projector">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Pass {s.currentPass} · {votingSessionStage(s)} · Candidate {Math.max(0,current?.candidates.findIndex(c=>c.applicationId===app?.applicationId)??0)+1} of {current?.candidates.length??0}</h2><p>Target {summary.target} · Passed {summary.passed} · Hold {summary.held} · Not passed {summary.notPassed} · Remaining {summary.remaining}</p></div><Button variant="outline" className="mr-8" onClick={()=>setPresent(false)}>Back to session controls</Button></header>
    {error&&<p role="alert" className="text-destructive">{error}</p>}
    {app?<ApplicantDisplayPanel key={app.applicationId} clubId={clubId} applicationId={app.applicationId} sessionId={s.id} mode="voting" layout="slide" refreshKey={String(s.revision)} onFitChange={setPresentFits}/>:<p role="status">Waiting for the next pass.</p>}
    {presentFits===false&&<p role="alert" className="text-destructive">The selected content does not fit this live slide. Return to session controls and use a larger presentation viewport; voting is disabled in this view.</p>}
    <footer className="space-y-3"><p role="status">Outcome: {outcome?labels[outcome.outcome]:"Unresolved"} · Your ballot: {mine?labels[mine.decision as Decision]:"Not recorded"} · {entry?.ballots.length??0} / {s.participants.length} ballots{summary.targetReached&&" · Target reached; voting can continue."}</p><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="outline" disabled={busy||!data.canStart||filteredQueue.findIndex(c=>c.applicationId===app?.applicationId)<=0} onClick={()=>navigate(-1)}>Previous candidate</Button>{voteControls}<Button variant="outline" disabled={busy||!data.canStart||filteredQueue.findIndex(c=>c.applicationId===app?.applicationId)>=filteredQueue.length-1} onClick={()=>navigate(1)}>Next candidate</Button></div></footer>
  </section>
  return <div className="mx-auto w-full max-w-5xl space-y-5 py-5">
    <p className="text-xs text-muted-foreground">{demo.isDemoEnabled ? "Saved in this isolated demo browser" : "Saved on the server"} · refreshes every 5 seconds · votes never change application statuses until publication.</p>
    {error&&<p role="alert" className="text-destructive">{error}<Button variant="ghost" onClick={()=>void refresh()}>Refresh</Button></p>}
    {!data&&!error&&<p role="status">Loading voting workspace…</p>}
    {data&&<>
      {!!data.sessions.length&&<label className="block">Session history <select className="rounded border bg-background p-2" value={sessionId??data.session?.id??""} onChange={e=>{setData(null);setSessionId(e.target.value);setIndex(0);setViewPass(0);setSelected([]);setPublishReview(false)}}>{data.sessions.map(v=><option key={v.id} value={v.id}>{new Date(v.createdAt).toLocaleString()} · {v.state} · Pass {v.currentPass}</option>)}</select></label>}
      {data.canManage&&<details open={!s}><summary className="cursor-pointer py-2">Create a voting session</summary><form className="space-y-3 rounded-lg border p-4" onSubmit={e=>{e.preventDefault();void run(async()=>{const id=await createVotingSession({clubId,roundId:round,applicationIds:applicants.filter(a=>a.roundId===round&&a.status!=="DRAFTING"&&(!creationCandidates.length||creationCandidates.includes(a.id))).map(a=>a.id),displayConfig,participantIds:members,targetSize:target,autoAdvance:rule,threshold});setSessionId(id);setSelected([]);setViewPass(0)})}}>
        <label className="block">Recruitment round <select required className="rounded border bg-background p-2" value={round} onChange={e=>{setRound(e.target.value);setCreationCandidates([]);setPreviewCandidate("")}}><option value="">Choose round</option>{data.rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
        <p className="text-xs text-muted-foreground">Snapshots submitted candidates in this round from the current applicant selection. Existing sessions remain in history.</p>
        <details><summary>Select candidates (all submitted candidates by default)</summary>{applicants.filter(a=>a.roundId===round&&a.status!=="DRAFTING").map((a,i)=><label key={a.id} className="block min-h-9"><input type="checkbox" checked={creationCandidates.includes(a.id)} onChange={e=>setCreationCandidates(v=>e.target.checked?[...v,a.id]:v.filter(id=>id!==a.id))}/> Candidate {i+1}</label>)}</details>
        <fieldset className="grid gap-3 sm:grid-cols-3"><legend className="mb-2">These are the fields voting participants will see during this session.</legend>{liveVotingFields.map(f=><label key={f} className="flex min-h-9 items-center gap-2"><input type="checkbox" checked={displayFields.includes(f)} onChange={e=>setDisplayFields(v=>e.target.checked?[...v,f]:v.filter(x=>x!==f))}/>{fieldLabels[f]}</label>)}</fieldset>
        <p className="text-sm text-muted-foreground">Start with compact profile fields. Structured information and review notes can be selected when the preview fits; review the candidates and remove fields if content is too long. Résumé and structured experience cannot be shown together. Anonymous review still withholds identity and documents.</p>
        {setupWarning&&<p role="alert">{setupWarning}</p>}
        {previewFits===false&&<p role="alert">Too much selected content for the live display. Remove one or more fields to keep the candidate view on one screen at 1280 × 720.</p>}
        {previewApplicant&&!setupWarning&&<div className="oc-voting-preview"><h3 className="mb-3 font-semibold">Candidate display preview</h3><label className="mb-3 block">Preview candidate <select className="rounded border bg-background p-2" value={previewApplicant.id} onChange={e=>setPreviewCandidate(e.target.value)}>{previewPool.map((a,i)=><option key={a.id} value={a.id}>Candidate {i+1}</option>)}</select></label><ApplicantDisplayPanel clubId={clubId} applicationId={previewApplicant.id} mode="voting" layout="slide" previewConfig={displayConfig} onFitChange={setPreviewFits}/></div>}
        <label className="block">Target class size <input required type="number" min={1} max={2000} className="w-24 rounded border bg-background p-2" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label>
        <label className="block">Visible automatic advancement rule <select className="rounded border bg-background p-2" value={rule} onChange={e=>setRule(e.target.value)}><option value="NONE">None · complete ballots and strict majority</option><option value="UNANIMOUS">Unanimous Pass</option><option value="THRESHOLD">Pass threshold of all participants</option></select></label>
        {rule==="THRESHOLD"&&<label>Threshold % <input type="number" min={51} max={100} value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label>}
        <fieldset><legend>Authorized voting participants</legend>{data.eligible.map(m=><label key={m.id} className="mr-4 inline-flex min-h-11 items-center gap-2"><input type="checkbox" checked={members.includes(m.id)} onChange={e=>setMembers(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}/>{m.label}</label>)}</fieldset>
        <Button disabled={busy||!members.length||!round||!!setupWarning||!previewFits}>Create draft session</Button>
      </form></details>}
      {s&&summary?<>
        <div className="rounded-lg border bg-card p-4"><p className="font-semibold">{votingSessionStage(s)} · Pass {s.currentPass} · {data.rounds.find(r=>r.id===s.roundId)?.name}</p><p>Target: {summary.target} · Passed: {summary.passed} · Hold: {summary.held} · Not passed: {summary.notPassed} · Unresolved / remaining: {summary.remaining} · Processed: {summary.processed} / {summary.total}</p>{summary.targetReached&&<p role="status" className="font-semibold text-emerald-700">Target reached. Leadership can continue voting and review.</p>}{s.publishedAt&&<p>Published {new Date(s.publishedAt).toLocaleString()} · session sealed.</p>}</div>
        {data.canManage&&s.state==="DRAFT"&&!s.joinOpenedAt&&<section className="space-y-3 rounded-lg border p-4"><h3>Session display setup</h3><fieldset className="grid gap-3 sm:grid-cols-3"><legend>These are the fields voting participants will see during this session.</legend>{liveVotingFields.map(f=><label key={f} className="flex min-h-9 items-center gap-2"><input type="checkbox" checked={displayFields.includes(f)} onChange={e=>setDisplayFields(v=>e.target.checked?[...v,f]:v.filter(x=>x!==f))}/> {fieldLabels[f]}</label>)}</fieldset>{setupWarning&&<p role="alert">{setupWarning}</p>}{s.candidates[0]&&!setupWarning&&<div className="oc-voting-preview"><h3 className="mb-3 font-semibold">Candidate display preview</h3><label className="mb-3 block">Preview candidate <select className="rounded border bg-background p-2" value={s.candidates.find(c=>c.applicationId===previewCandidate)?.applicationId??s.candidates[0].applicationId} onChange={e=>setPreviewCandidate(e.target.value)}>{s.candidates.map((c,i)=><option key={c.applicationId} value={c.applicationId}>Candidate {i+1}</option>)}</select></label><ApplicantDisplayPanel clubId={clubId} applicationId={s.candidates.find(c=>c.applicationId===previewCandidate)?.applicationId??s.candidates[0].applicationId} mode="voting" layout="slide" previewConfig={displayConfig} onFitChange={setPreviewFits}/></div>}<Button disabled={busy||!!setupWarning} onClick={()=>void run(()=>command("CONFIGURE",{displayConfig}))}>Save display configuration</Button><p className="text-sm">Opening the lobby locks the display snapshot. The voting roster freezes when the first pass starts.</p></section>}
        {data.canStart&&s.state==="DRAFT"&&!s.joinOpenedAt&&<Button disabled={busy||!!setupWarning||!previewFits||(data.canManage&&displayDirty)} onClick={()=>void run(()=>command("OPEN_JOIN"))}>Open session for joining</Button>}
        {data.canManage&&s.joinOpenedAt&&s.state!=="COMPLETED"&&!s.publishedAt&&<details open={s.state==="DRAFT"}><summary className="cursor-pointer py-2">QR join and participants</summary><QrCodeCard title="Join this voting session" description={demo.isDemoEnabled?"Demo only: requires the isolated Demo session in this browser; no production session is accessed.":"Scan, sign in, and join with your current club voting permissions."} path={votingJoinPath(s.id,demo.isDemoEnabled)} filename="outclass-voting-join"/><ul className="mt-3">{data.joinedParticipants?.map(p=><li key={p.id}>{p.label} · {p.joinedAt?"Joined":"Invited, not checked in"}</li>)}</ul></details>}
        {data.canStart&&current?.state==="OPEN"&&<><Button disabled={!!savedDisplayWarning} onClick={()=>{setViewPass(0);setFilter("ALL");setYear("ALL");setBallotFilter("ALL");setPresent(true)}}>Present candidates</Button>{savedDisplayWarning&&<p role="status">This session retains its earlier display configuration. Use the review view, or create a new session with a fitting live-display selection. {savedDisplayWarning}</p>}</>}
        <div className="flex flex-wrap items-center gap-4"><label>Outcome <select className="rounded border bg-background p-2" value={filter} onChange={e=>{setFilter(e.target.value);setIndex(0)}}><option value="ALL">All outcomes</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Graduation year <select className="rounded border bg-background p-2" value={year} onChange={e=>{setYear(e.target.value);setIndex(0)}}><option value="ALL">All years</option>{years.map(y=><option key={y} value={y}>{y} ({data.graduationYears.filter(a=>a.student.studentProfile?.gradYear===y).length})</option>)}</select></label><label>Your voting state <select className="rounded border bg-background p-2" value={ballotFilter} onChange={e=>{setBallotFilter(e.target.value);setIndex(0)}}><option value="ALL">All candidates</option><option value="VOTED">Ballot recorded</option><option value="UNVOTED">Not voted</option></select></label><label>Review pass <select className="rounded border bg-background p-2" value={viewPass} onChange={e=>{setViewPass(Number(e.target.value));setIndex(0)}}><option value={0}>Current pass</option>{s.passes.map(p=><option key={p.number} value={p.number}>Pass {p.number} · {p.state}</option>)}</select></label></div>
        {app?<article className="space-y-4"><h2 className="font-display text-2xl">Candidate {Math.max(0,(liveNavigation?current!.candidates:filteredQueue).findIndex(c=>c.applicationId===app.applicationId))+1} of {liveNavigation?current!.candidates.length:filteredQueue.length}</h2><p>Latest outcome: {outcome?labels[outcome.outcome]:"Unresolved"}{outcome?.automatic&&" · Automatically advanced by configured rule"} · Your ballot in this pass: {mine?labels[mine.decision as Decision]:"Not recorded"} · {entry?.ballots.length??0} / {s.participants.length} ballots</p><ApplicantDisplayPanel key={app.applicationId} clubId={clubId} applicationId={app.applicationId} sessionId={s.id} mode="voting"/><div className="flex flex-wrap justify-between gap-3"><Button variant="outline" disabled={busy||(liveNavigation&&!data.canStart)||filteredQueue.findIndex(c=>c.applicationId===app.applicationId)<=0} onClick={()=>navigate(-1)}>Previous candidate</Button><div className="flex flex-wrap gap-2">{(["PASS","HOLD","NOT_PASS"] as const).map(d=><Button key={d} variant={d==="PASS"?"default":"outline"} disabled={busy||!data.canVote||!!mine||s.state!=="OPEN"||shown?.number!==s.currentPass||current?.state!=="OPEN"||!entry} onClick={()=>void run(()=>submitVotingBallot({clubId,sessionId:s.id,passNumber:s.currentPass,applicationId:app.applicationId,decision:d}))}>{labels[d]}</Button>)}</div><Button variant="outline" disabled={busy||(liveNavigation&&!data.canStart)||filteredQueue.findIndex(c=>c.applicationId===app.applicationId)>=filteredQueue.length-1} onClick={()=>navigate(1)}>Next candidate</Button></div>
        {data.canManage&&!s.publishedAt&&s.state!=="COMPLETED"&&<details><summary className="cursor-pointer py-3">Leadership override</summary><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void run(()=>command("OVERRIDE",{applicationId:app.applicationId,decision:override,reason}))}}><label>Outcome <select value={override} onChange={e=>setOverride(e.target.value as Decision)}>{(["PASS","HOLD","NOT_PASS"] as const).map(d=><option key={d} value={d}>{labels[d]}</option>)}</select></label><label>Reason <input required maxLength={1000} className="rounded border bg-background p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy}>Record override</Button></form></details>}
        </article>:<p>No candidates match this view.</p>}
        {(data.canManage||data.canStart||data.canFinish||data.canReopen)&&!s.publishedAt&&<div className="space-y-3 border-t pt-4">
          {data.canStart&&s.state==="OPEN"&&<Button disabled={busy} variant="outline" onClick={()=>void run(()=>command("PAUSE"))}>Pause session</Button>}
          {data.canStart&&s.state==="PAUSED"&&current?.state==="OPEN"&&<Button disabled={busy} onClick={()=>void run(()=>command("RESUME"))}>Resume voting</Button>}
          {data.canStart&&current?.state==="OPEN"&&s.state!=="COMPLETED"&&<><p>{current.candidates.every(c=>c.ballots.length===s.participants.length)?"Everyone has voted. Complete this pass, then choose another pass or finish.":"Some ballots remain. Closing this pass preserves unresolved candidates for review."}</p><Button variant="outline" disabled={busy} onClick={()=>void run(()=>command("COMPLETE_PASS"))}>Complete pass</Button></>}
          {((s.state==="DRAFT"&&!!s.joinOpenedAt)||(s.state==="PAUSED"&&current?.state!=="OPEN"))&&<><p>Would you like {s.currentPass?"another":"the first"} pass? Select candidates, or leave the selection empty to include Hold and Unresolved candidates.</p><details><summary className="cursor-pointer py-2">Select next-pass candidates ({selected.length})</summary>{summary.outcomes.map((o,i)=><label key={o.applicationId} className="block min-h-9"><input type="checkbox" checked={selected.includes(o.applicationId)} onChange={e=>setSelected(v=>e.target.checked?[...v,o.applicationId]:v.filter(id=>id!==o.applicationId))}/> Candidate {i+1} · {labels[o.outcome]}</label>)}</details><Button disabled={busy||!data.canStart} onClick={()=>void run(async()=>{await command("START_PASS",selected.length?{applicationIds:selected}:{});setSelected([]);setViewPass(0);setIndex(0)})}>Start pass {s.currentPass+1}</Button>{data.canFinish&&s.currentPass>0&&<Button variant="outline" disabled={busy} onClick={()=>void run(()=>command("FINISH"))}>Finish session</Button>}</>}
          {data.canReopen&&s.state==="COMPLETED"&&<Button variant="outline" disabled={busy} onClick={()=>void run(()=>command("REOPEN"))}>Reopen for review / another pass</Button>}
          {data.canManage&&s.state!=="COMPLETED"&&<form className="flex gap-3" onSubmit={e=>{e.preventDefault();void run(()=>command("CONFIGURE",{targetSize:target}))}}><label>Update target <input required type="number" min={1} max={2000} className="w-24 rounded border bg-background p-2" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><Button variant="outline" disabled={busy}>Save target</Button></form>}
        </div>}
        {data.canPublish&&s.state==="COMPLETED"&&!s.publishedAt&&<section className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">Review and publish application decisions</h3><p>Pass → Accepted · Hold → Waitlisted · Do Not Pass → Rejected. Unselected candidates keep their application status. Publication seals this session.</p>{summary.outcomes.filter(o=>o.outcome!=="UNRESOLVED").map((o,i)=><label key={o.applicationId} className="block min-h-9"><input type="checkbox" checked={selected.includes(o.applicationId)} onChange={e=>{setPublishReview(false);setSelected(v=>e.target.checked?[...v,o.applicationId]:v.filter(id=>id!==o.applicationId))}}/> Candidate {i+1} · {o.applicationId} · {labels[o.outcome]} · Pass {o.passNumber}</label>)}<label className="block"><input type="checkbox" checked={publishReview} onChange={e=>setPublishReview(e.target.checked)}/> I reviewed these candidates and confirm the student-visible statuses.</label><Button disabled={busy||!publishReview||!selected.length} onClick={()=>void run(async()=>{await command("PUBLISH",{applicationIds:selected});for(const id of selected){const o=summary.outcomes.find(o=>o.applicationId===id);if(o)onDecision(id,o.outcome==="PASS"?"ACCEPTED":o.outcome==="HOLD"?"WAITLISTED":"REJECTED")}setSelected([]);setPublishReview(false)})}>Publish {selected.length} decisions</Button></section>}
      </>:<div><p>No voting session yet.</p>{demo.isDemoEnabled && <Button disabled={busy} onClick={()=>void run(async()=>{setSessionId(await seedVotingDemo(clubId))})}>Load sample two-pass voting session</Button>}</div>}
    </>}
  </div>
}
