"use client";
import { useEffect, useState } from "react";
import { useAuth } from "@/contexts/auth-context";
import { getInterviewAccessSetup, approveInterviewRoomPanel, changeInterviewRoomPanel, setMemberInterviewOffices, setInterviewPanelAssignment } from "@/lib/workspace-api";
import { Button } from "@/components/ui/button";
type Setup=Awaited<ReturnType<typeof getInterviewAccessSetup>>;
export function InterviewAccessSetup({clubId}:{clubId:string}) {
  const {refreshUser}=useAuth();const [data,setData]=useState<Setup|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[applicationId,setApplicationId]=useState("");
  const [offices,setOffices]=useState<Record<string,string[]>>({}),[panels,setPanels]=useState<Record<string,string[]>>({});
  useEffect(()=>{let current=true;setData(null);getInterviewAccessSetup(clubId).then(value=>{if(current){setData(value);setOffices(Object.fromEntries(value.members.map(m=>[m.id,m.offices])));setPanels(Object.fromEntries(value.rooms.map(r=>[r.id,r.panelMemberIds])));setError("");}}).catch(()=>{if(current)setError("Owner access setup unavailable. Check current membership and retry.");});return()=>{current=false};},[clubId,retry]);
  const run=async(action:()=>Promise<unknown>,message:string)=>{if(busy)return;setBusy(true);setError("");try{await action();setNotice(message);await refreshUser();setRetry(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Access save failed. Your choices remain here; retry.");}finally{setBusy(false);}};
  const app=data?.applications.find(a=>a.id===applicationId);
  return <section aria-label="Interview access setup" className="space-y-6 p-4"><h2 className="oc-section-heading">Interview access setup</h2><p className="text-sm text-muted-foreground">Owner attestations only. Titles and scheduling rights do not grant private interview access. Changes are audited.</p>{error&&<p role="alert">{error} <Button type="button" variant="outline" onClick={()=>setRetry(v=>v+1)}>Reload setup</Button></p>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p role="status">Loading access setup…</p>}
    {data&&<fieldset disabled={busy} className="space-y-6"><section className="space-y-3"><h3 className="font-medium">Explicit leadership offices</h3>{data.members.map(member=><div key={member.id} className="space-y-2 rounded-lg border p-3"><h4>{member.name}</h4><div className="flex flex-wrap gap-4">{["PRESIDENT","VICE_PRESIDENT","BOARD"].map(office=><label key={office} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={(offices[member.id]||[]).includes(office)} onChange={e=>setOffices(v=>({...v,[member.id]:e.target.checked?[...(v[member.id]||[]),office]:(v[member.id]||[]).filter(x=>x!==office)}))}/>{office==="VICE_PRESIDENT"?"Vice-president":office==="PRESIDENT"?"President":"Board member"}</label>)}</div><Button type="button" variant="outline" onClick={()=>void run(()=>setMemberInterviewOffices({clubId,memberId:member.id,offices:offices[member.id]||[]}),"Office attestation saved.")}>Save offices for {member.name}</Button></div>)}</section>
    <section className="space-y-3"><h3 className="font-medium">Review room panels and existing bookings</h3><p className="text-sm text-muted-foreground">Review the exact panel before approving access for its current and future identified-round bookings. Panel edits and room closures revoke booking-managed grants and require approval again. Legacy, moved-round and otherwise ambiguous bookings stay unresolved. Manual grants are independent and must be revoked separately.</p>{!data.rooms.length&&<p>No rooms yet. Create a room in Rooms & Booking first.</p>}{data.rooms.map(room=><div key={room.id} className="space-y-3 rounded-lg border p-3"><h4>{room.name}</h4><p className="text-sm">{room.approvedPanelMemberIds.length?"Owner-approved panel":"Owner approval required"} · {room.bookings.length} bookings · {room.bookings.filter(b=>b.unresolved).length} unresolved</p><div className="flex flex-wrap gap-3">{data.members.map(member=><label key={member.id} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={(panels[room.id]||[]).includes(member.id)} onChange={e=>setPanels(v=>({...v,[room.id]:e.target.checked?[...(v[room.id]||[]),member.id]:(v[room.id]||[]).filter(id=>id!==member.id)}))}/>{member.name}{!member.participate?" (review permissions required)":""}</label>)}</div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={()=>void run(()=>changeInterviewRoomPanel({clubId,roomId:room.id,revision:room.revision,panelMemberIds:panels[room.id]||[]}),"Proposed panel saved. Review again before approving access.")}>Save proposed panel</Button><Button type="button" disabled={!room.isOpen||!room.panelMemberIds.length||JSON.stringify([...(panels[room.id]||[])].sort())!==JSON.stringify([...room.panelMemberIds].sort())} onClick={()=>void run(async()=>{const result=await approveInterviewRoomPanel({clubId,roomId:room.id,revision:room.revision,panelMemberIds:room.panelMemberIds,confirm:true});if(result.unresolved)setNotice(`${result.unresolved} ambiguous bookings still require manual review.`);},"Panel approved. Eligible bookings now grant interviewer entry; ambiguous cases remain unresolved.")}>Approve reviewed panel and bookings</Button></div></div>)}</section>
    <section className="space-y-3"><h3 className="font-medium">Manual applicant panel grants</h3><label className="block">Applicant and current round<select aria-label="Applicant and current round" className="block min-h-11 w-full rounded-md border bg-background p-2" value={applicationId} onChange={e=>setApplicationId(e.target.value)}><option value="">Choose an applicant</option>{data.applications.map(a=><option key={a.id} value={a.id}>{a.name} · {a.roundName}</option>)}</select></label>{app?.anonymous&&<p role="status">Private panel access is unavailable in anonymous rounds.</p>}{app&&data.members.map(member=>{const grant=data.grants.find(g=>g.applicationId===app.id&&g.roundId===app.roundId&&g.memberId===member.id&&!g.revokedAt);return <div key={member.id} className="flex flex-wrap items-center justify-between gap-2 border-t py-2"><span>{member.name} · {grant?(grant.bookingManaged?"Booking-managed access":"Manual access"):"No access"}</span><Button type="button" variant="outline" disabled={!grant&&(app.anonymous||!member.participate)} onClick={()=>void run(()=>setInterviewPanelAssignment({clubId,applicationId:app.id,roundId:app.roundId,memberId:member.id,assigned:!grant}),grant?"Panel access revoked. Booking changes will not restore this manual revocation.":"Explicit panel access granted.")}>{grant?"Revoke":"Grant"} panel access for {member.name}</Button></div>;})}</section></fieldset>}
  </section>;
}
