"use client"
import { useState } from "react"
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Globe2, MapPin } from "lucide-react"
import { Button } from "@/components/ui/button"
import { dayKey, slotTime, type InterviewRoom, type RoomBooking } from "@/lib/interview-rooms"
import "./scheduling.css"
export const timezones = ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "Europe/London", "UTC"]
export function BookingPicker({ rooms, clubName, roundName, booking, onReserve, onCancel, preview = false }: { rooms: InterviewRoom[]; clubName: string; roundName: string; booking?: RoomBooking | null; onReserve?: (slotId: string) => Promise<void>; onCancel?: () => Promise<void>; preview?: boolean }) {
  const [zone, setZone] = useState(rooms[0]?.timezone ?? "America/New_York")
  const [roomId, setRoomId] = useState("all"), [day, setDay] = useState(""), [selected, setSelected] = useState("")
  const [month, setMonth] = useState((rooms.flatMap(r => r.slots).sort((a,b) => a.startTime.localeCompare(b.startTime))[0]?.startTime ? dayKey(rooms.flatMap(r => r.slots).sort((a,b) => a.startTime.localeCompare(b.startTime))[0].startTime, zone) : dayKey(new Date(), zone)).slice(0,7))
  const bookingPast = !!booking && +new Date(booking.endTime) <= Date.now()
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [cancelConfirm, setCancelConfirm] = useState(false)
  const slots = rooms.filter(r => r.isOpen && (roomId === "all" || r.id === roomId)).flatMap(room => room.slots.filter(s => +new Date(s.startTime) > Date.now()).map(slot => ({ ...slot, room }))).sort((a,b) => a.startTime.localeCompare(b.startTime))
  const availableDates = [...new Set(slots.filter(s => s.booked < s.capacity || s.id === booking?.slotId).map(s => dayKey(s.startTime, zone)))]
  const selectedDay = availableDates.includes(day) && day.startsWith(month) ? day : availableDates.find(d => d.startsWith(month)) ?? ""
  const choice = slots.find(s => s.id === selected && dayKey(s.startTime, zone) === selectedDay)
  const first = new Date(`${month}-01T12:00:00`), days = new Date(first.getFullYear(), first.getMonth()+1,0).getDate()
  async function run(fn: () => Promise<void>) { setBusy(true); setError(""); try { await fn(); setSelected(""); setCancelConfirm(false) } catch(e) { setError(e instanceof Error ? e.message : "Could not update your booking.") } finally { setBusy(false) } }
  return <div className="ir-booking" aria-busy={busy}>
    <aside className="ir-booking-intro"><div className="ir-symbol"><CalendarDays /></div><p className="ir-eyebrow">{clubName}</p><h2>{roundName || "Your interview"}</h2><p>{booking ? bookingPast ? "Your recorded interview details are below." : "Your time is reserved. You can reschedule before the interview starts." : "Choose a day, select a time, then confirm your interview."}</p><div className="ir-detail"><Clock3 size={17} />{[...new Set(rooms.map(r => r.duration))].join(" / ") || "—"} minute interviews</div><div className="ir-detail"><MapPin size={17} />{rooms.length} {rooms.length === 1 ? "room" : "rooms"} available</div><label className="mt-6 block text-xs font-medium"><span className="mb-2 flex items-center gap-2"><Globe2 size={15} />Your time zone</span><select className="ir-select" value={zone} onChange={e => { setZone(e.target.value); setDay(""); setSelected("") }}>{[...new Set([zone,...timezones])].map(z => <option key={z}>{z}</option>)}</select></label>{preview && <p className="mt-5 rounded-lg border border-dashed p-3 text-xs">Applicant preview · selecting a time here does not make a booking.</p>}</aside>
    <div className="min-w-0 p-5 sm:p-7">
      {booking && <div className="ir-confirmed" role="status"><CheckCircle2 size={20} /><div><strong>{bookingPast ? "Recorded interview" : "Interview confirmed"}</strong><p>{new Date(booking.startTime).toLocaleString([], { timeZone: zone, dateStyle: "medium", timeStyle: "short" })}</p><p className="break-words">{booking.location}</p>{+new Date(booking.startTime) > Date.now() && <><p className="mt-2 text-xs">Choose another time below to reschedule.</p>{onCancel && <Button type="button" size="sm" variant="ghost" disabled={busy} onClick={() => setCancelConfirm(!cancelConfirm)}>Cancel booking</Button>}{cancelConfirm && <div className="mt-2 flex flex-wrap items-center gap-2 text-xs"><span>Release your reserved time?</span><Button size="sm" variant="destructive" disabled={busy} onClick={() => onCancel && void run(onCancel)}>Yes, cancel</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => setCancelConfirm(false)}>Keep booking</Button></div>}</>}</div></div>}
      {!slots.length && !booking && <p role="status" className="mb-5 rounded-md border border-border bg-muted p-4 text-sm leading-relaxed">No interview times are available right now. Your invitation is still recorded; check again later or contact the club.</p>}
      <label className="mb-5 block text-sm font-medium">Location<select className="ir-select mt-2" value={roomId} onChange={e => { setRoomId(e.target.value); setSelected(""); setDay("") }}><option value="all">All rooms</option>{rooms.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
      <div className="ir-calendar-layout"><section aria-label="Choose interview date"><div className="mb-4 flex items-center justify-between"><h3 className="oc-card-heading ">{first.toLocaleDateString([], { month:"long", year:"numeric" })}</h3><div className="flex gap-1">{[-1,1].map(step => <Button key={step} variant="ghost" size="icon" aria-label={step < 0 ? "Previous month" : "Next month"} onClick={() => { const d = new Date(first.getFullYear(),first.getMonth()+step,1,12); setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`); setSelected("") }}>{step < 0 ? <ChevronLeft size={16} /> : <ChevronRight size={16} />}</Button>)}</div></div><div className="ir-calendar">{["Su","Mo","Tu","We","Th","Fr","Sa"].map(d => <span className="ir-weekday" key={d}>{d}</span>)}{Array.from({length:first.getDay()},(_,i)=><span key={`pad-${i}`} />)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`;return <button key={date} type="button" disabled={!availableDates.includes(date) || busy} aria-label={new Date(`${date}T12:00:00`).toLocaleDateString([], {dateStyle:"full"})} aria-pressed={date === selectedDay} onClick={()=>{setDay(date);setSelected("")}}>{i+1}</button>})}</div>{!availableDates.some(d => d.startsWith(month)) && <p className="mt-4 text-xs text-muted-foreground">No available times this month. Try another month or location.</p>}</section>
      <section aria-label="Choose interview time"><h3 className="oc-card-heading mb-4">{selectedDay ? new Date(`${selectedDay}T12:00:00`).toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"}) : "Select a date"}</h3><div className="ir-times">{slots.filter(s=>dayKey(s.startTime,zone)===selectedDay).map(s=><button key={s.id} type="button" disabled={busy || s.booked >= s.capacity && s.id !== booking?.slotId} aria-pressed={choice?.id===s.id} onClick={()=>setSelected(s.id)}><strong>{slotTime(s.startTime,zone)}</strong><span>{s.room.name}{s.id===booking?.slotId ? " · Your booking" : s.booked>=s.capacity ? " · Full" : ""}</span></button>)}</div></section></div>
      {choice && <div className="ir-booking-action mt-6 flex flex-wrap items-center justify-between gap-4 border-t pt-5"><div className="text-sm"><strong>{new Date(choice.startTime).toLocaleDateString("en-US", { timeZone: zone, weekday: "short", month: "short", day: "numeric" })} · {slotTime(choice.startTime,zone)} – {slotTime(choice.endTime,zone)}</strong><p className="mt-1 text-xs text-muted-foreground">{zone}</p><p className="mt-1 break-words text-muted-foreground">{choice.room.location}</p></div><Button disabled={busy || preview || choice.id===booking?.slotId} onClick={()=>onReserve && void run(()=>onReserve(choice.id))}>{busy ? "Saving…" : preview ? "Preview only" : booking ? "Confirm new time" : "Confirm interview"}</Button></div>}
      {error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}
    </div>
  </div>
}
