"use client"
import { useMemo, useState } from "react"
import { CalendarDays, Clock3, Plus, Users, X } from "lucide-react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { roomSlots, roomInputSchema, slotTime, dayKey, type RoomInput, type RoomWorkspace, type InterviewRoom } from "@/lib/interview-rooms"
import { createInterviewRoom } from "@/lib/workspace-api"
import { timezones } from "./booking-picker"
export function CreateRoomDialog({ clubId, workspace, source, onClose, onCreated }: { clubId: string; workspace: RoomWorkspace; source?: InterviewRoom; onClose: () => void; onCreated: () => void }) {
  const [input,setInput]=useState<RoomInput>({clubId,roundId:source?.roundId ?? workspace.rounds[0]?.id ?? "",name:source?.name ?? "",location:source?.location ?? "",kind:source?.kind === "VIRTUAL" ? "VIRTUAL" : "IN_PERSON",timezone:source?.timezone ?? "America/New_York",dates:[dayKey(new Date(Date.now()+86400000),source?.timezone ?? "America/New_York")],start:"10:00",end:"12:00",duration:source?.duration ?? 20,buffer:source?.buffer ?? 0,capacity:source?.slots[0]?.capacity ?? 1,panelMemberIds:source?.panelMemberIds ?? []})
  const [date,setDate]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("")
  function set<K extends keyof RoomInput>(k:K,v:RoomInput[K]){setInput(p=>({...p,[k]:v}));setError("")}
  const preview=useMemo(()=>{try{return {slots:input.dates.length ? roomSlots(input) : [],error:""}}catch(e){return {slots:[],error:e instanceof Error ? e.message : "Check the schedule."}}},[input])
  return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{source ? "Add another time window" : "Create an interview room"}</DialogTitle><DialogDescription>Choose your room, dates, and interview length. We’ll build the booking slots.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setError("");const parsed=roomInputSchema.safeParse(input);if(!parsed.success){setError(parsed.error.issues[0].message);return}setBusy(true);try{await createInterviewRoom(parsed.data);onCreated()}catch(e){setError(e instanceof Error ? e.message : "Could not create room.")}finally{setBusy(false)}}}>
    <fieldset disabled={busy} className="grid gap-6 py-3 md:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]"><div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-2"><label className="ir-field">Room name<Input required maxLength={100} value={input.name} onChange={e=>set("name",e.target.value)} placeholder="e.g. Shannon 318C" /></label><label className="ir-field">Recruitment round<select className="ir-select" value={input.roundId} onChange={e=>set("roundId",e.target.value)}>{workspace.rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>
      <div className="flex gap-2" role="group" aria-label="Meeting format">{(["IN_PERSON","VIRTUAL"] as const).map(kind=><Button key={kind} type="button" variant={input.kind===kind?"secondary":"outline"} aria-pressed={input.kind===kind} onClick={()=>set("kind",kind)}>{kind==="IN_PERSON"?"In person":"Video call"}</Button>)}</div><label className="ir-field">{input.kind==="VIRTUAL"?"Meeting link":"Location"}<Input required type={input.kind==="VIRTUAL"?"url":"text"} value={input.location} onChange={e=>set("location",e.target.value)} placeholder={input.kind==="VIRTUAL"?"https://zoom.us/j/…":"Building and room, or full address"} /></label>
      <label className="ir-field">Time zone<select className="ir-select" value={input.timezone} onChange={e=>set("timezone",e.target.value)}>{[...new Set([input.timezone,...timezones])].map(z=><option key={z}>{z}</option>)}</select></label>
      <div><label className="ir-field">Interview dates<span className="flex gap-2"><Input aria-label="Add interview date" type="date" min={dayKey(new Date(),input.timezone)} value={date} onChange={e=>setDate(e.target.value)} /><Button type="button" variant="outline" disabled={!date||input.dates.includes(date)||input.dates.length>=14} onClick={()=>{set("dates",[...input.dates,date].sort());setDate("")}}><Plus size={15} />Add</Button></span></label><div className="mt-3 flex flex-wrap gap-2">{input.dates.map(d=><span key={d} className="inline-flex items-center gap-2 rounded-lg bg-muted px-3 py-2 text-xs">{new Date(`${d}T12:00:00`).toLocaleDateString([],{month:"short",day:"numeric"})}<button type="button" aria-label={`Remove ${d}`} onClick={()=>set("dates",input.dates.filter(v=>v!==d))}><X size={13} /></button></span>)}</div><p className="mt-2 text-xs text-muted-foreground">Add up to 14 dates with the same time window.</p></div>
      <div className="grid grid-cols-2 gap-3"><label className="ir-field">Start time<Input type="time" required value={input.start} onChange={e=>set("start",e.target.value)} /></label><label className="ir-field">End time<Input type="time" required value={input.end} onChange={e=>set("end",e.target.value)} /></label></div>
      <div className="grid grid-cols-3 gap-3">{([{key:"duration",label:"Length",values:[15,20,30,45,60,90]},{key:"buffer",label:"Buffer",values:[0,5,10,15,30]},{key:"capacity",label:"Students / slot",values:[1,2,3,4,5,10,20]}] as const).map(f=><label key={f.key} className="ir-field">{f.label}<select className="ir-select" value={input[f.key]} onChange={e=>set(f.key,Number(e.target.value))}>{f.values.map(v=><option key={v} value={v}>{v}{f.key==="capacity"?"":" min"}</option>)}</select></label>)}</div>
      <details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Interview panel · {input.panelMemberIds.length} selected</summary><p className="my-3 text-xs text-muted-foreground">Optional. Selected interviewers cannot staff overlapping rooms.</p><div className="max-h-40 space-y-2 overflow-y-auto">{workspace.members.map(m=><label key={m.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={input.panelMemberIds.includes(m.id)} onChange={e=>set("panelMemberIds",e.target.checked?[...input.panelMemberIds,m.id]:input.panelMemberIds.filter(id=>id!==m.id))} />{m.name}</label>)}</div></details>
    </div><aside className="rounded-xl border bg-slate-50 p-5"><p className="ir-eyebrow">Your booking page</p><CalendarDays className="my-5 size-8 text-primary" /><h3 className="text-xl font-semibold">{input.name || "Your interview room"}</h3><p className="mt-2 break-words text-sm text-muted-foreground">{input.location || "Add a location or meeting link"}</p><div className="my-6 grid grid-cols-2 gap-4 border-y py-4"><div><Clock3 size={17}/><strong className="mt-2 block text-2xl">{preview.slots.length}</strong><span className="text-xs text-muted-foreground">interview slots</span></div><div><Users size={17}/><strong className="mt-2 block text-2xl">{preview.slots.length*input.capacity}</strong><span className="text-xs text-muted-foreground">student openings</span></div></div><div className="flex flex-wrap gap-2">{preview.slots.slice(0,8).map(s=><span key={s.startTime.toISOString()} className="rounded-lg border bg-white px-2 py-1 text-xs">{slotTime(s.startTime,input.timezone)}</span>)}</div>{preview.slots.length>8&&<p className="mt-2 text-xs text-muted-foreground">+ {preview.slots.length-8} more slots</p>}<p className="mt-5 text-xs leading-6 text-muted-foreground">{input.duration} minute interviews{input.buffer?` with ${input.buffer} minutes between slots`:""}. Only applicants invited to this round can book. Any remaining time that cannot fit a full interview is left free.</p>{preview.error&&<p role="alert" className="mt-3 text-sm text-destructive">{preview.error}</p>}</aside></fieldset>
    {error&&<p role="alert" className="my-4 text-sm text-destructive">{error}</p>}<div className="mt-5 flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy||!preview.slots.length}>{busy?"Creating…":`Create room · ${preview.slots.length} slots`}</Button></div>
  </form></DialogContent></Dialog>
}
