"use client"
import { useEffect, useState } from "react"
import { CalendarDays, CheckCircle2, Copy, DoorOpen, Eye, MapPin, Plus, Users, Video } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { getRoomWorkspace, setInterviewRoomOpen } from "@/lib/workspace-api"
import { useDemoMode } from "@/contexts/demo-context"
import { type InterviewRoom, type RoomWorkspace, dayKey, slotTime } from "@/lib/interview-rooms"
import { BookingPicker } from "./booking-picker"
import { CreateRoomDialog } from "./create-room-dialog"
import "./scheduling.css"

export function RoomManager({ clubId }: { clubId: string }) {
  const demo=useDemoMode()
  const [data,setData]=useState<RoomWorkspace|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0)
  const [tab,setTab]=useState("rooms"),[round,setRound]=useState("all"),[date,setDate]=useState(""),[create,setCreate]=useState(false),[source,setSource]=useState<InterviewRoom>(),[busy,setBusy]=useState(""),[notice,setNotice]=useState("")
  useEffect(()=>{if(!demo.ready)return;let current=true;setLoading(true);getRoomWorkspace(clubId).then(d=>{if(current){setData(d);setError("")}}).catch(e=>{if(current)setError(e instanceof Error?e.message:"Could not load rooms.")}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[clubId,refresh,demo.ready])
  const rooms=data?.rooms.filter(r=>(round==="all"||r.roundId===round)&&(!date||r.slots.some(s=>dayKey(s.startTime,r.timezone)===date)))??[]
  const previewRound=round!=="all"?round:data?.rounds.find(r=>rooms.some(room=>room.roundId===r.id))?.id??data?.rounds[0]?.id
  const bookings=data?.bookings.filter(b=>rooms.some(r=>r.id===b.roomId)&&(!date||dayKey(b.startTime,rooms.find(r=>r.id===b.roomId)!.timezone)===date))??[]
  return <div className="ir-manager space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="ir-eyebrow">Interview scheduling</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Great conversations start here.</h2><p className="mt-2 text-sm text-muted-foreground">Set up a room. Share availability. Let applicants choose their time.</p></div><Button disabled={!data?.rounds.length||loading} onClick={()=>{setSource(undefined);setCreate(true)}}><Plus size={16}/>Create interview room</Button></header>
    {demo.isDemoEnabled&&<p className="text-xs text-muted-foreground">Demo schedule · changes stay in this browser.</p>}
    {notice&&<p role="status" className="flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 size={16}/>{notice}</p>}
    {error&&<div role="alert" className="rounded-xl border border-destructive/30 p-4 text-sm"><p>{error}</p><Button className="mt-3" variant="outline" onClick={()=>setRefresh(n=>n+1)}>Retry</Button></div>}
    {!data&&loading?<p role="status" className="py-12 text-muted-foreground">Loading your interview schedule…</p>:data&&<>
      {!data.rounds.length&&<p className="rounded-xl border p-5 text-sm">Create a recruitment round first, then add its interview rooms.</p>}
      <div className="ir-overview">{[{n:rooms.length,label:"Rooms",icon:DoorOpen},{n:rooms.reduce((n,r)=>n+r.slots.filter(s=>!date||dayKey(s.startTime,r.timezone)===date).length,0),label:"Time slots",icon:CalendarDays},{n:bookings.length,label:"Bookings",icon:Users}].map(({n,label,icon:Icon})=><div key={label}><Icon size={19}/><strong>{n}</strong><span>{label}</span></div>)}</div>
      <div className="flex flex-wrap items-center justify-between gap-3"><div role="group" aria-label="Schedule views" className="flex flex-wrap gap-1 rounded-xl bg-muted p-1">{[{id:"rooms",label:"Rooms"},{id:"bookings",label:"Bookings"},{id:"preview",label:"Applicant preview"}].map(t=><Button key={t.id} variant={tab===t.id?"secondary":"ghost"} aria-pressed={tab===t.id} onClick={()=>setTab(t.id)}>{t.id==="preview"&&<Eye size={15}/>} {t.label}</Button>)}</div><div className="flex flex-wrap gap-2"><select aria-label="Recruitment round" className="ir-select !w-auto" value={round} onChange={e=>setRound(e.target.value)}><option value="all">All rounds</option>{data.rounds.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{tab!=="preview"&&<><Input aria-label="Filter interview date" className="w-auto" type="date" value={date} onChange={e=>setDate(e.target.value)}/>{date&&<Button variant="ghost" onClick={()=>setDate("")}>All dates</Button>}</>}</div></div>
      {tab==="rooms"&&<div className="grid gap-5 lg:grid-cols-2">{rooms.map(room=><RoomCard key={room.id} room={room} workspace={data} date={date} busy={busy===room.id} onCopy={()=>{setSource(room);setCreate(true)}} onToggle={async()=>{setBusy(room.id);setError("");try{await setInterviewRoomOpen({roomId:room.id,open:!room.isOpen});setNotice(room.isOpen?"Room paused. Existing bookings are kept.":"Room is open for booking.");setRefresh(n=>n+1)}catch(e){setError(e instanceof Error?e.message:"Could not update room.")}finally{setBusy("")}}}/>)}{!rooms.length&&<div className="ir-empty lg:col-span-2"><DoorOpen size={36}/><h3>Make room for your next members</h3><p>Create a room and generate interview slots in one step.</p><Button disabled={!data.rounds.length} onClick={()=>{setSource(undefined);setCreate(true)}}><Plus size={16}/>Create your first room</Button></div>}</div>}
      {tab==="bookings"&&<div className="overflow-hidden rounded-xl border">{bookings.length?<ul className="divide-y">{bookings.map(b=>{const r=data.rooms.find(r=>r.id===b.roomId)!;return <li key={b.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-semibold">{b.candidate}</p><p className="mt-1 text-sm text-muted-foreground">{r.name} · {data.rounds.find(round=>round.id===b.roundId)?.name}</p></div><div className="text-sm"><p>{new Date(b.startTime).toLocaleDateString([],{timeZone:r.timezone,month:"short",day:"numeric"})} · {slotTime(b.startTime,r.timezone)}</p><p className="mt-1 text-xs text-muted-foreground">{r.timezone}</p></div></li>})}</ul>:<p className="p-8 text-center text-sm text-muted-foreground">No bookings match these filters yet.</p>}</div>}
      {tab==="preview"&&<BookingPicker key={previewRound} rooms={data.rooms.filter(r=>r.roundId===previewRound)} clubName={data.clubName} roundName={data.rounds.find(r=>r.id===previewRound)?.name??"Interview"} preview/>}
      <p className="text-xs leading-6 text-muted-foreground">Applicants marked Interviewing in the matching round can book from their application. Panel identities and other applicants’ details stay private.</p>
      {create&&<CreateRoomDialog clubId={clubId} workspace={data} source={source} onClose={()=>setCreate(false)} onCreated={()=>{setCreate(false);setDate("");setRound("all");setNotice("Room created. Invited applicants can now choose a time.");setRefresh(n=>n+1)}}/>}
    </>}
  </div>
}
function RoomCard({room,workspace,date,busy,onCopy,onToggle}:{room:InterviewRoom;workspace:RoomWorkspace;date:string;busy:boolean;onCopy:()=>void;onToggle:()=>void}){
  const [expanded,setExpanded]=useState(false),[copied,setCopied]=useState("")
  const slots=room.slots.filter(s=>!date||dayKey(s.startTime,room.timezone)===date)
  const open=slots.reduce((n,s)=>n+(+new Date(s.startTime)>Date.now()&&room.isOpen?Math.max(0,s.capacity-s.booked):0),0)
  return <article className="ir-room-card"><div className="flex items-start justify-between gap-3"><div className="ir-symbol">{room.kind==="VIRTUAL"?<Video/>:<DoorOpen/>}</div><span className={`rounded-full px-3 py-1 text-xs font-medium ${room.isOpen?"bg-emerald-50 text-emerald-700":"bg-muted text-muted-foreground"}`}>{room.isOpen?"Open for booking":"Paused"}</span></div><h3 className="mt-4 text-lg font-semibold">{room.name}</h3><p className="mt-1 flex items-start gap-2 break-all text-sm text-muted-foreground"><MapPin className="mt-0.5 size-4 shrink-0"/>{room.location}</p><p className="mt-3 text-xs text-muted-foreground">{workspace.rounds.find(r=>r.id===room.roundId)?.name} · {room.duration} min{room.buffer?` + ${room.buffer} min buffer`:""} · {open} openings</p><p className="mt-1 text-xs text-muted-foreground">{room.timezone}</p>{room.panelMemberIds.length>0&&<p className="mt-3 text-xs"><span className="text-muted-foreground">Panel: </span>{room.panelMemberIds.map(id=>workspace.members.find(m=>m.id===id)?.name??"Former member").join(", ")}</p>}<div className="ir-room-slots">{slots.slice(0,expanded?slots.length:8).map(s=><div key={s.id} className={s.booked>=s.capacity?"is-full":""}><span>{new Date(s.startTime).toLocaleDateString([],{timeZone:room.timezone,month:"short",day:"numeric"})}</span><strong>{slotTime(s.startTime,room.timezone)}</strong><small>{s.booked}/{s.capacity} booked</small></div>)}</div>{slots.length>8&&<Button variant="ghost" size="sm" onClick={()=>setExpanded(!expanded)}>{expanded?"Show fewer":`Show all ${slots.length} slots`}</Button>}<div className="mt-4 flex flex-wrap justify-between gap-2 border-t pt-4"><Button variant="outline" size="sm" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/interviews/book?clubId=${encodeURIComponent(room.clubId)}&roundId=${encodeURIComponent(room.roundId)}`);setCopied("Booking link copied.")}catch{setCopied("Could not copy. Your browser may require clipboard access.")}}}>Copy booking link</Button><Button variant="outline" size="sm" onClick={onCopy}><Copy size={14}/>Add dates</Button><Button variant="ghost" size="sm" disabled={busy} onClick={onToggle}>{busy?"Saving…":room.isOpen?"Pause bookings":"Reopen bookings"}</Button></div>{copied&&<p role="status" className="mt-2 text-xs text-muted-foreground">{copied}</p>}</article>
}
