"use client";
import { useEffect, useState } from "react";
import { createAdminStudent, createAdminClub, changeAdminDesignatedLeader } from "@/actions/admin-workspace";
import { getOrganizationOnboardingSchools } from "@/actions/platform-organization-onboarding";
import type { OrganizationOnboardingSchool } from "@/lib/platform-organization-onboarding";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
export function AdminOnboarding() {
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const [tab, setTab] = useState("student"), [schools, setSchools] = useState<OrganizationOnboardingSchool[]>([]), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [student, setStudent] = useState({ email: "", firstName: "", lastName: "", major: "", gradYear: "", clubId: "", reason: "" });
  const [club, setClub] = useState({ name: "", description: "", category: "Academic", organizationInfo: "", leaderEmail: "", leaderName: "", leaderYear: "", additionalLeaders: "", identifierTypeId: "", reason: "" });
  const [replacement, setReplacement] = useState({ clubId: "", invitationId: "", identifierTypeId: "", identifier: "", name: "", reason: "" });
  useEffect(() => { let live = true; getOrganizationOnboardingSchools().then(s => { if (live) { setSchools(s); setClub(c => ({ ...c, identifierTypeId: s[0]?.identifierTypeId || "" })); setReplacement(c => ({ ...c, identifierTypeId: s[0]?.identifierTypeId || "" })); } }).catch(e => { if (live) setMessage(e.message); }); return () => { live = false; }; }, []);
  const studentField = (key: keyof typeof student, label: string, type = "text", required = true) => <label key={key} className="block">{label}<Input type={type} required={required} value={student[key]} onChange={e => setStudent(s => ({ ...s, [key]: e.target.value }))} /></label>;
  const clubField = (key: keyof typeof club, label: string, type = "text", required = true) => <label key={key} className="block">{label}<Input type={type} required={required} value={club[key]} onChange={e => setClub(s => ({ ...s, [key]: e.target.value }))} /></label>;
  async function run(fn: () => Promise<unknown>) { setBusy(true); setMessage(""); try { await fn(); setRequestId(crypto.randomUUID()); setMessage("Created and invited. Delivery and claim activity are available in Audit Log and Clubs."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not complete onboarding."); } finally { setBusy(false); } }
  return <section className="max-w-3xl space-y-6"><div className="flex flex-wrap gap-3" role="group" aria-label="Onboarding actions">{[["student", "Create Student Account"], ["club", "Create Club"], ["leader", "Change designated leader"]].map(([id, label]) => <Button key={id} variant={tab === id ? "default" : "outline"} onClick={() => { setTab(id); setMessage(""); }}>{label}</Button>)}</div>
    {tab === "student" && <form className="grid gap-4 rounded-xl border bg-card p-6 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); if (!window.confirm(`Create and invite ${student.email}?`)) return; void run(() => createAdminStudent({ email: student.email, firstName: student.firstName, lastName: student.lastName, ...(student.major ? { major: student.major } : {}), ...(student.gradYear ? { gradYear: Number(student.gradYear) } : {}), ...(student.clubId ? { clubId: student.clubId } : {}), reason: student.reason })); }}><p className="text-sm text-muted-foreground sm:col-span-2">The student receives a single-use invitation and chooses their own password. Optional club relationships create an invitation, which the student must accept.</p>{studentField("email", "UVA email", "email")}{studentField("firstName", "First name")}{studentField("lastName", "Last name")}{studentField("major", "Initial major (optional)", "text", false)}{studentField("gradYear", "Graduation year (optional)", "number", false)}{studentField("clubId", "Club ID (optional)", "text", false)}<label className="block sm:col-span-2">Onboarding reason<Textarea required minLength={10} value={student.reason} onChange={e => setStudent(s => ({ ...s, reason: e.target.value }))} /></label><Button disabled={busy}>{busy ? "Creating…" : "Create and invite student"}</Button></form>}
    {tab === "club" && <form className="grid gap-4 rounded-xl border bg-card p-6 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); if (!window.confirm(`Create ${club.name} and invite its leaders?`)) return; void run(() => createAdminClub({ organization: { requestId, identifierTypeId: club.identifierTypeId, organizationName: club.name, presidentName: club.leaderName, presidentIdentifier: club.leaderEmail.split("@")[0], presidentYear: club.leaderYear, reason: club.reason }, leaderEmail: club.leaderEmail, description: club.description, category: club.category, organizationInfo: club.organizationInfo, additionalLeaders: club.additionalLeaders.split("\n").filter(line => line.trim()).map(line => { const [email, ...name] = line.split(","); return { email: email.trim(), name: name.join(",").trim() }; }) })); }}>
      <label className="block">Institution<select required className="block min-h-11 w-full rounded-md border bg-card px-3" value={club.identifierTypeId} onChange={e => setClub(c => ({ ...c, identifierTypeId: e.target.value }))}>{schools.map(s => <option key={s.identifierTypeId} value={s.identifierTypeId}>{s.schoolName} · {s.identifierLabel}</option>)}</select></label>{clubField("name", "Club name")}{clubField("category", "Category")}<label className="block sm:col-span-2">Description<Textarea required value={club.description} onChange={e => setClub(c => ({ ...c, description: e.target.value }))} /></label>{clubField("leaderEmail", "Designated leader email", "email")}{clubField("leaderName", "Designated leader name")}{clubField("leaderYear", "Leader graduation year", "number")}<label className="block sm:col-span-2">Organization information<Textarea value={club.organizationInfo} onChange={e => setClub(c => ({ ...c, organizationInfo: e.target.value }))} /></label><label className="block sm:col-span-2">Additional leaders (optional)<Textarea placeholder="email, name — one person per line" value={club.additionalLeaders} onChange={e => setClub(c => ({ ...c, additionalLeaders: e.target.value }))} /></label><label className="block sm:col-span-2">Reason<Textarea required minLength={10} value={club.reason} onChange={e => setClub(c => ({ ...c, reason: e.target.value }))} /></label><Button disabled={busy || !schools.length}>Create club and invite leaders</Button>
    </form>}
    {tab === "leader" && <form className="space-y-4 rounded-xl border bg-card p-6" onSubmit={e => { e.preventDefault(); if (!window.confirm("Revoke the pending owner invitation and designate this leader?")) return; void run(() => changeAdminDesignatedLeader(replacement)); }}><p>Only pending owner designations can be replaced. Claimed clubs retain their existing ownership management.</p>{(["clubId", "invitationId", "identifier", "name", "reason"] as const).map(key => <label key={key} className="block">{({ clubId: "Club ID", invitationId: "Pending invitation ID", identifier: "New leader university identifier", name: "New leader name", reason: "Reason" })[key]}<Input required value={replacement[key]} onChange={e => setReplacement(r => ({ ...r, [key]: e.target.value }))} /></label>)}<label className="block">Institution<select className="block min-h-11 w-full rounded border" value={replacement.identifierTypeId} onChange={e => setReplacement(r => ({ ...r, identifierTypeId: e.target.value }))}>{schools.map(s => <option key={s.identifierTypeId} value={s.identifierTypeId}>{s.schoolName}</option>)}</select></label><Button disabled={busy}>Change designated leader</Button></form>}
    <p role="status">{message}</p>
  </section>;
}
