"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { getAdminClub, loadAdminClubs, saveAdminClub, type getAdminClubs } from "@/actions/admin-clubs";
import { uploadClubAsset } from "@/actions/club-assets";
import { setAdminClubSuspended } from "@/actions/admin-workspace";
import { ClubProfileEditor } from "@/components/clubs/club-profile-editor";
import { profileDraft } from "@/lib/club-marketing";
import { clubAssetSource } from "@/lib/club-assets";
import { AdminRecovery } from "./admin-recovery";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { NativeSelect } from "@/components/ui/native-select";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
type Club = NonNullable<Awaited<ReturnType<typeof getAdminClub>>['value']>;
const blank = (schoolId: string): Club => ({ id: '', slug: '', schoolId, campusKey: '', isDiscoverable: false, applicationOpen: false, applicationDeadline: null, suspendedAt: null, version: '', profile: profileDraft({name:'',category:'Other',color:'#232D4B'}) });
export function AdminClubs({ initial }: { initial: Awaited<ReturnType<typeof getAdminClubs>> }) {
  const [data,setData]=useState(initial),[query,setQuery]=useState(''),[status,setStatus]=useState('ALL'),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false),[supportCode,setSupportCode]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState<Club|null>(null),[saved,setSaved]=useState<Club|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[lifecycle,setLifecycle]=useState(false),[notice,setNotice]=useState('');
  const origin=useRef<HTMLButtonElement|null>(null), heading=useRef<HTMLHeadingElement|null>(null), inFlight=useRef(false);
  useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>{loadAdminClubs({query,status,page}).then(r=>{if(!active)return;if(r.supportCode){setData({...initial,rows:[]});setSupportCode(r.supportCode)}else{setData(r.value!);setSupportCode('')}}).catch(()=>{if(active){setData({...initial,rows:[]});setError('Could not refresh clubs. Try again.')}}).finally(()=>{if(active)setLoading(false)})},200);return()=>{active=false;clearTimeout(timer)}},[query,status,page,refresh,initial]);
  async function open(id: string) {if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{const r=await getAdminClub(id);if(r.supportCode)setSupportCode(r.supportCode);else{setEditing(r.value!);setSaved(r.value!);setReason('');setNotice('')}}catch{setError('Club could not be loaded. Try again.')}finally{setBusy(false);inFlight.current=false}}
  if(supportCode)return <AdminRecovery supportCode={supportCode}/>;
  if(editing)return <div className="min-w-0 space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 ref={heading} tabIndex={-1} className="oc-section-heading">{editing.id ? 'Edit club' : 'Create club'}</h2><Button variant="outline" disabled={busy} onClick={()=>{if(editing.id && document.querySelector('form[data-unsaved="true"]')){setError('Publish or discard your profile changes before leaving.');return}setEditing(null);setRefresh(n=>n+1)}}>Back to clubs</Button></div>
    {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="text-destructive">{error}</p>}
    <fieldset disabled={busy} className="min-w-0 space-y-4 rounded-xl border bg-card p-5"><legend className="px-2 font-semibold">Platform metadata</legend><div className="grid gap-4 sm:grid-cols-2">
      <label className="space-y-2 text-sm">Slug<Input value={editing.slug} maxLength={100} onChange={e=>setEditing({...editing,slug:e.target.value})}/></label>
      <label className="space-y-2 text-sm">School / campus<NativeSelect value={editing.schoolId} disabled={!!editing.id} onChange={e=>setEditing({...editing,schoolId:e.target.value})}>{data.schools.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</NativeSelect></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.isDiscoverable} onChange={e=>setEditing({...editing,isDiscoverable:e.target.checked})}/>Discoverable</label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.applicationOpen} onChange={e=>setEditing({...editing,applicationOpen:e.target.checked})}/>Applications open</label>
      <label className="space-y-2 text-sm">Application deadline (UTC, optional)<Input type="datetime-local" value={editing.applicationDeadline?.slice(0,16)||''} onChange={e=>setEditing({...editing,applicationDeadline:e.target.value?new Date(e.target.value+'Z').toISOString():null})}/></label>
      <label className="space-y-2 text-sm">Reason for change<Input minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>
    </div><p className="text-xs leading-6 text-muted-foreground">Public profile fields below are shared with authorized leaders’ Appearance controls. Slug, school, discovery and recruiting availability are platform metadata here. Opening applications requires a configured native recruiting pipeline. Leaders are assigned through existing invitations and claims.</p>
    {editing.id&&<div className="flex flex-wrap items-center gap-3"><Link className="text-sm underline" href={`/club/${editing.id}`} target="_blank" rel="noopener noreferrer">View public profile ↗</Link><Link className="text-sm underline" href={`/platform/claims?clubId=${editing.id}`}>Club claims</Link><Link className="text-sm underline" href={`/platform/permissions?clubId=${editing.id}`}>Membership and access</Link><Button variant="outline" onClick={e=>{origin.current=e.currentTarget;setLifecycle(true)}}>{editing.suspendedAt?'Restore club':'Suspend club'}</Button></div>}
    </fieldset>
    <Button variant="ghost" disabled={busy} onClick={()=>{if(saved){setEditing(saved);setError('');setNotice('Platform metadata reset. Use Discard below to reset profile edits.')}}}>Reset platform metadata</Button>
    <ClubProfileEditor key={editing.id+editing.version} initial={editing.profile} externalDirty={!!saved&&(editing.slug!==saved.slug||editing.isDiscoverable!==saved.isDiscoverable||editing.applicationOpen!==saved.applicationOpen||editing.applicationDeadline!==saved.applicationDeadline)} onUpload={async file=>{if(!editing.id)throw Error('Create the club before uploading images.');const f=new FormData();f.set('clubId',editing.id);f.set('admin','true');f.set('file',file);return(await uploadClubAsset(f)).reference}} onSave={async profile=>{if(inFlight.current)throw Error('A save is already running.');inFlight.current=true;setBusy(true);try{const r=await saveAdminClub({...(editing.id?{id:editing.id,version:editing.version}:{}),slug:editing.slug,schoolId:editing.schoolId,isDiscoverable:editing.isDiscoverable,applicationOpen:editing.applicationOpen,applicationDeadline:editing.applicationDeadline,profile,reason});if(r.supportCode){setSupportCode(r.supportCode);throw Error(r.error)}if(r.error)throw Error(r.error);const next=await getAdminClub(r.id!);if(next.supportCode){setSupportCode(next.supportCode);return}setEditing(next.value!);setSaved(next.value!);setNotice('Club saved. No leadership was granted.');setError('')}finally{inFlight.current=false;setBusy(false)}}}/>
    <Dialog open={lifecycle} onOpenChange={setLifecycle}><DialogContent onCloseAutoFocus={e=>{e.preventDefault();if(origin.current?.isConnected)origin.current.focus();else heading.current?.focus()}}><DialogTitle>{editing.suspendedAt?'Restore club?':'Suspend club?'}</DialogTitle><DialogDescription>Use the existing operational suspension policy. Club records and history remain intact. Provide a reason of at least 10 characters.</DialogDescription><label>Reason<Input value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<Button disabled={busy||reason.trim().length<10} onClick={async()=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);try{await setAdminClubSuspended(editing.id,!editing.suspendedAt,reason);setLifecycle(false);setEditing(null);setRefresh(n=>n+1)}catch{setError('Club state could not be changed. Refresh before retrying.')}finally{inFlight.current=false;setBusy(false)}}}>Confirm {editing.suspendedAt?'restoration':'suspension'}</Button></DialogContent></Dialog>
  </div>;
  return <section aria-label="Club management" className="min-w-0 space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div className="flex min-w-0 flex-wrap gap-3"><label className="text-sm">Search clubs<Input value={query} placeholder="Name, slug or category" onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label className="text-sm">Club filter<NativeSelect value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}>{['ALL','ACTIVE','SUSPENDED','DISCOVERABLE','HIDDEN','RECRUITING'].map(s=><option key={s}>{s}</option>)}</NativeSelect></label></div><Button disabled={!data.schools.length||busy} onClick={()=>{const c=blank(data.schools[0].id);setEditing(c);setSaved(c);setReason('');setError('')}}>+ Create Club</Button></div>{error&&<p role="alert">{error}</p>}{loading?<p role="status">Loading clubs…</p>:!data.rows.length?<p>No matching clubs.</p>:<ul className="grid gap-4 lg:grid-cols-2">{data.rows.map(c=><li key={c.id} className="min-w-0 space-y-4 rounded-xl border bg-card p-5"><div className="flex min-w-0 items-center gap-3">{c.logoUrl&&<img src={clubAssetSource(c.logoUrl,true)} alt="" className="size-14 shrink-0 rounded-lg object-contain"/>}<div className="min-w-0"><h2 className="break-words font-semibold">{c.name}</h2><p className="break-all text-xs text-muted-foreground">/{c.slug}</p></div></div><p className="text-sm">{c.school.name} · {c.category}</p><p className="text-sm">{c.suspendedAt?'Suspended':'Active'} · {c.isDiscoverable?'Discoverable':'Hidden'} · {!c.suspendedAt&&c.applicationOpen&&c._count.pipelineRounds&&(!c.applicationDeadline||+new Date(c.applicationDeadline)>Date.now())?'Recruiting open':'Recruiting closed'}</p><p className="text-xs text-muted-foreground">{c._count.members} active members · {c.logoUrl&&c.tagline?'Branding configured':'Profile needs attention'}</p><Button variant="outline" disabled={busy} onClick={()=>void open(c.id)}>Edit {c.name}</Button></li>)}</ul>}<div className="flex flex-wrap items-center gap-3"><Button variant="outline" disabled={!page||loading} onClick={()=>setPage(n=>n-1)}>Previous</Button><span className="text-sm">Page {page+1}</span><Button variant="outline" disabled={!data.hasMore||loading} onClick={()=>setPage(n=>n+1)}>Next</Button><Button variant="ghost" disabled={loading} onClick={()=>setRefresh(n=>n+1)}>Refresh</Button></div></section>;
}
