"use client";
import { useEffect, useState } from "react";
import { readPlatformResource, changePlatformResource } from "@/actions/platform-admin";
import { clubPermissions, permissionLabels } from "@/lib/permissions";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
type Access = { id: string; userId: string; clubId: string; isOwner: boolean; permissions: string[]; status: string; user: { email: string }; club: { name: string } };
export function AdminPermissions({ userId = "" }: { userId?: string }) {
  const [rows, setRows] = useState<Access[]>([]), [query, setQuery] = useState(""), [selected, setSelected] = useState<Access | null>(null), [reason, setReason] = useState(""), [error, setError] = useState(""), [retry, setRetry] = useState(0), [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; readPlatformResource("memberships", 0, { query, userId }).then(r => { if (live) setRows(r as Access[]); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [query, userId, retry]);
  return <section className="space-y-5"><div className="grid gap-4 sm:grid-cols-3">{[["Platform administration", "Configured allowlist + active grant + fresh password and MFA elevation. Club roles cannot grant Admin access."], ["Club leadership", "Ownership and explicit permissions apply within one club."], ["Club membership", "Membership provides member access without recruitment or platform powers."]].map(([title, desc]) => <article className="rounded-xl border bg-card p-5" key={title}><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{desc}</p></article>)}</div><label className="block">Search club access<Input value={query} onChange={e => setQuery(e.target.value)} /></label>{error && <p role="alert">{error}</p>}
    <ul className="space-y-3">{rows.map(row => <li className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card p-4" key={row.id}><span>{row.user.email}<small className="block text-muted-foreground">{row.club.name} · {row.isOwner ? "Owner" : row.permissions.length ? "Leader" : "Member"} · {row.status}</small></span><Button variant="outline" onClick={() => { setSelected({ ...row, permissions: [...row.permissions] }); setReason(""); }}>Review club permissions</Button></li>)}</ul>{!rows.length && <p>No matching club memberships.</p>}
    {selected && <form className="space-y-4 rounded-xl border bg-card p-6" onSubmit={async e => { e.preventDefault(); if (!window.confirm(`Change club access for ${selected.user.email}?`)) return; setBusy(true); setError(""); try { await changePlatformResource({ kind: "membership", clubId: selected.clubId, userId: selected.userId, isOwner: selected.isOwner, permissions: selected.permissions }, reason); setSelected(null); setRetry(r => r + 1); } catch (e) { setError(e instanceof Error ? e.message : "Could not change permissions."); } finally { setBusy(false); } }}><h2 className="font-semibold">Club access for {selected.user.email}</h2><label className="flex items-center gap-2"><input type="checkbox" checked={selected.isOwner} onChange={e => setSelected(s => s && ({ ...s, isOwner: e.target.checked }))} />Club owner</label><div className="grid gap-3 sm:grid-cols-2">{clubPermissions.map(permission => <label className="flex items-center gap-2 text-sm" key={permission}><input type="checkbox" checked={selected.permissions.includes(permission)} onChange={e => setSelected(s => s && ({ ...s, permissions: e.target.checked ? [...s.permissions, permission] : s.permissions.filter(p => p !== permission) }))} />{permissionLabels[permission]}</label>)}</div><label className="block">Reason<Textarea required minLength={10} value={reason} onChange={e => setReason(e.target.value)} /></label><div className="flex gap-3"><Button disabled={busy}>Confirm access change</Button><Button variant="outline" type="button" onClick={() => setSelected(null)}>Cancel</Button></div></form>}
  </section>;
}
