"use client"
import { useEffect, useState, type ReactNode } from "react"
import { BarChart3, Eye, IdCard, Link2, Palette, Plus, RotateCcw, Sparkles, Users, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { ColorPicker } from "@/components/views/branding/color-picker"
import { MarketingProfile, MarketingSections } from "@/components/clubs/marketing-profile"
import { ProfileImageInput } from "@/components/clubs/profile-image-input"
import { clubProfileSchema, type ClubMarketing, type ClubProfileDraft } from "@/lib/club-marketing"

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm font-medium"><span>{label}</span>{children}</label> }
function Lines({ label, value, onChange, max }: { label: string; value: string[]; onChange: (v: string[]) => void; max: number }) {
  return <div className="space-y-2"><p className="text-sm font-medium">{label}</p>{value.map((v, i) => <div key={i} className="flex gap-2"><Input aria-label={`${label} ${i + 1}`} value={v} onChange={e => onChange(value.map((a, j) => i === j ? e.target.value : a))} /><Button type="button" variant="ghost" size="icon" aria-label={`Remove ${label} ${i + 1}`} onClick={() => onChange(value.filter((_, j) => j !== i))}><X size={16} /></Button></div>)}<Button type="button" variant="outline" size="sm" disabled={value.length >= max} onClick={() => onChange([...value, ""])}><Plus size={14} />Add {label.toLowerCase()}</Button></div>
}
function Records<T extends Record<string, string>>({ title, value, onChange, empty, max, onUpload }: { onUpload?: (file: File) => Promise<string>; title: string; value: T[]; onChange: (v: T[]) => void; empty: T; max: number }) {
  return <div className="space-y-3"><h3 className="oc-card-heading ">{title}</h3>{value.map((row, i) => <div key={i} className="space-y-3 rounded-lg border bg-muted/20 p-3">{Object.keys(empty).map(key => key === "image" ? <ProfileImageInput key={key} label={`${title} image ${i + 1}`} value={row[key]} onUpload={onUpload} onChange={v => onChange(value.map((r, j) => i === j ? { ...r, [key]: v ?? "" } : r))} /> : <Field key={key} label={`${key[0].toUpperCase()}${key.slice(1)}`}>{["answer", "description"].includes(key) ? <Textarea value={row[key]} onChange={e => onChange(value.map((r, j) => i === j ? { ...r, [key]: e.target.value } : r))} /> : <Input value={row[key]} onChange={e => onChange(value.map((r, j) => i === j ? { ...r, [key]: e.target.value } : r))} placeholder={key === "url" ? "https://…" : ""} />}</Field>)}<Button type="button" variant="ghost" size="sm" onClick={() => onChange(value.filter((_, j) => j !== i))}><X size={14} />Remove {title.toLowerCase()} {i + 1}</Button></div>)}<Button type="button" variant="outline" size="sm" disabled={value.length >= max} onClick={() => onChange([...value, { ...empty }])}><Plus size={14} />Add {title.toLowerCase()}</Button></div>
}
const sections = [{ id: "identity", title: "Identity & media", icon: IdCard }, { id: "theme", title: "Brand & theme", icon: Palette }, { id: "metrics", title: "Stats & achievements", icon: BarChart3 }, { id: "membership", title: "Member experience", icon: Users }, { id: "showcase", title: "Showcase & FAQs", icon: Sparkles }, { id: "links", title: "Socials & links", icon: Link2 }]

export function ClubProfileEditor({ initial, onSave, demo = false, onUpload, externalDirty = false }: { initial: ClubProfileDraft; onSave: (profile: ClubProfileDraft) => Promise<void>; demo?: boolean; onUpload?: (file: File) => Promise<string>; externalDirty?: boolean }) {
  const [draft, setDraft] = useState(initial), [saved, setSaved] = useState(initial)
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("")
  const [preview, setPreview] = useState(false)
  const dirty = externalDirty || JSON.stringify(draft) !== JSON.stringify(saved)
  useEffect(() => { if (!dirty && !busy) return; const warn = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = "" }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn) }, [dirty, busy])
  function set<K extends keyof ClubProfileDraft>(key: K, value: ClubProfileDraft[K]) { setDraft(d => ({ ...d, [key]: value })); setMessage(""); setError("") }
  function marketing<K extends keyof ClubMarketing>(key: K, value: ClubMarketing[K]) { set("marketing", { ...draft.marketing, [key]: value }) }
  function jump(id: string) { const node = document.getElementById(`profile-${id}`); if (node instanceof HTMLDetailsElement) { node.open = true; node.scrollIntoView({ behavior: "smooth", block: "start" }); node.querySelector("summary")?.focus() } }
  const m = draft.marketing
  return <form data-unsaved={dirty} data-saving={busy} className="space-y-5" onSubmit={async e => {
    e.preventDefault(); setError(""); setMessage("")
    if (e.currentTarget.querySelector('[data-saving="true"]')) { setError("Wait for the image to finish preparing."); return }
    const result = clubProfileSchema.safeParse(draft)
    if (!result.success) { const issue = result.error.issues[0]; setError(`${issue.path.filter(p => p !== "marketing").map(p => typeof p === "number" ? p + 1 : p.replace(/([A-Z])/g, " $1")).join(" · ")}: ${issue.message}`); return }
    setBusy(true)
    try { await onSave(result.data); setDraft(result.data); setSaved(result.data); setMessage(demo ? "Profile saved in this demo. Open Explore to see your changes." : "Profile published. Your changes are now visible in Explore.") }
    catch (error) { setError(error instanceof Error ? error.message : "Could not publish. Your edits are still here.") }
    finally { setBusy(false) }
  }}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">Your public presence</p><h2 className="oc-section-heading mt-2">Make your club stand out.</h2><p className="mt-2 text-sm text-muted-foreground">Tell your story. Show what makes joining worthwhile.</p></div><Button type="button" variant="outline" onClick={() => setPreview(!preview)}><Eye size={16} />{preview ? "Back to editor" : "Full profile preview"}</Button></div>
    {demo && <p className="text-xs text-muted-foreground">Demo changes stay in this browser.</p>}
    {preview ? <div className="mx-auto max-w-3xl space-y-5"><MarketingProfile assetPreview profile={draft} /><section className="rounded-xl border p-6"><h3 className="oc-card-heading ">About us</h3><p className="mt-3 whitespace-pre-line text-sm leading-7">{draft.description}</p></section><MarketingSections assetPreview profile={draft} /></div> : <>
      <nav aria-label="Profile editor sections" className="flex flex-wrap gap-2">{sections.map(s => <Button key={s.id} type="button" size="sm" variant="outline" onClick={() => jump(s.id)}>{s.title}</Button>)}</nav>
      <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,3fr)_minmax(300px,2fr)]">
        <fieldset disabled={busy} className="min-w-0 space-y-4">
          {sections.map(({ id, title, icon: Icon }) => <details key={id} id={`profile-${id}`} open className="scroll-mt-36 rounded-xl border bg-card p-5"><summary className="cursor-pointer text-sm font-semibold"><span className="ml-2 inline-flex items-center gap-2"><Icon size={18} />{title}</span></summary><div className="space-y-5 pt-6">
            {id === "identity" && <><div className="grid gap-4 sm:grid-cols-2"><Field label="Club name"><Input required maxLength={150} value={draft.name} onChange={e => set("name", e.target.value)} /></Field><Field label="Category"><Input required maxLength={100} list="club-categories" value={draft.category} onChange={e => set("category", e.target.value)} /><datalist id="club-categories">{["Finance", "Consulting", "Technology", "Arts & Culture", "Community Service", "Sports", "Academic", "Other"].map(c => <option key={c} value={c} />)}</datalist></Field></div><Field label="One-line pitch"><Input maxLength={300} value={draft.tagline} onChange={e => set("tagline", e.target.value)} placeholder="What makes your club different?" /></Field><Field label="About your club"><Textarea rows={6} maxLength={10000} value={draft.description} onChange={e => set("description", e.target.value)} /></Field><ProfileImageInput onUpload={onUpload} label="Club logo" value={draft.logoUrl} onChange={v => set("logoUrl", v)} /><ProfileImageInput onUpload={onUpload} label="Cover banner" banner value={draft.bannerUrl} onChange={v => set("bannerUrl", v)} /></>}
            {id === "theme" && <><ColorPicker value={draft.color} onChange={v => set("color", v)} /><p className="text-xs leading-6 text-muted-foreground">Your accent color appears on your profile cover and club identity. Use a six-digit hex code for a custom color.</p></>}
            {id === "metrics" && <><div className="grid gap-4 sm:grid-cols-2"><Field label="Acceptance rate (%)"><Input type="number" min="0" max="100" step="any" value={draft.acceptanceRate ?? ""} onChange={e => set("acceptanceRate", e.target.value === "" ? null : Number(e.target.value))} /></Field><Field label="Active members"><Input type="number" min="0" value={m.memberCount ?? ""} onChange={e => marketing("memberCount", e.target.value === "" ? null : Number(e.target.value))} /></Field></div><Field label="Assets under management ($)"><Input type="number" min="0" step="any" value={draft.aumValue ?? ""} onChange={e => set("aumValue", e.target.value === "" ? null : Number(e.target.value))} /></Field><div className="space-y-3">{([["showAcceptance", "Show acceptance rate"], ["showMembers", "Show member count"], ["showAum", "Show AUM"]] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-lg border p-3 text-sm">{label}<input type="checkbox" checked={m[key]} onChange={e => marketing(key, e.target.checked)} className="size-4 accent-primary" /></label>)}</div><Records title="Custom metric" value={m.metrics} onChange={v => marketing("metrics", v)} empty={{ label: "", value: "" }} max={6} /><Lines label="Member outcomes" value={m.placements} onChange={v => marketing("placements", v)} max={20} /><Lines label="Accolades" value={m.accolades} onChange={v => marketing("accolades", v)} max={20} /></>}
            {id === "membership" && <><Lines label="Member benefits" value={m.benefits} onChange={v => marketing("benefits", v)} max={12} /><Field label="Who can join"><Textarea maxLength={500} value={m.eligibility} onChange={e => marketing("eligibility", e.target.value)} placeholder="Open to all years and majors…" /></Field><Field label="Time commitment"><Input maxLength={150} value={m.commitment} onChange={e => marketing("commitment", e.target.value)} placeholder="e.g. 3–5 hours per week" /></Field><Field label="Membership dues"><Input maxLength={150} value={m.dues} onChange={e => marketing("dues", e.target.value)} placeholder="e.g. Free, or $25 per semester" /></Field></>}
            {id === "showcase" && <>
              <h3 className="font-semibold">Public content sections</h3><p className="text-sm text-muted-foreground">Order, hide, and edit programs, people, impact and recruitment copy. Application availability is managed separately.</p>
              {m.sections.map((block, i) => <div key={i} className="min-w-0 space-y-3 rounded-lg border p-4">
                <Field label={`Section ${i + 1} title`}><Input value={block.title} maxLength={100} onChange={e => marketing("sections", m.sections.map((s,j) => i===j ? {...s,title:e.target.value} : s))} /></Field>
                <Field label={`Section ${i + 1} type`}><select className="oc-native-select" value={block.kind} onChange={e => marketing("sections", m.sections.map((s,j) => i===j ? {...s,kind:e.target.value as typeof block.kind} : s))}>{["about","programs","people","impact","recruitment"].map(k=><option key={k}>{k}</option>)}</select></Field>
                <Field label={`Section ${i + 1} text`}><Textarea value={block.body} maxLength={5000} onChange={e => marketing("sections", m.sections.map((s,j) => i===j ? {...s,body:e.target.value} : s))} /></Field>
                <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={block.visible} onChange={e=>marketing("sections",m.sections.map((s,j)=>i===j?{...s,visible:e.target.checked}:s))}/>Show section</label>
                <Records onUpload={onUpload} title={`Section ${i + 1} card`} value={block.cards} onChange={cards=>marketing("sections",m.sections.map((s,j)=>i===j?{...s,cards}:s))} empty={{title:"",description:"",url:"",image:""}} max={12}/>
                <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={!i} onClick={()=>{const blocks=[...m.sections];[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];marketing("sections",blocks)}}>Move section up</Button><Button type="button" variant="outline" disabled={i===m.sections.length-1} onClick={()=>{const blocks=[...m.sections];[blocks[i+1],blocks[i]]=[blocks[i],blocks[i+1]];marketing("sections",blocks)}}>Move section down</Button><Button type="button" variant="ghost" onClick={()=>marketing("sections",m.sections.filter((_,j)=>i!==j))}>Remove section</Button></div>
              </div>)}
              <Button type="button" variant="outline" disabled={m.sections.length>=12} onClick={()=>marketing("sections",[...m.sections,{title:"New section",kind:"programs",visible:true,body:"",cards:[]}])}>Add content section</Button>
<Records title="Featured project" value={m.features} onChange={v => marketing("features", v)} empty={{ title: "", description: "", url: "" }} max={8} /><Field label="Introduction video link"><Input value={m.videoUrl} onChange={e => marketing("videoUrl", e.target.value)} placeholder="https://youtube.com/…" /></Field><div className="space-y-4"><h3 className="oc-card-heading ">Photo gallery</h3>{m.gallery.map((g, i) => <div key={i} className="space-y-3 rounded-lg border p-3"><ProfileImageInput onUpload={onUpload} label={`Gallery photo ${i + 1}`} banner value={g.url} onChange={v => marketing("gallery", m.gallery.map((p, j) => i === j ? { ...p, url: v ?? "" } : p))} /><Field label="Caption"><Input maxLength={180} value={g.caption} onChange={e => marketing("gallery", m.gallery.map((p, j) => i === j ? { ...p, caption: e.target.value } : p))} /></Field><Button type="button" variant="ghost" size="sm" onClick={() => marketing("gallery", m.gallery.filter((_, j) => j !== i))}>Remove photo</Button></div>)}<Button type="button" variant="outline" size="sm" disabled={m.gallery.length >= 6} onClick={() => marketing("gallery", [...m.gallery, { url: "", caption: "" }])}><Plus size={14} />Add photo</Button></div><Records title="FAQ" value={m.faqs} onChange={v => marketing("faqs", v)} empty={{ question: "", answer: "" }} max={12} /></>}
            {id === "links" && <><div className="grid gap-4 sm:grid-cols-2">{([["website", "Website URL"], ["linkedin", "LinkedIn URL"], ["instagram", "Instagram URL"], ["email", "Public contact email"]] as const).map(([key, label]) => <Field key={key} label={label}><Input type={key === "email" ? "email" : "text"} value={m[key]} onChange={e => marketing(key, e.target.value)} placeholder={key === "email" ? "hello@yourclub.org" : "https://…"} /></Field>)}</div><Records title="Additional link" value={m.links} onChange={v => marketing("links", v)} empty={{ label: "", url: "" }} max={12} /></>}
          </div></details>)}
        </fieldset>
        <aside className="hidden space-y-3 xl:sticky xl:top-36 xl:block"><p className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground"><Eye size={15} />Live public profile preview</p><MarketingProfile assetPreview profile={draft} compact action={<span className="rounded-md bg-primary px-4 py-2 text-xs text-primary-foreground">Apply now</span>} /><p className="text-xs leading-5 text-muted-foreground">Preview updates as you type. Publish when you’re ready.</p></aside>
      </div>
    </>}
    <div className="sticky bottom-0 z-10 flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card/95 p-4 shadow-sm backdrop-blur"><div className="min-w-0 text-sm" aria-live="polite">{error ? <p role="alert" className="text-destructive">{error}</p> : message || (dirty ? "Unpublished changes" : "All changes saved")}</div><div className="flex gap-2"><Button type="button" variant="outline" disabled={busy || !dirty} onClick={() => { setDraft(saved); setError(""); setMessage("Changes discarded.") }}><RotateCcw size={15} />Discard</Button><Button type="submit" disabled={busy || !dirty}>{busy ? "Publishing…" : demo ? "Save demo profile" : "Publish profile"}</Button></div></div>
  </form>
}
